Operator Console: FileAcquisition Class Reference
FileAcquisition Class Reference
Another class for loading an image file that loads into the critical buffer m_frame inherited from class ImageAcquisition.
#include <FileAcquisition.h>
Public Member Functions
FileAcquisition (void)
~FileAcquisition (void)
bool CaptureFrame ()
image is already in m_frame, so there's nothing to do
bool Close ()
bool Init (int width, int height, const char *filename)
Initializes the buffers inherited from class ImageAcquisition with 2 bytes per pixel.
bool Open ()
void SetFile (const CString filePathName)
FileAcquisition (void)
~FileAcquisition (void)
bool CaptureFrame ()
image is already in m_frame, so there's nothing to do
bool Close ()
bool Init (int width, int height, const char *filename)
bool Open ()
void SetFile (const CString filePathName)
Public Member Functions inherited from ImageAcquisition
ImageAcquisition (void)
virtual ~ImageAcquisition (void)
void GetFrame (void *buf)
virtual bool Init (int width, int height, int bytesPerPixel=4)
may be overridden, but be sure to call parent function also
unsigned int BytesPerFrame ()
unsigned int PixelsPerFrame ()
int GetHeight ()
CString & GetInfo ()
int GetWidth ()
void SetHeight (int height)
void SetWidth (int width)
ImageAcquisition (void)
virtual ~ImageAcquisition (void)
void GetFrame (void *buf)
virtual bool Init (int width, int height, int bytesPerPixel=4)
may be overridden, but be sure to call parent function also
unsigned int BytesPerFrame ()
unsigned int PixelsPerFrame ()
int GetHeight ()
CString & GetInfo ()
int GetWidth ()
void SetHeight (int height)
void SetWidth (int width)
Protected Member Functions
bool LoadFile ()
Loads an image file through a filestream and then copies into m_buf.
bool LoadFile ()
Protected Attributes
CString m_filename
fully-qualified image file name
Protected Attributes inherited from ImageAcquisition
CriticalBuf m_frame
shared memory to hold copy of current frame
int m_width
width of image in pixels
int m_height
height of image in pixels
unsigned int m_numBytes
number of bytes in a frame
unsigned int m_numPixels
number of pixels in a frame
CString m_logMsg
error or information message
void * m_buf
buffer to capture into
Additional Inherited Members
Static Public Member Functions inherited from ImageAcquisition
static UINT __cdecl ThreadProc (LPVOID param)
static UINT __cdecl ThreadProc (LPVOID param)
Detailed Description
Another class for loading an image file that loads into the critical buffer m_frame inherited from class ImageAcquisition.
Constructor & Destructor Documentation
FileAcquisition::FileAcquisition (void)
 {
    m_numPixels = 0;
    m_buf       = NULL;
    m_filename.Empty();
 }
FileAcquisition::~FileAcquisition (void)
 {
 }
FileAcquisition::FileAcquisition (void)
FileAcquisition::~FileAcquisition (void)
Member Function Documentation
bool FileAcquisition::CaptureFrame () inline virtual
image is already in m_frame, so there's nothing to do
Implements ImageAcquisition.
bool FileAcquisition::CaptureFrame () inline virtual
image is already in m_frame, so there's nothing to do
Implements ImageAcquisition.
bool FileAcquisition::Close () virtual
Implements ImageAcquisition.
 {
    return true;
 }
bool FileAcquisition::Close () virtual
Implements ImageAcquisition.
bool FileAcquisition::Init (int width, int height, const char * filename)
bool FileAcquisition::Init (int width, int height, const char * filename)
Initializes the buffers inherited from class ImageAcquisition with 2 bytes per pixel.
Returns
Returns TRUE if allocation is successful.
References ImageAcquisition::Init().
Referenced by COperatorConsoleApp::InitBlemishAcq(), and COperatorConsoleApp::InitSFRplusAcq().
 {
    bool  result;
    m_filename = filename;
    result     = ImageAcquisition::Init(width, height, 2);
    return result;
 }
bool FileAcquisition::LoadFile () protected
bool FileAcquisition::LoadFile () protected
Loads an image file through a filestream and then copies into m_buf.
Optionally, m_buf can be copied into the critical buffer, m_frame.
Returns
Returns TRUE if the file is loaded into m_buf, FALSE otherwise.
 {
    bool           success = false;
    ifstream::pos_type   size;
    ifstream       filestream(m_filename, ios::binary);
    if (!filestream.is_open())
    {
       m_logMsg.Format("%s: Unable to open image file '%s'", __FUNCTION__, m_filename);
    }
    else
    {
       filestream.seekg(0, ios::end);   // Determine length of file
       size = filestream.tellg();
       filestream.seekg(0, ios::beg);   // rewind
       //
       // Make sure that our buffer is large enough to hold the file
       //
       if (m_numBytes != (unsigned int)size)
       {
          m_logMsg.Format("%s: '%s' is too big for buffer", __FUNCTION__, m_filename);
       }
       else if (m_buf == NULL)
       {
          m_logMsg.Format("%s: m_buf is NULL", __FUNCTION__);
       }
       else
       {
          //
          // Read the contents of the file into m_buf, closing the file when done
          //
          filestream.read((char *)m_buf, size);
          filestream.close();
          m_logMsg.Format("%s:  Read in %d bytes", __FUNCTION__, (long)size);
 #if 0
          m_frame.Set(m_buf);  // this copies m_buf to shared memory that gets accessed by GetFrame()
 #endif
          success = true;
       }
    }
    return success;
 }
bool FileAcquisition::Open () virtual
Implements ImageAcquisition.
bool FileAcquisition::Open () virtual
Implements ImageAcquisition.
Referenced by COperatorConsoleApp::InitBlemishAcq(), and COperatorConsoleApp::InitSFRplusAcq().
 {
    bool result = LoadFile();
    return result;
 }
void FileAcquisition::SetFile (const CString filePathName) inline
References m_filename.
 {m_filename = filePathName;}
void FileAcquisition::SetFile (const CString filePathName) inline
References m_filename.
 {m_filename = filePathName;}
Member Data Documentation
CString FileAcquisition::m_filename protected
fully-qualified image file name
Referenced by SetFile().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/FileAcquisition.h
FileAcquisition.h
Documentation/Operator-Console/FileAcquisition.cpp
FileAcquisition.cpp