Operator Console: Documentation/Operator-Console/JSON/NumberToString.h File Reference
NumberToString.h File Reference
#include <limits>
#include "JSONDebug.h"
#include "JSONSharedString.h"
#include <cstdio>
Classes
struct getLenSize< GETLENSIZE >
struct getLenSize< 1 >
struct getLenSize< 2 >
struct getLenSize< 4 >
struct getLenSize< 8 >
class NumberToString
Macros
#define EXTRA_LONG long
#define FLOAT_STRING "%Lf"
#define LFLOAT_STRING L"%Lf"
Functions
static bool _floatsAreEqual (const json_number &one, const json_number &two) json_pure
Class Documentation
struct getLenSize
template<unsigned int GETLENSIZE>
struct getLenSize< GETLENSIZE >
Class Members
__unnamed__
__unnamed__
Class Members
char tmp[GETLENSIZE==16]
struct getLenSize< 1 >
template<>
struct getLenSize< 1 >
Class Members
__unnamed__
__unnamed__
struct getLenSize< 2 >
template<>
struct getLenSize< 2 >
Class Members
__unnamed__
__unnamed__
struct getLenSize< 4 >
template<>
struct getLenSize< 4 >
Class Members
__unnamed__
__unnamed__
struct getLenSize< 8 >
template<>
struct getLenSize< 8 >
Class Members
__unnamed__
__unnamed__
Macro Definition Documentation
#define EXTRA_LONG long
Referenced by NumberToString::_ftoa().
#define FLOAT_STRING "%Lf"
Referenced by NumberToString::_ftoa().
#define LFLOAT_STRING L"%Lf"
Referenced by NumberToString::_ftoa().
Function Documentation
static bool _floatsAreEqual (const json_number & one, const json_number & two) inline static
References JSON_FLOAT_THRESHHOLD.
Referenced by NumberToString::_ftoa(), internalJSONNode::IsEqualTo(), and internalJSONNode::operator bool().
{
     return (one > two) ? (one - two) < JSON_FLOAT_THRESHHOLD : (one - two) > -JSON_FLOAT_THRESHHOLD;
 }