Operator Console: JSONWorker Class Reference
JSONWorker Class Reference
#include <JSONWorker.h>
Static Public Member Functions
static json_string RemoveWhiteSpaceAndComments (const json_string &value_t, bool escapeQuotes) json_nothrow json_read_priority
static void DoArray (const internalJSONNode *parent, const json_string &value_t) json_nothrow json_read_priority
static void DoNode (const internalJSONNode *parent, const json_string &value_t) json_nothrow json_read_priority
static json_string FixString (const json_string &value_t, bool &flag) json_nothrow json_read_priority
template<json_char ch>
static size_t FindNextRelevant (const json_string &value_t, const size_t pos) json_nothrow json_read_priority
static void UnfixString (const json_string &value_t, bool flag, json_string &res) json_nothrow
static JSON_PRIVATE json_char Hex (const json_char *&pos) json_nothrow
static json_uchar UTF8 (const json_char *&pos) json_nothrow
static json_string toUTF8 (json_uchar p) json_nothrow
static void SpecialChar (const json_char *&pos, json_string &res) json_nothrow
static void NewNode (const internalJSONNode *parent, const json_string &name, const json_string &value, bool array) json_nothrow
static json_string RemoveWhiteSpaceAndComments (const json_string &value_t, bool escapeQuotes) json_nothrow json_read_priority
static void DoArray (const internalJSONNode *parent, const json_string &value_t) json_nothrow json_read_priority
static void DoNode (const internalJSONNode *parent, const json_string &value_t) json_nothrow json_read_priority
static json_string FixString (const json_string &value_t, bool &flag) json_nothrow json_read_priority
template<json_char ch>
static size_t FindNextRelevant (const json_string &value_t, const size_t pos) json_nothrow json_read_priority
static void UnfixString (const json_string &value_t, bool flag, json_string &res) json_nothrow
static JSON_PRIVATE json_char Hex (const json_char *&pos) json_nothrow
static json_uchar UTF8 (const json_char *&pos) json_nothrow
static json_string toUTF8 (json_uchar p) json_nothrow
static void SpecialChar (const json_char *&pos, json_string &res) json_nothrow
static void NewNode (const internalJSONNode *parent, const json_string &name, const json_string &value, bool array) json_nothrow
Static Public Attributes
static JSONNode static parse(const
json_string &json) json_throws(std
JSONNode static
parse_unformatted(const
json_string &json) json_throws(std
JSONNode static
_parse_unformatted(const
json_char *json) json_throws(std
json_char RemoveWhiteSpace)(const json_string &value_t, bool escapeQuotes) json_nothrow json_read_priority
Member Function Documentation
void JSONWorker::DoArray (const internalJSONNode * parent, const json_string & value_t) static
References FIND_NEXT_RELEVANT, JSON_ASSERT, JSON_ASSERT_SAFE, json_global, JSON_TEXT, and json_unlikely.
Referenced by internalJSONNode::FetchArray().
{
    //This takes an array and creates nodes out of them
    JSON_ASSERT(!value_t.empty(), JSON_TEXT("DoArray is empty"));
    JSON_ASSERT_SAFE(value_t[0] == JSON_TEXT('['), JSON_TEXT("DoArray is not an array"), parent -> Nullify(); return;);
    if (json_unlikely(value_t.length() <= 2)) return;  // just a [] (blank array)
    #ifdef JSON_SAFE
       json_string newValue;  //share this so it has a reserved buffer
    #endif
    size_t starting = 1;  //ignore the [
    //Not sure what's in the array, so we have to use commas
    for(size_t ending = FIND_NEXT_RELEVANT(JSON_TEXT(','), value_t, 1);
       ending != json_string::npos;
       ending = FIND_NEXT_RELEVANT(JSON_TEXT(','), value_t, starting)){
       #ifdef JSON_SAFE
          newValue.assign(value_t.begin() + starting, value_t.begin() + ending);
          JSON_ASSERT_SAFE(FIND_NEXT_RELEVANT(JSON_TEXT(':'), newValue, 0) == json_string::npos, JSON_TEXT("Key/Value pairs are not allowed in arrays"), parent -> Nullify(); return;);
          NewNode(parent, json_global(EMPTY_JSON_STRING), newValue, true);
       #else
          NewNode(parent, json_global(EMPTY_JSON_STRING), json_string(value_t.begin() + starting, value_t.begin() + ending), true);
       #endif
       starting = ending + 1;
    }
    //since the last one will not find the comma, we have to add it here, but ignore the final ]
    #ifdef JSON_SAFE
       newValue.assign(value_t.begin() + starting, value_t.end() - 1);
       JSON_ASSERT_SAFE(FIND_NEXT_RELEVANT(JSON_TEXT(':'), newValue, 0) == json_string::npos, JSON_TEXT("Key/Value pairs are not allowed in arrays"), parent -> Nullify(); return;);
       NewNode(parent, json_global(EMPTY_JSON_STRING), newValue, true);
    #else
       NewNode(parent, json_global(EMPTY_JSON_STRING), json_string(value_t.begin() + starting, value_t.end() - 1), true);
    #endif
 }
static void JSONWorker::DoArray (const internalJSONNode * parent, const json_string & value_t) static
void JSONWorker::DoNode (const internalJSONNode * parent, const json_string & value_t) static
References FIND_NEXT_RELEVANT, JSON_ASSERT, JSON_ASSERT_SAFE, JSON_TEXT, and json_unlikely.
Referenced by internalJSONNode::FetchNode().
{
    //This take a node and creates its members and such
    JSON_ASSERT(!value_t.empty(), JSON_TEXT("DoNode is empty"));
    JSON_ASSERT_SAFE(value_t[0] == JSON_TEXT('{'), JSON_TEXT("DoNode is not an node"), parent -> Nullify(); return;);
    if (json_unlikely(value_t.length() <= 2)) return;  // just a {} (blank node)
    size_t name_ending = FIND_NEXT_RELEVANT(JSON_TEXT(':'), value_t, 1);  //find where the name ends
    JSON_ASSERT_SAFE(name_ending != json_string::npos, JSON_TEXT("Missing :"), parent -> Nullify(); return;);
    json_string name(value_t.begin() + 1, value_t.begin() + name_ending - 1);    //pull the name out
    for (size_t value_ending = FIND_NEXT_RELEVANT(JSON_TEXT(','), value_t, name_ending),  //find the end of the value
        name_starting = 1;  //ignore the {
        value_ending != json_string::npos;
        value_ending = FIND_NEXT_RELEVANT(JSON_TEXT(','), value_t, name_ending)){
       NewNode(parent, name, json_string(value_t.begin() + name_ending + 1, value_t.begin() + value_ending), false);
       name_starting = value_ending + 1;
       name_ending = FIND_NEXT_RELEVANT(JSON_TEXT(':'), value_t, name_starting);
       JSON_ASSERT_SAFE(name_ending != json_string::npos, JSON_TEXT("Missing :"), parent -> Nullify(); return;);
       name.assign(value_t.begin() + name_starting, value_t.begin() + name_ending - 1);
    }
    //since the last one will not find the comma, we have to add it here
    NewNode(parent, name, json_string(value_t.begin() + name_ending + 1, value_t.end() - 1), false);
 }
static void JSONWorker::DoNode (const internalJSONNode * parent, const json_string & value_t) static
template<json_char ch> size_t JSONWorker::FindNextRelevant (const json_string & value_t, const size_t pos) static
References BRACKET, json_char, json_nothrow, JSON_TEXT, json_unlikely, and QUOTECASE.
{
    #else
       #define FIND_NEXT_RELEVANT(ch, vt, po) JSONWorker::FindNextRelevant(ch, vt, po)
       size_t JSONWorker::FindNextRelevant(json_char ch, const json_string & value_t, const size_t pos) json_nothrow {
    #endif
          //TODO get rid of the c_str and use an iterator to take advantage of shared strings
       json_string::const_iterator start = value_t.begin();
       for (json_string::const_iterator p = start + pos; *p; ++p){
         if (json_unlikely(*p == ch)) return p - start;
         switch (*p){
             BRACKET(JSON_TEXT('['), JSON_TEXT(']'))
             BRACKET(JSON_TEXT('{'), JSON_TEXT('}'))
             QUOTECASE()
         }
       };
       return json_string::npos;
     }
template<json_char ch> static size_t JSONWorker::FindNextRelevant (const json_string & value_t, const size_t pos) static
json_string JSONWorker::FixString (const json_string & value_t, bool & flag) static
References json_char, JSON_TEXT, setflag, and shrinkString.
Referenced by internalJSONNode::FetchString().
{
     #define setflag(x) flag = x
 #endif
     //Do things like unescaping
     setflag(false);
     json_string res;
     res.reserve(value_t.length());   //since it goes one character at a time, want to reserve it first so that it doens't have to reallocating
     for(const json_char * p = value_t.c_str(); *p; ++p){
       switch (*p){
         case JSON_TEXT('\\'):
           setflag(true);
           SpecialChar(++p, res);
           break;
         default:
           res += *p;
           break;
       }
     }
     return shrinkString(res);  //because this is actually setting something to be stored, shrink it it need be
 }
static json_string JSONWorker::FixString (const json_string & value_t, bool & flag) static
static JSON_PRIVATE json_char JSONWorker::Hex (const json_char *& pos) static
json_char JSONWorker::Hex (const json_char *& pos) static
References json_char, and json_uchar.
{
     /*
    takes the numeric value of the next two characters and convert them
    \u0058 becomes 0x58
    In case of \u, it's SpecialChar's responsibility to move past the first two chars
    as this method is also used for \x
    */
     //First character
     json_uchar hi = *pos++ - 48;
     if (hi > 48){  //A-F don't immediately follow 0-9, so have to pull them down a little
       hi -= 39;
     } else if (hi > 9){  //neither do a-f
       hi -= 7;
     }
     //second character
     json_uchar lo = *pos - 48;
     if (lo > 48){  //A-F don't immediately follow 0-9, so have to pull them down a little
       lo -= 39;
     } else if (lo > 9){  //neither do a-f
       lo -= 7;
     }
     //combine them
     return (json_char)((hi << 4) | lo);
 }
static void JSONWorker::NewNode (const internalJSONNode * parent, const json_string & name, const json_string & value, bool array) static
static void JSONWorker::NewNode (const internalJSONNode * parent, const json_string & name, const json_string & value, bool array) static
json_string JSONWorker::RemoveWhiteSpaceAndComments (const json_string & value_t, bool escapeQuotes) static
References ascii_one(), JSON_ASSERT_SAFE, json_char, JSON_TEXT, json_uchar, json_unlikely, and SingleLineComment().
Referenced by libjson::is_valid(), and libjson::strip_white_space().
{
     json_string result;
     result.reserve(value_t.length());
    try {
       for(const json_char * p = value_t.c_str(); *p; ++p){
          switch(*p){
            case JSON_TEXT(' '):   //defined as white space
            case JSON_TEXT('\t'):  //defined as white space
            case JSON_TEXT('\n'):  //defined as white space
            case JSON_TEXT('\r'):  //defined as white space
              break;
            #ifndef JSON_STRICT
              case JSON_TEXT('/'):  //a C comment
                if (*(++p) == JSON_TEXT('*')){  //a multiline comment
                   while ((*(++p) != JSON_TEXT('*')) || (*(p + 1) != JSON_TEXT('/'))){
                      if (json_unlikely(*p == JSON_TEXT('\0'))) throw false;
                   }
                   ++p;
                   break;
                }
                //Should be a single line C comment, so let it fall through to use the bash comment stripper
                JSON_ASSERT_SAFE(*p == JSON_TEXT('/'), JSON_TEXT("stray / character, not quoted, or a comment"), throw false;);
              case JSON_TEXT('#'):  //a bash comment
                SingleLineComment(p);
                break;
            #endif
            case JSON_TEXT('\"'):  //a quote
              result += JSON_TEXT('\"');
              while(*(++p) != JSON_TEXT('\"')){  //find the end of the quotation, as white space is preserved within it
                switch(*p){
                   case JSON_TEXT('\\'):
                      result += JSON_TEXT('\\');
                             if (escapeQuotes){
                                 result += (*++p == JSON_TEXT('\"')) ? ascii_one() : *p;  //an escaped quote will reak havoc will all of my searching functions, so change it into an illegal character in JSON for convertion later on
                             }
                      break;
                   case '\0':
                      throw false;
                   default:
                      result += *p;
                      break;
                }
              }
              //no break, let it fall through so that the trailing quote gets added
            default:
              JSON_ASSERT_SAFE((json_uchar)*p >= 32, JSON_TEXT("Invalid JSON character detected (lo)"), throw false;);
              JSON_ASSERT_SAFE((json_uchar)*p <= 126, JSON_TEXT("Invalid JSON character detected (hi)"), throw false;);
              result += *p;
              break;
          }
       }
    } catch (...){}
     return result;
 }
static json_string JSONWorker::RemoveWhiteSpaceAndComments (const json_string & value_t, bool escapeQuotes) static
void JSONWorker::SpecialChar (const json_char *& pos, json_string & res) static
References FromOctal(), JSON_FAIL, and JSON_TEXT.
{
     /*
       Since JSON uses forward slash escaping for special characters within strings, I have to
       convert these escaped characters into C characters
    */
     switch(*pos){
       case JSON_TEXT('\1'):  //quote character (altered by RemoveWhiteSpace)
         res += JSON_TEXT('\"');
         break;
       case JSON_TEXT('t'): //tab character
         res += JSON_TEXT('\t');
         break;
       case JSON_TEXT('n'): //newline character
         res += JSON_TEXT('\n');
         break;
       case JSON_TEXT('r'): //return character
         res += JSON_TEXT('\r');
         break;
       case JSON_TEXT('\\'):   //backslash
         res += JSON_TEXT('\\');
         break;
       case JSON_TEXT('/'): //forward slash
         res += JSON_TEXT('/');
         break;
       case JSON_TEXT('b'): //backspace
         res += JSON_TEXT('\b');
         break;
       case JSON_TEXT('f'): //formfeed
         res += JSON_TEXT('\f');
         break;
       case JSON_TEXT('v'): //vertical tab
         res += JSON_TEXT('\v');
         break;
       case JSON_TEXT('u'): //utf character
         #ifdef JSON_UNICODE
           UTF(pos, res);
         #else
           res += UTF8(pos);
         #endif
         break;
       #ifndef JSON_STRICT
         case JSON_TEXT('x'):   //hexidecimal ascii code
           res += Hex(++pos);
           break;
         #ifdef __GNUC__
           case JSON_TEXT('0') ... JSON_TEXT('7'):
         #else
           //octal encoding
           case JSON_TEXT('0'):
           case JSON_TEXT('1'):
           case JSON_TEXT('2'):
           case JSON_TEXT('3'):
           case JSON_TEXT('4'):
           case JSON_TEXT('5'):
           case JSON_TEXT('6'):
           case JSON_TEXT('7'):
         #endif
           res += FromOctal(pos);
           break;
         default:
           res += *pos;
           break;
       #elif defined(JSON_DEBUG)
         default:
           JSON_FAIL(JSON_TEXT("Unsupported escaped character"));
           break;
       #endif
     }
 }
static void JSONWorker::SpecialChar (const json_char *& pos, json_string & res) static
json_string JSONWorker::toUTF8 (json_uchar p) static
References END_MEM_SCOPE, JSON_TEXT, json_uchar, json_unlikely, and START_MEM_SCOPE.
{
       #ifdef JSON_UNICODE
         if (json_unlikely(p > 0xFFFF)) return toSurrogatePair(p);
       #endif
       json_string res(JSON_TEXT("\\u"));
       #ifdef JSON_UNICODE
         START_MEM_SCOPE
           json_uchar hihi = ((p & 0xF000) >> 12) + 48;
           if (hihi > 57) hihi += 7; //A-F don't immediately follow 0-9, so have to further adjust those
           json_uchar hilo = ((p & 0x0F00) >> 8) + 48;
           if (hilo > 57) hilo += 7; //A-F don't immediately follow 0-9, so have to further adjust those
           res += hihi;
           res += hilo;
         END_MEM_SCOPE
         json_uchar hi = ((p & 0x00F0) >> 4) + 48;
       #else
         res += JSON_TEXT("00");
         json_uchar hi = (p >> 4) + 48;
       #endif
       //convert the character to be escaped into two digits between 0 and 15
       if (hi > 57) hi += 7; //A-F don't immediately follow 0-9, so have to further adjust those
       json_uchar lo = (p & 0x000F) + 48;
       if (lo > 57) lo += 7; //A-F don't immediately follow 0-9, so have to further adjust those
       res += hi;
       res += lo;
       return res;
     }
static json_string JSONWorker::toUTF8 (json_uchar p) static
void JSONWorker::UnfixString (const json_string & value_t, bool flag, json_string & res) static
References json_char, JSON_TEXT, json_uchar, and json_unlikely.
Referenced by internalJSONNode::Write(), and internalJSONNode::WriteName().
{
     if (!flag){
       res += value_t;
       return;
    }
     //Re-escapes a json_string so that it can be written out into a JSON file
     for(const json_char * p = value_t.c_str(); *p; ++p){
       switch(*p){
         case JSON_TEXT('\"'):  //quote character
           res += JSON_TEXT("\\\"");
           break;
         case JSON_TEXT('\\'): //backslash
           res += JSON_TEXT("\\\\");
           break;
         #ifdef JSON_ESCAPE_WRITES
           case JSON_TEXT('\t'):  //tab character
             res += JSON_TEXT("\\t");
             break;
           case JSON_TEXT('\n'):  //newline character
             res += JSON_TEXT("\\n");
             break;
           case JSON_TEXT('\r'):  //return character
             res += JSON_TEXT("\\r");
             break;
           case JSON_TEXT('/'):   //forward slash
             res += JSON_TEXT("\\/");
             break;
           case JSON_TEXT('\b'):  //backspace
             res += JSON_TEXT("\\b");
             break;
           case JSON_TEXT('\f'):  //formfeed
             res += JSON_TEXT("\\f");
             break;
           default:
             if (json_unlikely(((json_uchar)(*p) < 32) || ((json_uchar)(*p) > 126))){
                 res += toUTF8((json_uchar)(*p));
             } else {
                 res += *p;
             }
             break;
         #else
           default:
             res += *p;
             break;
         #endif
       }
     }
 }
static void JSONWorker::UnfixString (const json_string & value_t, bool flag, json_string & res) static
json_uchar JSONWorker::UTF8 (const json_char *& pos) static
References JSON_ASSERT, JSON_TEXT, and json_uchar.
{
     #ifdef JSON_UNICODE
       ++pos;
       json_uchar temp = Hex(pos) << 8;
       ++pos;
       return temp | Hex(pos);
     #else
       JSON_ASSERT(*(pos + 1) == JSON_TEXT('0'), JSON_TEXT("wide utf character (hihi)"));
       JSON_ASSERT(*(pos + 2) == JSON_TEXT('0'), JSON_TEXT("wide utf character (hilo)"));
       pos += 3;
       return Hex(pos);
     #endif
 }
static json_uchar JSONWorker::UTF8 (const json_char *& pos) static
Member Data Documentation
json_char * JSONWorker::RemoveWhiteSpace static
Referenced by JSONStream::parse(), and libjson::parse().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/JSON/JSONWorker.h
Documentation/Operator-Console/JSON/JSONWorker.cpp