Operator Console: TextDlg Class Reference
TextDlg Class Reference
TextDlg dialog.
#include <TextDlg.h>
Public Types
enum { IDD = IDD_TEXTDIALOG }
enum { IDD = IDD_TEXTDIALOG }
Public Member Functions
TextDlg (CWnd *pParent=NULL)
standard constructor
virtual ~TextDlg ()
void SetText (LPCTSTR text)
set the contents of the window to the string pointed to by 'text'
void SetTitle (LPCTSTR title)
sets the window's title
void Show (bool show)
show or hide the window
afx_msg void OnClose ()
TextDlg (CWnd *pParent=NULL)
standard constructor
virtual ~TextDlg ()
void SetText (LPCTSTR text)
set the contents of the window to the string pointed to by 'text'
void SetTitle (LPCTSTR title)
sets the window's title
void Show (bool show)
show or hide the window
afx_msg void OnClose ()
Public Attributes
CEdit c_text
Protected Member Functions
virtual void DoDataExchange (CDataExchange *pDX)
for DDX/DDV support
virtual void DoDataExchange (CDataExchange *pDX)
for DDX/DDV support
Detailed Description
TextDlg dialog.
Member Enumeration Documentation
anonymous enum
Enumerator
IDD
 { IDD = IDD_TEXTDIALOG };
anonymous enum
Enumerator
IDD
 { IDD = IDD_TEXTDIALOG };
Constructor & Destructor Documentation
TextDlg::TextDlg (CWnd * pParent = NULL)
standard constructor
References IDD.
    : CDialogEx(TextDlg::IDD, pParent)
 {
    Create(TextDlg::IDD);
 }
TextDlg::~TextDlg () virtual
 {
    DestroyWindow();
 }
TextDlg::TextDlg (CWnd * pParent = NULL)
standard constructor
virtual TextDlg::~TextDlg () virtual
Member Function Documentation
void TextDlg::DoDataExchange (CDataExchange * pDX) protected virtual
for DDX/DDV support
References c_text, and IDC_TEXT.
 {
    CDialogEx::DoDataExchange(pDX);
    DDX_Control(pDX, IDC_TEXT, c_text);
 }
virtual void TextDlg::DoDataExchange (CDataExchange * pDX) protected virtual
for DDX/DDV support
void TextDlg::OnClose ()
 {
    ShowWindow(false);   // if the user clicked on the Cloe button, just hide the window rather than destroying it
 }
afx_msg void TextDlg::OnClose ()
void TextDlg::SetText (LPCTSTR text)
set the contents of the window to the string pointed to by 'text'
References c_text.
Referenced by ModelessDialogThread::SetText().
 {
    c_text.SetSel(0, -1);      // select all the text
    c_text.ReplaceSel(text);   // replace selection
 }
void TextDlg::SetText (LPCTSTR text)
set the contents of the window to the string pointed to by 'text'
void TextDlg::SetTitle (LPCTSTR title)
sets the window's title
Referenced by ModelessDialogThread::SetTitle().
 {
    SetWindowText(title);
 }
void TextDlg::SetTitle (LPCTSTR title)
sets the window's title
void TextDlg::Show (bool show)
show or hide the window
Referenced by ModelessDialogThread::Show().
 {
    ShowWindow(show ? SW_SHOW : SW_HIDE);
    if (show)
       BringWindowToTop();
 }
void TextDlg::Show (bool show)
show or hide the window
Member Data Documentation
CEdit TextDlg::c_text
Referenced by DoDataExchange(), and SetText().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/TextDlg.h
TextDlg.h
Documentation/Operator-Console/TextDlg.cpp
TextDlg.cpp