Operator Console: Documentation/Operator-Console/OperatorConsole.cpp File Reference
OperatorConsole.cpp File Reference
#include "stdafx.h"
#include "Config.h"
#include "imatest_library.h"
#include "OperatorConsole.h"
#include "OperatorConsoleDlg.h"
#include "Setup.h"
#include "PassFail.h"
#include "PasswordDialog.h"
#include <sstream>
Macros
#define REDIRECT_STDIO
OperatorConsole.cpp : Defines the class behaviors for the application.
#define STDOUT_BUFSIZE 32768
#define START_TEST_FROM_FRAME_READY
#define USE_RGB_DATA
#define LOG_FILENAME ".\\log.txt"
Functions
template<typename T >
const std::string writeEntValueString (const entry< T > &ent)
Converts the entry<T>.value into a std::string to facilitate writing to the pass/fail file.
template<>
const std::string writeEntValueString (const entry< CString > &ent)
Converts the entry<CString>.value into a std::string to facilitate writing to the pass/fail file.
template<typename T >
const std::string writeMinMaxEntValueString (const minMaxEntry< T > &ent)
Converts the minMaxEntry<CString>.min_val and .max_val into a std::string to facilitate writing to the pass/fail file.
template<typename T >
const std::string writeVecEntValueString (const vecEntry< T > &ent)
Converts the vecEntry<CString>.value into a single std::string to facilitate writing to the pass/fail file.
void addKeysAndValues (const std::string &candidateKey, const std::string &candidateVal, std::vector< std::string > &keys, std::vector< std::string > &vals, bool b_addKey)
Conditionally adds a particular key (variable name) and value to the std::vector<std::string> keys, vals if the particular key is in use by the pass/fail file.
void addDataTypeAndKey (const std::string &candidateDT, const CString &candidateKey, std::vector< std::string > &data_types, std::vector< CString > &keys)
Adds a data_type string and key string to the std::vector<std::string> data_types and keys, respectively.
Variables
COperatorConsoleApp theApp
The one and only COperatorConsoleApp object.
Macro Definition Documentation
#define LOG_FILENAME ".\\log.txt"
Referenced by COperatorConsoleApp::Quit().
#define REDIRECT_STDIO
OperatorConsole.cpp : Defines the class behaviors for the application.
#define START_TEST_FROM_FRAME_READY
#define STDOUT_BUFSIZE 32768
Referenced by COperatorConsoleApp::InitOutput().
#define USE_RGB_DATA
Function Documentation
void addDataTypeAndKey (const std::string & candidateDT, const CString & candidateKey, std::vector< std::string > & data_types, std::vector< CString > & keys)
Adds a data_type string and key string to the std::vector<std::string> data_types and keys, respectively.
Referenced by COperatorConsoleApp::ReadPassFail().
 {
    data_types.push_back(candidateDT);
    keys.push_back(candidateKey);
 }
void addKeysAndValues (const std::string & candidateKey, const std::string & candidateVal, std::vector< std::string > & keys, std::vector< std::string > & vals, bool b_addKey)
Conditionally adds a particular key (variable name) and value to the std::vector<std::string> keys, vals if the particular key is in use by the pass/fail file.
Referenced by COperatorConsoleApp::WritePassFail().
 {
    if (b_addKey)
    {
       keys.push_back(candidateKey);
       vals.push_back(candidateVal);
    }
 }
template<typename T > const std::string writeEntValueString (const entry< T > & ent)
Converts the entry<T>.value into a std::string to facilitate writing to the pass/fail file.
Referenced by COperatorConsoleApp::WritePassFail().
 {
    stringstream ss;
    ss << ent.value;
    return ss.str();
 }
template<> const std::string writeEntValueString (const entry< CString > & ent)
Converts the entry<CString>.value into a std::string to facilitate writing to the pass/fail file.
References entry< T >::value.
 {
    stringstream ss;
    ss << ent.value.GetString();
    return ss.str();
 }
template<typename T > const std::string writeMinMaxEntValueString (const minMaxEntry< T > & ent)
Converts the minMaxEntry<CString>.min_val and .max_val into a std::string to facilitate writing to the pass/fail file.
References minMaxEntry< T >::max_val, and minMaxEntry< T >::min_val.
Referenced by COperatorConsoleApp::WritePassFail().
 {
    stringstream ss;
    ss<< ent.min_val << " " << ent.max_val;
    return ss.str();
 }
template<typename T > const std::string writeVecEntValueString (const vecEntry< T > & ent)
Converts the vecEntry<CString>.value into a single std::string to facilitate writing to the pass/fail file.
References vecEntry< T >::value.
Referenced by COperatorConsoleApp::WritePassFail().
 {
    stringstream ss;
    for(std::size_t idx =0 ; idx < ent.value.size(); ++idx)
    {
       ss << ent.value[idx] << " ";
    }
    return ss.str();
 }
Variable Documentation
COperatorConsoleApp theApp
The one and only COperatorConsoleApp object.