Operator Console: SFRplusTest Class Reference
SFRplusTest Class Reference
contains the details of an sfrPlus test to be performed including all relevant fields for determining pass or fail
#include <SFRplusTest.h>
Public Member Functions
SFRplusTest (void)
virtual ~SFRplusTest (void)
const bool * GetQSO ()
SFRplusTest (void)
virtual ~SFRplusTest (void)
const bool * GetQSO ()
void ClearQSO (void)
Public Member Functions inherited from ImageTest
ImageTest (void)
virtual ~ImageTest (void)
virtual void Run ()
Runs the test pointed to by m_imatestFunc.
virtual void Run (void *raw_pixels, int width, int height, const Config *config)
void GetLog (CString &dst)
void GetFailInfo (CString &dst)
void GetJSON (CString &dst)
void GetName (CString &name)
void GetSummary (CString &dst)
void Init (void *raw_pixels, int width, int height, const Config *config)
bool Passed ()
void SetBuffer (void *buf)
ImageTest (void)
virtual ~ImageTest (void)
virtual void Run ()
virtual void Run (void *raw_pixels, int width, int height, const Config *config)
void GetLog (CString &dst)
void GetFailInfo (CString &dst)
void GetJSON (CString &dst)
void GetName (CString &name)
void GetSummary (CString &dst)
void Init (void *raw_pixels, int width, int height, const Config *config)
bool Passed ()
void SetBuffer (void *buf)
Protected Member Functions
void GetResults (JSONNode &passfail)
Gets the pass/fail results for a range of pass/fail metrics to be displayed in summary dialog.
void ParseResults (string &results)
Parses the JSON output of an sfrPlus test to determine the pass/fail status of the various metrics.
void ParseOverlay (JSONNode &data, JSONNode &passfail)
Determines the pass/fail result for each quadrant.
void GetResults (JSONNode &passfail)
void ParseResults (string &results)
This must be implemented by subclass.
void ParseOverlay (JSONNode &data, JSONNode &passfail)
Protected Member Functions inherited from ImageTest
bool AllocateRGB ()
void AppendLog (CString &log)
void ClearLog ()
void ClearJSON ()
void ClearFailInfo ()
void ClearSummary ()
void DeleteRGB ()
bool GetDataNode (string &results, JSONNode &data, bool logErrors=true)
bool GetPassFailNode (JSONNode &data, JSONNode &passFail, bool logErrors=true)
void PlanesFromRGB ()
converts from m_rawPixels to m_rgb
void GetString (JSONNode &node, const char *name, json_string &string, bool logErrors=true)
void InitResults ()
void ParseFailures (const JSONNode *data)
void RGBFromPlanes (UINT *rgb)
converts from m_rgb to rgb
void SaveImage (RGBQUAD *buf, const char *filename)
void SetJSON (string &src)
void SetSummary (CString &src)
bool AllocateRGB ()
void AppendLog (CString &log)
void ClearLog ()
void ClearJSON ()
void ClearFailInfo ()
void ClearSummary ()
void DeleteRGB ()
bool GetDataNode (string &results, JSONNode &data, bool logErrors=true)
bool GetPassFailNode (JSONNode &data, JSONNode &passFail, bool logErrors=true)
void PlanesFromRGB ()
void GetString (JSONNode &node, const char *name, json_string &string, bool logErrors=true)
void InitResults ()
void ParseFailures (const JSONNode *data)
void RGBFromPlanes (UINT *rgb)
void SaveImage (RGBQUAD *buf, const char *filename)
void SetJSON (string &src)
void SetSummary (CString &src)
Protected Attributes
bool m_qso [eNumQuadrants]
pass/fail for each quadrant
Protected Attributes inherited from ImageTest
const void * m_rawPixels
unsigned char * m_rgb
bool m_passed
const TestID * m_tests
int m_numTests
Timer m_time
ImatestShellFunc m_imatestFunc
CriticalCString m_jsonResults
the full results of the test in JSON format
CriticalCString m_summary
the summary results of the test (these get displayed in the dialog)
CriticalCString m_failInfo
reasons that image failed the test
CriticalCString m_log
log message(s)
Additional Inherited Members
Static Public Member Functions inherited from ImageTest
static UINT __cdecl ThreadProc (void *param)
param must be a pointer to a ThreadControl object; param->m_data must point to an ImageTest object
static UINT __cdecl ThreadProc (void *param)
param must be a pointer to a ThreadControl object; param->m_data must point to an ImageTest object
Public Attributes inherited from ImageTest
int m_width
int m_height
int m_ncolors
const char * m_extension
const char * m_fileroot
const char * m_serialNumber
const char * m_partNumber
const char * m_iniFilePathName
const char * m_programPath
const char * m_name
long long m_elapsed
CString m_elapsedStr
Timestamp m_timestamp
Detailed Description
contains the details of an sfrPlus test to be performed including all relevant fields for determining pass or fail
Constructor & Destructor Documentation
SFRplusTest::SFRplusTest (void)
References gTestID, NUM_TESTS, and TEST_NAME.
 {
    m_name        = TEST_NAME;
    m_tests       = gTestID;
    m_numTests    = NUM_TESTS;
    m_imatestFunc = sfrplus_shell;
 }
SFRplusTest::~SFRplusTest (void) virtual
 {
 }
SFRplusTest::SFRplusTest (void)
virtual SFRplusTest::~SFRplusTest (void) virtual
Member Function Documentation
void SFRplusTest::ClearQSO (void)
References eNumQuadrants.
 {
    for (int i1 = 0; i1 < eNumQuadrants; ++i1)
    {
       m_qso[i1] = false;
    }
 }
const bool* SFRplusTest::GetQSO () inline
References m_qso.
 {return m_qso;}
const bool* SFRplusTest::GetQSO () inline
References m_qso.
Referenced by COperatorConsoleApp::UpdateResultsSFRplus().
 {return m_qso;}
void SFRplusTest::GetResults (JSONNode & passfail) protected
Gets the pass/fail results for a range of pass/fail metrics to be displayed in summary dialog.
 {
    CString     summary;
    json_string center1, outer1, center2, outer2, fov, hConverge, vConverge, rotation;
    char     *format = "MTF#1 Center %s\r\nMTF#1 Outer %s\r\nMTF#2 Center %s\r\nMTF#2 Outer %s\r\nFOV %s\r\nH Tilt %s\r\nV Tilt %s\r\nRotation %s\r\n";
    //
    // Get the data values (they're stored in the pass/fail section)
    // GetString() gets the value and handles any exceptions.
    //
    GetString(passfail, "Secondary_readout_1_center_mean", center1);
    GetString(passfail, "Secondary_readout_1_outer_mean", outer1);
    GetString(passfail, "Secondary_readout_2_center_mean", center2);
    GetString(passfail, "Secondary_readout_2_outer_mean", outer2);
    GetString(passfail, "FOV_degrees_diagonal", fov);
    GetString(passfail, "Horizontal_convergence_angle_degrees", hConverge);
    GetString(passfail, "Vertical_convergence_angle_degrees", vConverge);
    GetString(passfail, "Rotation_degrees", rotation);
    summary.Format(format, center1.c_str(), outer1.c_str(), center2.c_str(), outer2.c_str(), fov.c_str(), hConverge.c_str(), vConverge.c_str(), rotation.c_str());
    m_summary.Set(summary);
 }
void SFRplusTest::GetResults (JSONNode & passfail) protected
void SFRplusTest::ParseOverlay (JSONNode & data, JSONNode & passfail) protected
Determines the pass/fail result for each quadrant.
References JSONNode::as_array(), JSONNode::as_float(), eCenter, eNumQuadrants, and getFloatArray().
 {
    int      i;
    double   readout1[eNumQuadrants];
    double   readout2[eNumQuadrants];
    double   minCenter1, minCenter2;    // minimum allowed values for center quadrant
    double   minOuter1,  minOuter2;     // minimum allowed values for outer (non-center) quadrants
    double   min1, min2;
    memset(m_qso, 0, sizeof(m_qso));
    try
    {
       //
       // The readout data values are stored in the data section of the JSON buffer
       //
       getFloatArray(data.at("secondary_1_quadrant_mean").as_array(), readout1, eNumQuadrants);  // get the readout1 data values
       getFloatArray(data.at("secondary_2_quadrant_mean").as_array(), readout2, eNumQuadrants);  // get the readout2 data values
       //
       // The min allowed values are stored in the pass/fail section of the JSON buffer
       //
       minCenter1 = passfail.at("Secondary_readout_1_center_mean_min").as_array()[0].as_float(); // get the readout1 center min value
       minCenter2 = passfail.at("Secondary_readout_2_center_mean_min").as_array()[0].as_float(); // get the readout2 center min value
       minOuter1  = passfail.at("Secondary_readout_1_outer_mean_min").as_array()[0].as_float();  // get the readout1 outer min value
       minOuter2  = passfail.at("Secondary_readout_2_outer_mean_min").as_array()[0].as_float();  // get the readout2 outer min value
       //
       // See whether or not each quadrant passed the test.
       //
       for (i = 0; i < eNumQuadrants; i++)
       {
          if (i == eCenter)
          {
             min1 = minCenter1;
             min2 = minCenter2;
          }
          else
          {
             min1 = minOuter1;
             min2 = minOuter2;
          }
          m_qso[i] = (readout1[i] >= min1) && (readout2[i] >= min2);
       }
    }
    catch (...)
    {
       CString  log;
       log.AppendFormat("%s Error parsing quadrant results\n", (LPCTSTR)m_timestamp.Get());
       m_log.Append(log);
    }
 }
void SFRplusTest::ParseOverlay (JSONNode & data, JSONNode & passfail) protected
void SFRplusTest::ParseResults (string & results) protected virtual
Parses the JSON output of an sfrPlus test to determine the pass/fail status of the various metrics.
Implements ImageTest.
 {
    CString     summary;
    JSONNode passfail;
     JSONNode   data;
    if (GetDataNode(results, data) && GetPassFailNode(data, passfail))
    {
       try
       {
          m_passed = passfail.at(ALL_TESTS).as_array()[0].as_bool();
          if (!m_passed)
          {
             ParseFailures(&passfail);
          }
       }
       catch(...)
       {
          m_failInfo.Set("Couldn't find pass/fail result");
          m_passed = false;
       }
       GetResults(passfail);         // get the results (they're stored in the pass fail node)
       ParseOverlay(data, passfail);
    }
 }
void SFRplusTest::ParseResults (string & results) protected virtual
This must be implemented by subclass.
Implements ImageTest.
Member Data Documentation
bool SFRplusTest::m_qso protected
pass/fail for each quadrant
Referenced by GetQSO().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/SFRplusTest.h
Documentation/Operator-Console/SFRplusTest.cpp