Operator Console: JSONStream Class Reference
JSONStream Class Reference
#include <JSONStream.h>
Public Member Functions
JSONStream (json_stream_callback_t call_p, json_stream_e_callback_t call_e=NULL, void *callbackIdentifier=JSONSTREAM_SELF) json_nothrow
JSONStream (const JSONStream &orig) json_nothrow
JSONStream & operator= (const JSONStream &orig) json_nothrow
JSONStream & operator<< (const json_string &str) json_nothrow
void reset () json_nothrow
JSON_PRIVATE void * getIdentifier (void) json_nothrow
void parse (void) json_nothrow
bool state BITS (1)
JSONStream (json_stream_callback_t call_p, json_stream_e_callback_t call_e=NULL, void *callbackIdentifier=JSONSTREAM_SELF) json_nothrow
JSONStream (const JSONStream &orig) json_nothrow
JSONStream & operator= (const JSONStream &orig) json_nothrow
JSONStream & operator<< (const json_string &str) json_nothrow
void reset () json_nothrow
JSON_PRIVATE void * getIdentifier (void) json_nothrow
void parse (void) json_nothrow
bool state BITS (1)
Static Public Member Functions
static void deleteJSONStream (JSONStream *stream) json_nothrow
static JSONStream * newJSONStream (json_stream_callback_t callback, json_stream_e_callback_t call_e, void *callbackIdentifier) json_nothrow
template<json_char ch>
static size_t FindNextRelevant (const json_string &value_t, const size_t pos) json_nothrow json_read_priority
static void deleteJSONStream (JSONStream *stream) json_nothrow
static JSONStream * newJSONStream (json_stream_callback_t callback, json_stream_e_callback_t call_e, void *callbackIdentifier) json_nothrow
template<json_char ch>
static size_t FindNextRelevant (const json_string &value_t, const size_t pos) json_nothrow json_read_priority
Public Attributes
json_string buffer
json_stream_callback_t call
json_stream_e_callback_t err_call
void * callback_identifier
Constructor & Destructor Documentation
JSONStream::JSONStream (json_stream_callback_t call_p, json_stream_e_callback_t call_e = NULL, void * callbackIdentifier = JSONSTREAM_SELF)
Referenced by newJSONStream().
 : state(true), call(call_p), err_call(call_e), buffer(), callback_identifier(callbackIdentifier) {}
JSONStream::JSONStream (const JSONStream & orig)
 : state(orig.state), call(orig.call), err_call(orig.err_call), buffer(orig.buffer), callback_identifier(orig.callback_identifier){}
JSONStream::JSONStream (json_stream_callback_t call_p, json_stream_e_callback_t call_e = NULL, void * callbackIdentifier = JSONSTREAM_SELF)
JSONStream::JSONStream (const JSONStream & orig)
Member Function Documentation
bool state JSONStream::BITS (1)
bool state JSONStream::BITS (1)
static void JSONStream::deleteJSONStream (JSONStream * stream) inline static
{
 #ifdef JSON_MEMORY_CALLBACKS
       stream -> ~JSONStream();
       libjson_free<JSONStream>(stream);
 #else
       delete stream;
 #endif
     }
static void JSONStream::deleteJSONStream (JSONStream * stream) inline static
{
 #ifdef JSON_MEMORY_CALLBACKS
       stream -> ~JSONStream();
       libjson_free<JSONStream>(stream);
 #else
       delete stream;
 #endif
     }
template<json_char ch> static size_t JSONStream::FindNextRelevant (const json_string & value_t, const size_t pos) static
template<json_char ch> size_t JSONStream::FindNextRelevant (const json_string & value_t, const size_t pos) static
References BRACKET_STREAM, json_char, json_nothrow, JSON_TEXT, json_unlikely, and QUOTECASE_STREAM.
{
 #else
    #define STREAM_FIND_NEXT_RELEVANT(ch, vt, po) FindNextRelevant(ch, vt, po)
    size_t JSONStream::FindNextRelevant(json_char ch, const json_string & value_t, const size_t pos) json_nothrow {
 #endif
     const json_char * start = value_t.c_str();
     for (const json_char * p = start + pos; *p; ++p){
       if (json_unlikely(*p == ch)) return p - start;
       switch (*p){
           BRACKET_STREAM(JSON_TEXT('['), JSON_TEXT(']'))
           BRACKET_STREAM(JSON_TEXT('{'), JSON_TEXT('}'))
           QUOTECASE_STREAM()
       }
     };
     return json_string::npos;
 }
JSON_PRIVATE void* JSONStream::getIdentifier (void) inline
References callback_identifier, and JSONSTREAM_SELF.
{
       if (callback_identifier == JSONSTREAM_SELF){
          return (void*)this;
       }
       return callback_identifier;
    }
JSON_PRIVATE void* JSONStream::getIdentifier (void) inline
References callback_identifier, and JSONSTREAM_SELF.
Referenced by parse().
{
       if (callback_identifier == JSONSTREAM_SELF){
          return (void*)this;
       }
       return callback_identifier;
    }
static JSONStream* JSONStream::newJSONStream (json_stream_callback_t callback, json_stream_e_callback_t call_e, void * callbackIdentifier) inline static
References JSONStream().
{
 #ifdef JSON_MEMORY_CALLBACKS
       return new(json_malloc<JSONStream>(1)) JSONStream(callback, call_e, callbackIdentifier);
 #else
       return new JSONStream(callback, call_e, callbackIdentifier);
 #endif
     }
static JSONStream* JSONStream::newJSONStream (json_stream_callback_t callback, json_stream_e_callback_t call_e, void * callbackIdentifier) inline static
References JSONStream().
{
 #ifdef JSON_MEMORY_CALLBACKS
       return new(json_malloc<JSONStream>(1)) JSONStream(callback, call_e, callbackIdentifier);
 #else
       return new JSONStream(callback, call_e, callbackIdentifier);
 #endif
     }
JSONStream& JSONStream::operator<< (const json_string & str)
JSONStream & JSONStream::operator<< (const json_string & str)
References libjson::parse().
{
 #endif
       if (state){
          buffer += str;
          parse();
       }
       return *this;
 }
JSONStream & JSONStream::operator= (const JSONStream & orig)
{
    err_call = orig.err_call;
     call = orig.call;
    state = orig.state;
     buffer = orig.buffer;
    callback_identifier = orig.callback_identifier;
     return *this;
 }
JSONStream& JSONStream::operator= (const JSONStream & orig)
void JSONStream::parse (void)
References buffer, call, END_MEM_SCOPE, err_call, getIdentifier(), JSONValidator::isValidPartialRoot(), json_char, JSON_FAIL, json_likely, JSON_SECURITY_MAX_STREAM_OBJECTS, JSON_TEXT, libjson::parse(), json_auto< T >::ptr, JSONWorker::RemoveWhiteSpace, json_auto< T >::set(), START_MEM_SCOPE, and STREAM_FIND_NEXT_RELEVANT.
{
    #ifdef JSON_SECURITY_MAX_STREAM_OBJECTS
       size_t objects = 0;
    #endif
    for(;;){
       size_t pos = buffer.find_first_of(JSON_TEXT("{["));
       if (json_likely(pos != json_string::npos)){
          size_t end = (buffer[pos] == JSON_TEXT('[')) ? STREAM_FIND_NEXT_RELEVANT(JSON_TEXT(']'), buffer, pos + 1) : STREAM_FIND_NEXT_RELEVANT(JSON_TEXT('}'), buffer, pos + 1);
          if (end != json_string::npos){
            #ifdef JSON_SECURITY_MAX_STREAM_OBJECTS
               if (++objects > JSON_SECURITY_MAX_STREAM_OBJECTS){
                  JSON_FAIL(JSON_TEXT("Maximum number of json objects for a stream at once has been reached"));
                 if (err_call) err_call(getIdentifier());
                 state = false;
                  return;
               }
            #endif
            START_MEM_SCOPE
              JSONNode temp(JSONWorker::parse(buffer.substr(pos, end - pos + 1)));
              #ifndef JSON_LIBRARY
                call(temp, getIdentifier());
              #else
                call(&temp, getIdentifier());
              #endif
            END_MEM_SCOPE
            json_string::iterator beginning = buffer.begin();
            buffer.erase(beginning, beginning + end);
            continue; //parse();  //parse the next object too
          }
          #ifdef JSON_SAFE
             else {
                //verify that what's in there is at least valid so far
                #ifndef JSON_VALIDATE
                   #error In order to use safe mode and streams, JSON_VALIDATE needs to be defined
                #endif
                json_auto<json_char> s;
                #if defined JSON_DEBUG || defined JSON_SAFE
                   json_char c;
                   s.set(JSONWorker::RemoveWhiteSpace(json_string(buffer.c_str() + pos), c, false));
                #else
                   s.set(JSONWorker::RemoveWhiteSpace(json_string(buffer.c_str() + pos), false));
                #endif
                if (!JSONValidator::isValidPartialRoot(s.ptr)){
                   if (err_call) err_call(getIdentifier());
                   state = false;
                }
             }
          #endif
       }
       break;
    }
 }
void JSONStream::parse (void)
void JSONStream::reset () inline
References buffer.
{
       state = true;
       buffer.clear();
    }
void JSONStream::reset () inline
References buffer.
{
       state = true;
       buffer.clear();
    }
Member Data Documentation
json_string JSONStream::buffer
Referenced by parse(), and reset().
json_stream_callback_t JSONStream::call
Referenced by parse().
void * JSONStream::callback_identifier
Referenced by getIdentifier().
json_stream_e_callback_t JSONStream::err_call
Referenced by parse().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/JSON/JSONStream.h
JSON/JSONStream.h
Documentation/Operator-Console/JSON/JSONStream.cpp
JSON/JSONStream.cpp