Operator Console: BlemishTest Class Reference
BlemishTest Class Reference
contains the details of an Blemish test to be performed including all relevant fields for determining pass or fail
#include <BlemishTest.h>
Public Member Functions
BlemishTest (void)
virtual ~BlemishTest (void)
BlemishTest (void)
virtual ~BlemishTest (void)
Public Member Functions inherited from ImageTest
ImageTest (void)
virtual ~ImageTest (void)
virtual void Run ()
Runs the test pointed to by m_imatestFunc.
virtual void Run (void *raw_pixels, int width, int height, const Config *config)
void GetLog (CString &dst)
void GetFailInfo (CString &dst)
void GetJSON (CString &dst)
void GetName (CString &name)
void GetSummary (CString &dst)
void Init (void *raw_pixels, int width, int height, const Config *config)
bool Passed ()
void SetBuffer (void *buf)
ImageTest (void)
virtual ~ImageTest (void)
virtual void Run ()
virtual void Run (void *raw_pixels, int width, int height, const Config *config)
void GetLog (CString &dst)
void GetFailInfo (CString &dst)
void GetJSON (CString &dst)
void GetName (CString &name)
void GetSummary (CString &dst)
void Init (void *raw_pixels, int width, int height, const Config *config)
bool Passed ()
void SetBuffer (void *buf)
Protected Member Functions
void ParseResults (string &results)
Parses the JSON output of an sfrPlus test to determine the pass/fail status of the various metrics.
void ParseResults (string &results)
This must be implemented by subclass.
Protected Member Functions inherited from ImageTest
bool AllocateRGB ()
void AppendLog (CString &log)
void ClearLog ()
void ClearJSON ()
void ClearFailInfo ()
void ClearSummary ()
void DeleteRGB ()
bool GetDataNode (string &results, JSONNode &data, bool logErrors=true)
bool GetPassFailNode (JSONNode &data, JSONNode &passFail, bool logErrors=true)
void PlanesFromRGB ()
converts from m_rawPixels to m_rgb
void GetString (JSONNode &node, const char *name, json_string &string, bool logErrors=true)
void InitResults ()
void ParseFailures (const JSONNode *data)
void RGBFromPlanes (UINT *rgb)
converts from m_rgb to rgb
void SaveImage (RGBQUAD *buf, const char *filename)
void SetJSON (string &src)
void SetSummary (CString &src)
bool AllocateRGB ()
void AppendLog (CString &log)
void ClearLog ()
void ClearJSON ()
void ClearFailInfo ()
void ClearSummary ()
void DeleteRGB ()
bool GetDataNode (string &results, JSONNode &data, bool logErrors=true)
bool GetPassFailNode (JSONNode &data, JSONNode &passFail, bool logErrors=true)
void PlanesFromRGB ()
void GetString (JSONNode &node, const char *name, json_string &string, bool logErrors=true)
void InitResults ()
void ParseFailures (const JSONNode *data)
void RGBFromPlanes (UINT *rgb)
void SaveImage (RGBQUAD *buf, const char *filename)
void SetJSON (string &src)
void SetSummary (CString &src)
Additional Inherited Members
Static Public Member Functions inherited from ImageTest
static UINT __cdecl ThreadProc (void *param)
param must be a pointer to a ThreadControl object; param->m_data must point to an ImageTest object
static UINT __cdecl ThreadProc (void *param)
param must be a pointer to a ThreadControl object; param->m_data must point to an ImageTest object
Public Attributes inherited from ImageTest
int m_width
int m_height
int m_ncolors
const char * m_extension
const char * m_fileroot
const char * m_serialNumber
const char * m_partNumber
const char * m_iniFilePathName
const char * m_programPath
const char * m_name
long long m_elapsed
CString m_elapsedStr
Timestamp m_timestamp
Protected Attributes inherited from ImageTest
const void * m_rawPixels
unsigned char * m_rgb
bool m_passed
const TestID * m_tests
int m_numTests
Timer m_time
ImatestShellFunc m_imatestFunc
CriticalCString m_jsonResults
the full results of the test in JSON format
CriticalCString m_summary
the summary results of the test (these get displayed in the dialog)
CriticalCString m_failInfo
reasons that image failed the test
CriticalCString m_log
log message(s)
Detailed Description
contains the details of an Blemish test to be performed including all relevant fields for determining pass or fail
Constructor & Destructor Documentation
BlemishTest::BlemishTest (void)
References blemish_shell(), gTestID, NUM_TESTS, and TEST_NAME.
 {
    m_name        = TEST_NAME;
    m_tests       = gTestID;
    m_numTests    = NUM_TESTS;
    m_imatestFunc = blemish_shell;
 }
BlemishTest::~BlemishTest (void) virtual
 {
 }
BlemishTest::BlemishTest (void)
virtual BlemishTest::~BlemishTest (void) virtual
Member Function Documentation
void BlemishTest::ParseResults (string & results) protected virtual
Parses the JSON output of an sfrPlus test to determine the pass/fail status of the various metrics.
Implements ImageTest.
References JSONNode::as_array(), JSONNode::as_bool(), getIntFromArray(), getStringArray(), PIXEL_ERROR_REGIONS, JSONNode::size(), and sumArrayInt().
 {
    CString     summary;
     JSONNode   pixelErrors;
    JSONNode blemishSize;
    JSONNode passfail;
     JSONNode   data;
    json_string sizes;
    int         total;
    int         dead;
    int         hot;
    int         blemishes;
    const char  *format = "Total pixel errors %d\r\nDead pixels %d\r\nHot pixels %d\r\nBlemishes %d\r\nBlemish size (pixels) %s";
    InitResults();
    if (GetDataNode(results, data))
    {
       //
       // Get the results of interest from the data node
       //
       try
       {
          pixelErrors = data.at("pixelErrors").as_array();
          total       = sumArrayInt(pixelErrors, PIXEL_ERROR_REGIONS);
          dead        = getIntFromArray(data, "nDeadPixels");
          hot         = getIntFromArray(data, "nHotPixels");
          blemishes   = getIntFromArray(data, "N_blemish_count");
          blemishSize = data.at("blemishSizePxls").as_array();
          // Note: blemishSize is limited to 50 entries in the Imatest library and does
          // not necessarily equal the JSON entry "N_blemish_count" = blemishes
          if ( blemishes < (int)blemishSize.size())
          {
             getStringArray(blemishSize, blemishes, &sizes);
          }
          else
          {
             getStringArray(blemishSize, blemishSize.size(), &sizes);
          }
          summary.Format(format, total, dead, hot, blemishes, sizes.c_str());
          m_summary.Set(summary);
       }
       catch(...)
       {
          CString  log;
          log.AppendFormat("%s Error parsing results\n", (LPCTSTR)m_timestamp.Get());
          AppendLog(log);
       }
       //
       // Now get the pass/fail results
       //
       if (GetPassFailNode(data, passfail))   // this will copy any errors into m_log
       {
          try
          {
             m_passed = passfail.at("all_tests_passed").as_array()[0].as_bool();
             if (!m_passed)
             {
                ParseFailures(&passfail);
             }
          }
          catch(...)
          {
             CString str("Unable to find pass/fail result");
             m_failInfo.Set(str);
             m_log.Append(str);
             m_passed = false;
          }
       }
    }
 }
void BlemishTest::ParseResults (string & results) protected virtual
This must be implemented by subclass.
Implements ImageTest.
The documentation for this class was generated from the following files:
BlemishTest.h
Documentation/Operator-Console/BlemishTest.h
BlemishTest.cpp
Documentation/Operator-Console/BlemishTest.cpp