Operator Console: Timestamp Class Reference
Timestamp Class Reference
A class for acquiring the current time.
#include <Timestamp.h>
Public Member Functions
Timestamp (void)
virtual ~Timestamp (void)
const CString & Get ()
Timestamp (void)
virtual ~Timestamp (void)
const CString & Get ()
Protected Attributes
CTime m_time
CString m_str
Detailed Description
A class for acquiring the current time.
Constructor & Destructor Documentation
Timestamp::Timestamp (void)
 {
 }
Timestamp::~Timestamp (void) virtual
 {
 }
Timestamp::Timestamp (void)
virtual Timestamp::~Timestamp (void) virtual
Member Function Documentation
const CString & Timestamp::Get ()
References m_str, and m_time.
Referenced by ImageTest::GetDataNode(), ImageTest::GetPassFailNode(), ImageTest::GetString(), COperatorConsoleDlg::LogMessage(), and ImageTest::Run().
 {
    m_time = CTime::GetCurrentTime();
 #if 0
    m_str = m_time.Format("%c "); // full date and time
 #else
    m_str = m_time.Format("%X "); // just the time, no date
 #endif
    return m_str;
 }
const CString& Timestamp::Get ()
Member Data Documentation
CString Timestamp::m_str protected
Referenced by Get().
CTime Timestamp::m_time protected
Referenced by Get().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/Timestamp.h
Timestamp.h
Documentation/Operator-Console/Timestamp.cpp
Timestamp.cpp