Operator Console: json_shared_string Class Reference
json_shared_string Class Reference
#include <JSONSharedString.h>
Classes
struct json_shared_string_internal
Public Member Functions
json_string::iterator begin (void)
json_string::iterator end (void)
json_string::const_iterator begin (void) const
json_string::const_iterator end (void) const
json_shared_string (void)
json_shared_string (const json_string &str)
json_shared_string (const json_shared_string &str, size_t _offset, size_t _len)
json_shared_string (const json_shared_string &str, size_t _offset)
~json_shared_string (void)
bool empty (void) const
size_t find (json_char ch, size_t pos=0) const
json_char & operator[] (size_t loc)
json_char operator[] (size_t loc) const
void clear ()
size_t length () const
const json_char * c_str () const
const json_char * data () const
bool operator!= (const json_shared_string &other) const
bool operator== (const json_shared_string &other) const
bool operator== (const json_string &other) const
json_string & toString (void) const
void assign (const json_shared_string &other, size_t _offset, size_t _len)
json_shared_string (const json_shared_string &other)
json_shared_string & operator= (const json_shared_string &other)
void deref (void)
size_t offset PACKED (20)
size_t len PACKED (20)
json_string::iterator begin (void)
json_string::iterator end (void)
json_string::const_iterator begin (void) const
json_string::const_iterator end (void) const
json_shared_string (void)
json_shared_string (const json_string &str)
json_shared_string (const json_shared_string &str, size_t _offset, size_t _len)
json_shared_string (const json_shared_string &str, size_t _offset)
~json_shared_string (void)
bool empty (void) const
size_t find (json_char ch, size_t pos=0) const
json_char & operator[] (size_t loc)
json_char operator[] (size_t loc) const
void clear ()
size_t length () const
const json_char * c_str () const
const json_char * data () const
bool operator!= (const json_shared_string &other) const
bool operator== (const json_shared_string &other) const
bool operator== (const json_string &other) const
json_string & toString (void) const
void assign (const json_shared_string &other, size_t _offset, size_t _len)
json_shared_string (const json_shared_string &other)
json_shared_string & operator= (const json_shared_string &other)
void deref (void)
size_t offset PACKED (20)
size_t len PACKED (20)
Public Attributes
json_shared_string_internal * _str
Constructor & Destructor Documentation
json_shared_string::json_shared_string (void) inline
 : offset(0), len(0), _str(new json_shared_string_internal(json_global(EMPTY_JSON_STRING))) {}
json_shared_string::json_shared_string (const json_string & str) inline
 : offset(0), len(str.length()), _str(new json_shared_string_internal(str)) {}
json_shared_string::json_shared_string (const json_shared_string & str, size_t _offset, size_t _len) inline
References _str.
                                                                                           : _str(str._str), offset(str.offset + _offset), len(_len) {
       ++_str -> refCount;
    }
json_shared_string::json_shared_string (const json_shared_string & str, size_t _offset) inline
References _str.
                                                                              : _str(str._str), offset(str.offset + _offset), len(str.len - _offset) {
       ++_str -> refCount;
    }
json_shared_string::~json_shared_string (void) inline
References deref().
{
       deref();
    }
json_shared_string::json_shared_string (const json_shared_string & other) inline
References _str.
                                                         : _str(other._str), offset(other.offset), len(other.len){
       ++_str -> refCount;
    }
json_shared_string::json_shared_string (void) inline
 : offset(0), len(0), _str(new json_shared_string_internal(json_global(EMPTY_JSON_STRING))) {}
json_shared_string::json_shared_string (const json_string & str) inline
 : offset(0), len(str.length()), _str(new json_shared_string_internal(str)) {}
json_shared_string::json_shared_string (const json_shared_string & str, size_t _offset, size_t _len) inline
References _str.
                                                                                           : _str(str._str), offset(str.offset + _offset), len(_len) {
       ++_str -> refCount;
    }
json_shared_string::json_shared_string (const json_shared_string & str, size_t _offset) inline
References _str.
                                                                              : _str(str._str), offset(str.offset + _offset), len(str.len - _offset) {
       ++_str -> refCount;
    }
json_shared_string::~json_shared_string (void) inline
References deref().
{
       deref();
    }
json_shared_string::json_shared_string (const json_shared_string & other) inline
References _str.
                                                         : _str(other._str), offset(other.offset), len(other.len){
       ++_str -> refCount;
    }
Member Function Documentation
void json_shared_string::assign (const json_shared_string & other, size_t _offset, size_t _len) inline
References _str, and deref().
{
       if (other._str != _str){
          deref();
          _str = other._str;
       }
       ++_str -> refCount;
       offset = other.offset + _offset;
       len = _len;
    }
void json_shared_string::assign (const json_shared_string & other, size_t _offset, size_t _len) inline
References _str, and deref().
{
       if (other._str != _str){
          deref();
          _str = other._str;
       }
       ++_str -> refCount;
       offset = other.offset + _offset;
       len = _len;
    }
json_string::iterator json_shared_string::begin (void) inline
References _str.
Referenced by end(), find(), and toString().
{
       return _str -> mystring.begin() + offset;
    }
json_string::iterator json_shared_string::begin (void) inline
References _str.
{
       return _str -> mystring.begin() + offset;
    }
json_string::const_iterator json_shared_string::begin (void) const inline
References _str.
{
       return _str -> mystring.begin() + offset;
    }
json_string::const_iterator json_shared_string::begin (void) const inline
References _str.
{
       return _str -> mystring.begin() + offset;
    }
const json_char* json_shared_string::c_str () const inline
References toString().
 { return toString().c_str(); }
const json_char* json_shared_string::c_str () const inline
References toString().
 { return toString().c_str(); }
void json_shared_string::clear (void) inline
 { len = 0; }
void json_shared_string::clear (void) inline
 { len = 0; }
const json_char* json_shared_string::data () const inline
References _str.
 { return _str -> mystring.c_str() + offset; }
const json_char* json_shared_string::data () const inline
References _str.
 { return _str -> mystring.c_str() + offset; }
void json_shared_string::deref (void) inline
References _str.
Referenced by assign(), operator=(), and ~json_shared_string().
{
       if (--_str -> refCount == 0){
          delete _str;
       }
    }
void json_shared_string::deref (void) inline
References _str.
{
       if (--_str -> refCount == 0){
          delete _str;
       }
    }
bool json_shared_string::empty (void) const inline
 { return len == 0; }
bool json_shared_string::empty (void) const inline
 { return len == 0; }
json_string::iterator json_shared_string::end (void) inline
References begin().
Referenced by find(), and toString().
{
       return begin() + len;
    }
json_string::iterator json_shared_string::end (void) inline
References begin().
{
       return begin() + len;
    }
json_string::const_iterator json_shared_string::end (void) const inline
References begin().
{
       return begin() + len;
    }
json_string::const_iterator json_shared_string::end (void) const inline
References begin().
{
       return begin() + len;
    }
size_t json_shared_string::find (json_char ch, size_t pos = 0) const inline
References _str, begin(), and end().
{
       if (_str -> refCount == 1) return _str -> mystring.find(ch, pos);
       json_string::const_iterator e = end();
       for(json_string::const_iterator b = begin() + pos; b != e; ++b){
          if (*b == ch) return b - begin();
       }
       return json_string::npos;
    }
size_t json_shared_string::find (json_char ch, size_t pos = 0) const inline
References _str, begin(), and end().
{
       if (_str -> refCount == 1) return _str -> mystring.find(ch, pos);
       json_string::const_iterator e = end();
       for(json_string::const_iterator b = begin() + pos; b != e; ++b){
          if (*b == ch) return b - begin();
       }
       return json_string::npos;
    }
size_t json_shared_string::length () const inline
 { return len; }
size_t json_shared_string::length () const inline
 { return len; }
bool json_shared_string::operator!= (const json_shared_string & other) const inline
References _str, and toString().
{
       if ((other._str == _str) && (other.len == len) && (other.offset == offset)) return false;
       return other.toString() != toString();
    }
bool json_shared_string::operator!= (const json_shared_string & other) const inline
References _str, and toString().
{
       if ((other._str == _str) && (other.len == len) && (other.offset == offset)) return false;
       return other.toString() != toString();
    }
json_shared_string& json_shared_string::operator= (const json_shared_string & other) inline
References _str, and deref().
{
       if (other._str != _str){
          deref();
          _str = other._str;
       }
       ++_str -> refCount;
       offset = other.offset;
       len = other.len;
       return *this;
    }
json_shared_string& json_shared_string::operator= (const json_shared_string & other) inline
References _str, and deref().
{
       if (other._str != _str){
          deref();
          _str = other._str;
       }
       ++_str -> refCount;
       offset = other.offset;
       len = other.len;
       return *this;
    }
bool json_shared_string::operator== (const json_shared_string & other) const inline
References _str, and toString().
{
       if ((other._str == _str) && (other.len == len) && (other.offset == offset)) return true;
       return other.toString() == toString();
    }
bool json_shared_string::operator== (const json_shared_string & other) const inline
References _str, and toString().
{
       if ((other._str == _str) && (other.len == len) && (other.offset == offset)) return true;
       return other.toString() == toString();
    }
bool json_shared_string::operator== (const json_string & other) const inline
References toString().
{
       return other == toString();
    }
bool json_shared_string::operator== (const json_string & other) const inline
References toString().
{
       return other == toString();
    }
json_char& json_shared_string::operator[] (size_t loc) inline
References _str.
{
       return _str -> mystring[loc + offset];
    }
json_char& json_shared_string::operator[] (size_t loc) inline
References _str.
{
       return _str -> mystring[loc + offset];
    }
json_char json_shared_string::operator[] (size_t loc) const inline
References _str.
{
       return _str -> mystring[loc + offset];
    }
json_char json_shared_string::operator[] (size_t loc) const inline
References _str.
{
       return _str -> mystring[loc + offset];
    }
size_t offset json_shared_string::PACKED (20) mutable
size_t offset json_shared_string::PACKED (20) mutable
size_t len json_shared_string::PACKED (20) mutable
size_t len json_shared_string::PACKED (20) mutable
json_string& json_shared_string::toString (void) const inline
References _str, begin(), and end().
Referenced by c_str(), operator!=(), and operator==().
{
       //gonna have to do a real substring now anyway, so do it completely
       if (_str -> refCount == 1){
          if (offset || len != _str -> mystring.length()){
             _str -> mystring = json_string(begin(), end());
          }
       } else if (offset || len != _str -> mystring.length()){
          --_str -> refCount;  //dont use deref because I know its not going to be deleted
          _str = new json_shared_string_internal(json_string(begin(), end()));
       }
       offset = 0;
       return _str -> mystring;
    }
json_string& json_shared_string::toString (void) const inline
References _str, begin(), and end().
{
       //gonna have to do a real substring now anyway, so do it completely
       if (_str -> refCount == 1){
          if (offset || len != _str -> mystring.length()){
             _str -> mystring = json_string(begin(), end());
          }
       } else if (offset || len != _str -> mystring.length()){
          --_str -> refCount;  //dont use deref because I know its not going to be deleted
          _str = new json_shared_string_internal(json_string(begin(), end()));
       }
       offset = 0;
       return _str -> mystring;
    }
Member Data Documentation
json_shared_string_internal * json_shared_string::_str mutable
Referenced by assign(), begin(), data(), deref(), find(), json_shared_string(), operator!=(), operator=(), operator==(), operator[](), and toString().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/JSON/JSONSharedString.h
JSON/JSONSharedString.h