Operator Console: imatest_library.h File Reference
imatest_library.h File Reference
#include "mclmcrrt.h"
#include "mclcppclass.h"
Macros
#define LIB_imatest_library_C_API
Functions
LIB_imatest_library_C_API bool
MW_CALL_CONV imatest_libraryInitializeWithHandlers (mclOutputHandlerFcn error_handler, mclOutputHandlerFcn print_handler)
LIB_imatest_library_C_API bool
MW_CALL_CONV imatest_libraryInitialize (void)
LIB_imatest_library_C_API void
MW_CALL_CONV imatest_libraryTerminate (void)
LIB_imatest_library_C_API void
MW_CALL_CONV imatest_libraryPrintStackTrace (void)
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxGraythresh (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxBwconncomp (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxDemosaic (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxRegionprops (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxGetrangefromclass (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxSfrplus_shell (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxBlemish_shell (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxAcquire_image (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxInifile (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxOis_shell (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
Macro Definition Documentation
#define LIB_imatest_library_C_API
Function Documentation
LIB_imatest_library_C_API bool MW_CALL_CONV imatest_libraryInitialize (void)
References imatest_libraryInitializeWithHandlers(), mclDefaultErrorHandler(), and mclDefaultPrintHandler().
Referenced by COperatorConsoleApp::InitLibs().
 {
   return imatest_libraryInitializeWithHandlers(mclDefaultErrorHandler,
                                                mclDefaultPrintHandler);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV imatest_libraryInitializeWithHandlers (mclOutputHandlerFcn error_handler, mclOutputHandlerFcn print_handler)
References _mcr_inst.
Referenced by imatest_libraryInitialize().
 {
     int bResult = 0;
   if (_mcr_inst != NULL)
     return true;
   if (!mclmcrInitialize())
     return false;
   if (!GetModuleFileName(GetModuleHandle("imatest_library"), path_to_dll, _MAX_PATH))
     return false;
     {
         mclCtfStream ctfStream =
             mclGetEmbeddedCtfStream(path_to_dll);
         if (ctfStream) {
             bResult = mclInitializeComponentInstanceEmbedded(   &_mcr_inst,
                                                                 error_handler,
                                                                 print_handler,
                                                                 ctfStream);
             mclDestroyStream(ctfStream);
         } else {
             bResult = 0;
         }
     }
     if (!bResult)
     return false;
   return true;
 }
LIB_imatest_library_C_API void MW_CALL_CONV imatest_libraryPrintStackTrace (void)
 {
   char** stackTrace;
   int stackDepth = mclGetStackTrace(&stackTrace);
   int i;
   for(i=0; i<stackDepth; i++)
   {
     mclWrite(2 /* stderr */, stackTrace[i], sizeof(char)*strlen(stackTrace[i]));
     mclWrite(2 /* stderr */, "\n", sizeof(char)*strlen("\n"));
   }
   mclFreeStackTrace(&stackTrace, stackDepth);
 }
LIB_imatest_library_C_API void MW_CALL_CONV imatest_libraryTerminate (void)
References _mcr_inst.
Referenced by COperatorConsoleApp::CloseLibs().
 {
   if (_mcr_inst != NULL)
     mclTerminateInstance(&_mcr_inst);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxAcquire_image (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "acquire_image", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxBlemish_shell (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "blemish_shell", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxBwconncomp (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "bwconncomp", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxDemosaic (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "demosaic", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxGetrangefromclass (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "getrangefromclass", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxGraythresh (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "graythresh", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxInifile (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "inifile", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxOis_shell (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "ois_shell", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxRegionprops (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "regionprops", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxSfrplus_shell (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "sfrplus_shell", nlhs, plhs, nrhs, prhs);
 }