Operator Console: CriticalCString Class Reference
CriticalCString Class Reference
A null-terminated string class for which all access is controlled by critical sections.
#include <CriticalCString.h>
Public Member Functions
CriticalCString (void)
virtual ~CriticalCString (void)
bool Append (CString &str)
bool Append (const char *str, int len)
void Clear ()
void Get (CString &str, bool clear=false)
copy m_string into str, then optionally clear m_string
void Set (CString &str)
void Set (std::string &str)
void Set (const char *str)
void Set (const char *str, int len)
CriticalCString (void)
virtual ~CriticalCString (void)
bool Append (CString &str)
bool Append (const char *str, int len)
void Clear ()
void Get (CString &str, bool clear=false)
copy m_string into str, then optionally clear m_string
void Set (CString &str)
void Set (std::string &str)
void Set (const char *str)
void Set (const char *str, int len)
Private Attributes
CString m_string
Detailed Description
A null-terminated string class for which all access is controlled by critical sections.
Constructor & Destructor Documentation
CriticalCString::CriticalCString (void)
 {
 }
CriticalCString::~CriticalCString (void) virtual
 {
 }
CriticalCString::CriticalCString (void)
virtual CriticalCString::~CriticalCString (void) virtual
Member Function Documentation
bool CriticalCString::Append (CString & str)
References m_string.
Referenced by ImageTest::GetDataNode(), ImageTest::GetPassFailNode(), ImageTest::GetString(), ImageTest::ParseFailures(), and StdoutThread::ThreadProc().
 {
    bool wasEmpty;
    Lock();
    wasEmpty = m_string.IsEmpty();
    if (!str.IsEmpty())
    {
       m_string.Append(str);         // concatenate str onto the end of m_string
    }
    Unlock();
    return wasEmpty;
 }
bool CriticalCString::Append (CString & str)
bool CriticalCString::Append (const char * str, int len)
References m_string.
 {
    bool wasEmpty;
    Lock();
    wasEmpty = m_string.IsEmpty();
    if (str != NULL)
    {
       m_string.Append(str,len);        // concatenate str onto the end of m_string
    }
    Unlock();
    return wasEmpty;
 }
bool CriticalCString::Append (const char * str, int len)
void CriticalCString::Clear ()
void CriticalCString::Clear ()
References m_string.
Referenced by ImageTest::InitResults().
 {
    Lock();
    m_string.Empty();
    Unlock();
 }
void CriticalCString::Get (CString & str, bool clear = false)
copy m_string into str, then optionally clear m_string
References m_string.
Referenced by StdoutThread::Get().
 {
    Lock();
    dest = m_string;              // copy m_string into dest str
    if (clear)
    {
       m_string.Empty();
    }
    Unlock();
 }
void CriticalCString::Get (CString & str, bool clear = false)
copy m_string into str, then optionally clear m_string
void CriticalCString::Set (CString & str)
void CriticalCString::Set (CString & str)
References m_string.
Referenced by ImageTest::ParseFailures(), and StdoutThread::ThreadProc().
 {
    Lock();
    m_string = src;                  // copy src into m_string
    Unlock();
 }
void CriticalCString::Set (std::string & str)
void CriticalCString::Set (std::string & str)
References m_string.
 {
    Lock();
    m_string.SetString(src.c_str()); // copy src into m_string
    Unlock();
 }
void CriticalCString::Set (const char * str)
void CriticalCString::Set (const char * str)
References m_string.
 {
    if (src != NULL)
    {
       Lock();
       m_string.SetString(src);         // copy src into m_string
       Unlock();
    }
 }
void CriticalCString::Set (const char * str, int len)
References m_string.
 {
    if (str != NULL)
    {
       Lock();
       m_string.SetString(str, len);    // copy len characters of str into m_string
       m_string.AppendChar('\0');
       Unlock();
    }
 }
void CriticalCString::Set (const char * str, int len)
Member Data Documentation
CString CriticalCString::m_string private
Referenced by Append(), Clear(), Get(), and Set().
The documentation for this class was generated from the following files:
CriticalCString.h
Documentation/Operator-Console/CriticalCString.h
CriticalCString.cpp
Documentation/Operator-Console/CriticalCString.cpp