Operator Console: imatest_library.cpp File Reference
imatest_library.cpp File Reference
#include <stdio.h>
#include "imatest_library.h"
Macros
#define EXPORTING_imatest_library 1
Functions
static int mclDefaultPrintHandler (const char *s)
static int mclDefaultErrorHandler (const char *s)
LIB_imatest_library_C_API bool
MW_CALL_CONV imatest_libraryInitializeWithHandlers (mclOutputHandlerFcn error_handler, mclOutputHandlerFcn print_handler)
LIB_imatest_library_C_API bool
MW_CALL_CONV imatest_libraryInitialize (void)
LIB_imatest_library_C_API void
MW_CALL_CONV imatest_libraryTerminate (void)
LIB_imatest_library_C_API void
MW_CALL_CONV imatest_libraryPrintStackTrace (void)
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxGraythresh (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxBwconncomp (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxDemosaic (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxRegionprops (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxGetrangefromclass (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxSfrplus_shell (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxBlemish_shell (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxAcquire_image (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxInifile (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_C_API bool
MW_CALL_CONV mlxOis_shell (int nlhs, mxArray *plhs[], int nrhs, mxArray *prhs[])
LIB_imatest_library_CPP_API
void MW_CALL_CONV graythresh (int nargout, mwArray &level, mwArray &em, const mwArray &I)
LIB_imatest_library_CPP_API
void MW_CALL_CONV bwconncomp (int nargout, mwArray &CC, const mwArray &varargin)
LIB_imatest_library_CPP_API
void MW_CALL_CONV bwconncomp (int nargout, mwArray &CC)
LIB_imatest_library_CPP_API
void MW_CALL_CONV demosaic (int nargout, mwArray &RGB, const mwArray &I, const mwArray &sensorAlignment)
LIB_imatest_library_CPP_API
void MW_CALL_CONV regionprops (int nargout, mwArray &outstats, const mwArray &varargin)
LIB_imatest_library_CPP_API
void MW_CALL_CONV regionprops (int nargout, mwArray &outstats)
LIB_imatest_library_CPP_API
void MW_CALL_CONV getrangefromclass (int nargout, mwArray &range, const mwArray &I)
LIB_imatest_library_CPP_API
void MW_CALL_CONV sfrplus_shell (int nargout, mwArray &nret, const mwArray &inputFile, const mwArray &rootDir, const mwArray &inputKeys, const mwArray &opMode, const mwArray &varargin)
LIB_imatest_library_CPP_API
void MW_CALL_CONV blemish_shell (int nargout, mwArray &nret, const mwArray &inputFile, const mwArray &rootDir, const mwArray &inputKeys, const mwArray &opMode, const mwArray &varargin)
LIB_imatest_library_CPP_API
void MW_CALL_CONV acquire_image (int nargout, mwArray &im_orig, mwArray &vstr, const mwArray &source_id, const mwArray &varargin)
LIB_imatest_library_CPP_API
void MW_CALL_CONV inifile (int nargout, mwArray &varargout, const mwArray &varargin)
LIB_imatest_library_CPP_API
void MW_CALL_CONV inifile (int nargout, mwArray &varargout)
LIB_imatest_library_CPP_API
void MW_CALL_CONV inifile (const mwArray &varargin)
LIB_imatest_library_CPP_API
void MW_CALL_CONV inifile ()
LIB_imatest_library_CPP_API
void MW_CALL_CONV ois_shell (int nargout, mwArray &results, const mwArray &ncontrol, const mwArray &arg1, const mwArray &arg2, const mwArray &arg3, const mwArray &passFailFile)
Variables
static HMCRINSTANCE _mcr_inst = NULL
Macro Definition Documentation
#define EXPORTING_imatest_library 1
Function Documentation
LIB_imatest_library_CPP_API void MW_CALL_CONV acquire_image (int nargout, mwArray & im_orig, mwArray & vstr, const mwArray & source_id, const mwArray & varargin)
References _mcr_inst.
Referenced by ImatestLibAcq::CaptureFrame().
 {
   mclcppMlfFeval(_mcr_inst, "acquire_image", nargout, 2, -2, &im_orig, &vstr, &source_id, &varargin);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV blemish_shell (int nargout, mwArray & nret, const mwArray & inputFile, const mwArray & rootDir, const mwArray & inputKeys, const mwArray & opMode, const mwArray & varargin)
References _mcr_inst.
Referenced by BlemishTest::BlemishTest().
 {
   mclcppMlfFeval(_mcr_inst, "blemish_shell", nargout, 1, -5, &nret, &inputFile, &rootDir, &inputKeys, &opMode, &varargin);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV bwconncomp (int nargout, mwArray & CC, const mwArray & varargin)
References _mcr_inst.
 {
   mclcppMlfFeval(_mcr_inst, "bwconncomp", nargout, 1, -1, &CC, &varargin);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV bwconncomp (int nargout, mwArray & CC)
References _mcr_inst.
 {
   mclcppMlfFeval(_mcr_inst, "bwconncomp", nargout, 1, 0, &CC);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV demosaic (int nargout, mwArray & RGB, const mwArray & I, const mwArray & sensorAlignment)
References _mcr_inst.
 {
   mclcppMlfFeval(_mcr_inst, "demosaic", nargout, 1, 2, &RGB, &I, &sensorAlignment);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV getrangefromclass (int nargout, mwArray & range, const mwArray & I)
References _mcr_inst.
 {
   mclcppMlfFeval(_mcr_inst, "getrangefromclass", nargout, 1, 1, &range, &I);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV graythresh (int nargout, mwArray & level, mwArray & em, const mwArray & I)
References _mcr_inst.
 {
   mclcppMlfFeval(_mcr_inst, "graythresh", nargout, 2, 1, &level, &em, &I);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV imatest_libraryInitialize (void)
References imatest_libraryInitializeWithHandlers(), mclDefaultErrorHandler(), and mclDefaultPrintHandler().
Referenced by COperatorConsoleApp::InitLibs().
 {
   return imatest_libraryInitializeWithHandlers(mclDefaultErrorHandler,
                                                mclDefaultPrintHandler);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV imatest_libraryInitializeWithHandlers (mclOutputHandlerFcn error_handler, mclOutputHandlerFcn print_handler)
References _mcr_inst.
Referenced by imatest_libraryInitialize().
 {
     int bResult = 0;
   if (_mcr_inst != NULL)
     return true;
   if (!mclmcrInitialize())
     return false;
   if (!GetModuleFileName(GetModuleHandle("imatest_library"), path_to_dll, _MAX_PATH))
     return false;
     {
         mclCtfStream ctfStream =
             mclGetEmbeddedCtfStream(path_to_dll);
         if (ctfStream) {
             bResult = mclInitializeComponentInstanceEmbedded(   &_mcr_inst,
                                                                 error_handler,
                                                                 print_handler,
                                                                 ctfStream);
             mclDestroyStream(ctfStream);
         } else {
             bResult = 0;
         }
     }
     if (!bResult)
     return false;
   return true;
 }
LIB_imatest_library_C_API void MW_CALL_CONV imatest_libraryPrintStackTrace (void)
 {
   char** stackTrace;
   int stackDepth = mclGetStackTrace(&stackTrace);
   int i;
   for(i=0; i<stackDepth; i++)
   {
     mclWrite(2 /* stderr */, stackTrace[i], sizeof(char)*strlen(stackTrace[i]));
     mclWrite(2 /* stderr */, "\n", sizeof(char)*strlen("\n"));
   }
   mclFreeStackTrace(&stackTrace, stackDepth);
 }
LIB_imatest_library_C_API void MW_CALL_CONV imatest_libraryTerminate (void)
References _mcr_inst.
Referenced by COperatorConsoleApp::CloseLibs().
 {
   if (_mcr_inst != NULL)
     mclTerminateInstance(&_mcr_inst);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV inifile (int nargout, mwArray & varargout, const mwArray & varargin)
References _mcr_inst.
Referenced by COperatorConsoleApp::ReadINISettings(), COperatorConsoleApp::ReadPassFail(), COperatorConsoleApp::WriteINISettings(), and COperatorConsoleApp::WritePassFail().
 {
   mclcppMlfFeval(_mcr_inst, "inifile", nargout, -1, -1, &varargout, &varargin);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV inifile (int nargout, mwArray & varargout)
References _mcr_inst.
 {
   mclcppMlfFeval(_mcr_inst, "inifile", nargout, -1, 0, &varargout);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV inifile (const mwArray & varargin)
References _mcr_inst.
 {
   mclcppMlfFeval(_mcr_inst, "inifile", 0, 0, -1, &varargin);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV inifile ()
References _mcr_inst.
 {
   mclcppMlfFeval(_mcr_inst, "inifile", 0, 0, 0);
 }
static int mclDefaultErrorHandler (const char * s) static
Referenced by imatest_libraryInitialize().
 {
   int written = 0;
   size_t len = 0;
   len = strlen(s);
   written = mclWrite(2 /* stderr */, s, sizeof(char)*len);
   if (len > 0 && s[ len-1 ] != '\n')
     written += mclWrite(2 /* stderr */, "\n", sizeof(char));
   return written;
 }
static int mclDefaultPrintHandler (const char * s) static
Referenced by imatest_libraryInitialize().
 {
   return mclWrite(1 /* stdout */, s, sizeof(char)*strlen(s));
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxAcquire_image (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "acquire_image", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxBlemish_shell (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "blemish_shell", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxBwconncomp (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "bwconncomp", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxDemosaic (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "demosaic", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxGetrangefromclass (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "getrangefromclass", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxGraythresh (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "graythresh", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxInifile (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "inifile", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxOis_shell (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "ois_shell", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxRegionprops (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "regionprops", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_C_API bool MW_CALL_CONV mlxSfrplus_shell (int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[])
References _mcr_inst.
 {
   return mclFeval(_mcr_inst, "sfrplus_shell", nlhs, plhs, nrhs, prhs);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV ois_shell (int nargout, mwArray & results, const mwArray & ncontrol, const mwArray & arg1, const mwArray & arg2, const mwArray & arg3, const mwArray & passFailFile)
References _mcr_inst.
 {
   mclcppMlfFeval(_mcr_inst, "ois_shell", nargout, 1, 5, &results, &ncontrol, &arg1, &arg2, &arg3, &passFailFile);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV regionprops (int nargout, mwArray & outstats, const mwArray & varargin)
References _mcr_inst.
 {
   mclcppMlfFeval(_mcr_inst, "regionprops", nargout, 1, -1, &outstats, &varargin);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV regionprops (int nargout, mwArray & outstats)
References _mcr_inst.
 {
   mclcppMlfFeval(_mcr_inst, "regionprops", nargout, 1, 0, &outstats);
 }
LIB_imatest_library_CPP_API void MW_CALL_CONV sfrplus_shell (int nargout, mwArray & nret, const mwArray & inputFile, const mwArray & rootDir, const mwArray & inputKeys, const mwArray & opMode, const mwArray & varargin)
References _mcr_inst.
Referenced by SFRplusTest::SFRplusTest().
 {
   mclcppMlfFeval(_mcr_inst, "sfrplus_shell", nargout, 1, -5, &nret, &inputFile, &rootDir, &inputKeys, &opMode, &varargin);
 }
Variable Documentation
HMCRINSTANCE _mcr_inst = NULL static
Referenced by acquire_image(), blemish_shell(), bwconncomp(), demosaic(), getrangefromclass(), graythresh(), imatest_libraryInitializeWithHandlers(), imatest_libraryTerminate(), inifile(), mlxAcquire_image(), mlxBlemish_shell(), mlxBwconncomp(), mlxDemosaic(), mlxGetrangefromclass(), mlxGraythresh(), mlxInifile(), mlxOis_shell(), mlxRegionprops(), mlxSfrplus_shell(), ois_shell(), regionprops(), and sfrplus_shell().