Operator Console: StdoutRedirect Class Reference
StdoutRedirect Class Reference
Defines functions for redirecting stdout through a buffered pipe.
#include <StdoutRedirect.h>
Public Member Functions
StdoutRedirect ()
virtual ~StdoutRedirect ()
void Close ()
int Init (int bufferSize)
int Start ()
int Stop ()
int GetBuffer (char *buffer, int size)
StdoutRedirect ()
virtual ~StdoutRedirect ()
void Close ()
int Init (int bufferSize)
int Start ()
int Stop ()
int GetBuffer (char *buffer, int size)
Protected Attributes
FILE * file
stdout (subclasses can set this to something else, e.g. stderr)
Private Attributes
int fdStdOutPipe [2]
int fdStdOut
bool isOpen
Detailed Description
Defines functions for redirecting stdout through a buffered pipe.
Constructor & Destructor Documentation
StdoutRedirect::StdoutRedirect ()
 {
    isOpen = false;
    file = stdout;
 }
StdoutRedirect::~StdoutRedirect () virtual
References READ_FD, and WRITE_FD.
 {
 #if 0
    _close(fdStdOut);
     _close(fdStdOutPipe[WRITE_FD]);
     _close(fdStdOutPipe[READ_FD]);
 #else
    Close();
 #endif
 }
StdoutRedirect::StdoutRedirect ()
virtual StdoutRedirect::~StdoutRedirect () virtual
Member Function Documentation
void StdoutRedirect::Close ()
References READ_FD, and WRITE_FD.
Referenced by StdoutThread::Quit().
 {
    if (isOpen)
    {
       _close(fdStdOut);
       _close(fdStdOutPipe[WRITE_FD]);
       _close(fdStdOutPipe[READ_FD]);
       isOpen = false;
    }
 }
void StdoutRedirect::Close ()
int StdoutRedirect::GetBuffer (char * buffer, int size)
References READ_FD.
Referenced by StdoutThread::ThreadProc().
 {
    int nOutRead = _read(fdStdOutPipe[READ_FD], buffer, size);  // this will block until there is data to read (could cause thread to hang)
     buffer[nOutRead] = '\0';
     return nOutRead;
 }
int StdoutRedirect::GetBuffer (char * buffer, int size)
int StdoutRedirect::Init (int bufferSize)
int StdoutRedirect::Init (int bufferSize)
Referenced by StdoutThread::InitThread().
 {
    int error = _pipe(fdStdOutPipe, bufferSize, O_TEXT);
    if (!error)
     {
       fdStdOut = _dup(_fileno(file));
       isOpen   = true;
    }
    return error;
 }
int StdoutRedirect::Start ()
int StdoutRedirect::Start ()
References CHECK, and WRITE_FD.
Referenced by StdoutThread::InitThread().
 {
 #if 0
    fflush( file );
 #endif
    CHECK(_dup2(fdStdOutPipe[WRITE_FD], _fileno(file)));
     ios::sync_with_stdio();
     setvbuf( file, NULL, _IONBF, 0 ); // absolutely needed
     return 0;
 }
int StdoutRedirect::Stop ()
References CHECK.
Referenced by StdoutThread::Quit().
 {
     CHECK(_dup2(fdStdOut, _fileno(file)));
     ios::sync_with_stdio();
     return 0;
 }
int StdoutRedirect::Stop ()
Member Data Documentation
int StdoutRedirect::fdStdOut private
int StdoutRedirect::fdStdOutPipe private
FILE * StdoutRedirect::file protected
stdout (subclasses can set this to something else, e.g. stderr)
Referenced by StderrRedirect::StderrRedirect(), and StderrThread::StderrThread().
bool StdoutRedirect::isOpen private
The documentation for this class was generated from the following files:
Documentation/Operator-Console/StdoutRedirect.h
StdoutRedirect.h
Documentation/Operator-Console/StdoutRedirect.cpp
StdoutRedirect.cpp