Operator Console: ImageAcquisition Class Reference
ImageAcquisition Class Reference abstract
the base class for image acquisition
#include <ImageAcquisition.h>
Public Member Functions
ImageAcquisition (void)
virtual ~ImageAcquisition (void)
virtual bool CaptureFrame ()=0
capture a single image into m_buf
virtual bool Close ()=0
virtual bool Open ()=0
void GetFrame (void *buf)
virtual bool Init (int width, int height, int bytesPerPixel=4)
may be overridden, but be sure to call parent function also
unsigned int BytesPerFrame ()
unsigned int PixelsPerFrame ()
int GetHeight ()
CString & GetInfo ()
int GetWidth ()
void SetHeight (int height)
void SetWidth (int width)
ImageAcquisition (void)
virtual ~ImageAcquisition (void)
virtual bool CaptureFrame ()=0
capture a single image into m_buf
virtual bool Close ()=0
virtual bool Open ()=0
void GetFrame (void *buf)
virtual bool Init (int width, int height, int bytesPerPixel=4)
may be overridden, but be sure to call parent function also
unsigned int BytesPerFrame ()
unsigned int PixelsPerFrame ()
int GetHeight ()
CString & GetInfo ()
int GetWidth ()
void SetHeight (int height)
void SetWidth (int width)
Static Public Member Functions
static UINT __cdecl ThreadProc (LPVOID param)
static UINT __cdecl ThreadProc (LPVOID param)
Protected Attributes
CriticalBuf m_frame
shared memory to hold copy of current frame
int m_width
width of image in pixels
int m_height
height of image in pixels
unsigned int m_numBytes
number of bytes in a frame
unsigned int m_numPixels
number of pixels in a frame
CString m_logMsg
error or information message
void * m_buf
buffer to capture into
Detailed Description
the base class for image acquisition
Constructor & Destructor Documentation
ImageAcquisition::ImageAcquisition (void)
References m_buf, m_height, m_numBytes, m_numPixels, and m_width.
 {
    m_width     = 0;
    m_height    = 0;
    m_numBytes  = 0;
    m_numPixels = 0;
    m_buf       = NULL;
 }
ImageAcquisition::~ImageAcquisition (void) virtual
References m_buf.
 {
    if (m_buf != NULL)
    {
       delete [] m_buf;
    }
 }
ImageAcquisition::ImageAcquisition (void)
virtual ImageAcquisition::~ImageAcquisition (void) virtual
Member Function Documentation
unsigned int ImageAcquisition::BytesPerFrame () inline
References m_numBytes.
Referenced by COperatorConsoleApp::AllocateImageBuf().
 {return m_numBytes;}
unsigned int ImageAcquisition::BytesPerFrame () inline
References m_numBytes.
 {return m_numBytes;}
virtual bool ImageAcquisition::CaptureFrame () pure virtual
capture a single image into m_buf
Implemented in FileAcq, FileAcq, ImatestLibAcq, SimpleDirectShowAcq, ImatestLibAcq, SimpleDirectShowAcq, FileAcquisition, FileAcquisition, ImatestLibAcq, and ImatestLibAcq.
Referenced by ThreadProc().
virtual bool ImageAcquisition::CaptureFrame () pure virtual
capture a single image into m_buf
Implemented in FileAcq, FileAcq, ImatestLibAcq, SimpleDirectShowAcq, ImatestLibAcq, SimpleDirectShowAcq, FileAcquisition, FileAcquisition, ImatestLibAcq, and ImatestLibAcq.
virtual bool ImageAcquisition::Close () pure virtual
Implemented in FileAcq, FileAcq, ImatestLibAcq, SimpleDirectShowAcq, ImatestLibAcq, SimpleDirectShowAcq, FileAcquisition, FileAcquisition, ImatestLibAcq, and ImatestLibAcq.
virtual bool ImageAcquisition::Close () pure virtual
Implemented in FileAcq, FileAcq, ImatestLibAcq, SimpleDirectShowAcq, ImatestLibAcq, SimpleDirectShowAcq, FileAcquisition, FileAcquisition, ImatestLibAcq, and ImatestLibAcq.
void ImageAcquisition::GetFrame (void * buf) inline
References CriticalBuf::Get(), and m_frame.
 {m_frame.Get(buf);}
void ImageAcquisition::GetFrame (void * buf) inline
References CriticalBuf::Get(), and m_frame.
Referenced by COperatorConsoleApp::OnFrameReady(), and COperatorConsoleApp::OnRunTest().
 {m_frame.Get(buf);}
int ImageAcquisition::GetHeight () inline
References m_height.
Referenced by COperatorConsoleApp::InitBlemishThread(), and COperatorConsoleApp::InitSFRplusThread().
 {return m_height;}
int ImageAcquisition::GetHeight () inline
References m_height.
 {return m_height;}
CString& ImageAcquisition::GetInfo () inline
References m_logMsg.
Referenced by COperatorConsoleApp::Init(), and COperatorConsoleApp::ReInit().
 {return m_logMsg;}
CString& ImageAcquisition::GetInfo () inline
References m_logMsg.
 {return m_logMsg;}
int ImageAcquisition::GetWidth () inline
References m_width.
 {return m_width;}
int ImageAcquisition::GetWidth () inline
References m_width.
Referenced by COperatorConsoleApp::InitBlemishThread(), and COperatorConsoleApp::InitSFRplusThread().
 {return m_width;}
bool ImageAcquisition::Init (int width, int height, int bytesPerPixel = 4) virtual
may be overridden, but be sure to call parent function also
References height, CriticalBuf::Init(), m_buf, m_frame, m_height, m_logMsg, m_numBytes, m_numPixels, m_width, and width.
Referenced by FileAcquisition::Init(), COperatorConsoleApp::InitCamera(), and FileAcq::Open().
 {
    bool  success = false;
    m_width     = width;
    m_height    = height;
    m_numPixels = m_width * m_height;
    m_numBytes  = m_numPixels * bytesPerPixel;
    if ( m_buf != NULL) // allow for resizing of buffer by re-initialization
    {
       delete[] m_buf;
    }
    m_buf       = new byte[m_numBytes];
    if (m_buf == NULL)
    {
       m_logMsg.Format("%s: Unable to allocate image buffer (%u bytes)", __FUNCTION__, m_numPixels);
    }
    else
    {
       success = m_frame.Init(m_numBytes);
    }
    return success;
 }
virtual bool ImageAcquisition::Init (int width, int height, int bytesPerPixel = 4) virtual
may be overridden, but be sure to call parent function also
virtual bool ImageAcquisition::Open () pure virtual
Implemented in FileAcq, FileAcq, ImatestLibAcq, SimpleDirectShowAcq, ImatestLibAcq, SimpleDirectShowAcq, FileAcquisition, FileAcquisition, ImatestLibAcq, and ImatestLibAcq.
virtual bool ImageAcquisition::Open () pure virtual
Implemented in FileAcq, FileAcq, ImatestLibAcq, SimpleDirectShowAcq, ImatestLibAcq, SimpleDirectShowAcq, FileAcquisition, FileAcquisition, ImatestLibAcq, and ImatestLibAcq.
unsigned int ImageAcquisition::PixelsPerFrame () inline
References m_numPixels.
 {return m_numPixels;}
unsigned int ImageAcquisition::PixelsPerFrame () inline
References m_numPixels.
 {return m_numPixels;}
void ImageAcquisition::SetHeight (int height) inline
References height, and m_height.
 {m_height = height;}
void ImageAcquisition::SetHeight (int height) inline
References height, and m_height.
 {m_height = height;}
void ImageAcquisition::SetWidth (int width) inline
References m_width, and width.
 {m_width = width;}
void ImageAcquisition::SetWidth (int width) inline
References m_width, and width.
 {m_width = width;}
UINT __cdecl ImageAcquisition::ThreadProc (LPVOID param) static
References CaptureFrame(), DONE_INDEX, m_buf, ThreadControl::m_data, ThreadControl::m_events, m_frame, ThreadControl::m_parentID, ThreadControl::m_threadMsg, NUM_THREAD_EVENTS, RUN_INDEX, and CriticalBuf::Set().
Referenced by COperatorConsoleApp::InitCameraThread().
 {
    ThreadControl     *info = (ThreadControl *)param;
    ImageAcquisition  *acq = (ImageAcquisition *)info->m_data;
    bool           done  = false;
    DWORD          eventIndex;
    while (!done)
    {
       eventIndex = ::WaitForMultipleObjects(NUM_THREAD_EVENTS, info->m_events, FALSE, INFINITE);
       if (eventIndex == DONE_INDEX)
       {
          done = TRUE;
       }
       else if (eventIndex == RUN_INDEX)
       {
          acq->CaptureFrame();
          acq->m_frame.Set(acq->m_buf);
 //       acq->m_mwarray.Set(acq->m_mwarray);
          ::PostThreadMessage(info->m_parentID, info->m_threadMsg, (WPARAM)0, (LPARAM)0);
       }
    }
    return 0;   // this terminates the thread
 }
static UINT __cdecl ImageAcquisition::ThreadProc (LPVOID param) static
Member Data Documentation
void * ImageAcquisition::m_buf protected
buffer to capture into
Referenced by ImageAcquisition(), Init(), SimpleDirectShowAcq::Open(), FileAcq::Open(), SimpleDirectShowAcq::SimpleDirectShowAcq(), ThreadProc(), and ~ImageAcquisition().
CriticalBuf ImageAcquisition::m_frame protected
shared memory to hold copy of current frame
Referenced by GetFrame(), Init(), and ThreadProc().
int ImageAcquisition::m_height protected
height of image in pixels
Referenced by GetHeight(), ImageAcquisition(), Init(), SimpleDirectShowAcq::Open(), FileAcq::Open(), SetHeight(), and SimpleDirectShowAcq::SimpleDirectShowAcq().
CString ImageAcquisition::m_logMsg protected
error or information message
Referenced by GetInfo(), Init(), and SimpleDirectShowAcq::Open().
unsigned int ImageAcquisition::m_numBytes protected
number of bytes in a frame
Referenced by BytesPerFrame(), ImageAcquisition(), Init(), and SimpleDirectShowAcq::SimpleDirectShowAcq().
unsigned int ImageAcquisition::m_numPixels protected
number of pixels in a frame
Referenced by ImageAcquisition(), Init(), PixelsPerFrame(), and SimpleDirectShowAcq::SimpleDirectShowAcq().
int ImageAcquisition::m_width protected
width of image in pixels
Referenced by GetWidth(), ImageAcquisition(), Init(), SimpleDirectShowAcq::Open(), FileAcq::Open(), SetWidth(), and SimpleDirectShowAcq::SimpleDirectShowAcq().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/ImageAcquisition.h
ImageAcquisition.h
Documentation/Operator-Console/ImageAcquisition.cpp
ImageAcquisition.cpp