Operator Console: COperatorConsoleDlg Class Reference
COperatorConsoleDlg Class Reference
The class underlying the main dialog.
#include <OperatorConsoleDlg.h>
Public Types
enum { IDD = IDD_OPERATORCONSOLE_DIALOG }
enum { IDD = IDD_OPERATORCONSOLE_DIALOG }
Public Member Functions
COperatorConsoleDlg (CWnd *pParent=NULL)
afx_msg void OnBnClickedRadioBlemish ()
afx_msg void OnBnClickedRadioSfr ()
afx_msg void OnBnClickedShowjson ()
afx_msg void OnBnClickedStart ()
afx_msg void OnBnClickedStop ()
afx_msg void OnDrawItem (int nIDCtl, LPDRAWITEMSTRUCT lpDrawItemStruct)
afx_msg void OnClose ()
afx_msg BOOL OnEraseBkgnd (CDC *pDC)
afx_msg void OnBnClickedSetupButton ()
void DrawImage (LPDRAWITEMSTRUCT info)
void DrawLogo (LPDRAWITEMSTRUCT info)
void GetLog (CString &dst)
void LogMessage (LPCTSTR msg, bool timestamp=true)
void ReInitDialog (void)
Allows the display to be resized after the user changes the image size.
void UpdateFPS (long long ms)
void UpdateImage (void *buf)
void UpdateStatus (bool passed, LPCTSTR reason)
void UpdateSummary (LPCTSTR summary)
void UpdateQuadrants (const bool *data)
afx_msg void OnClickedPassFail ()
COperatorConsoleDlg (CWnd *pParent=NULL)
afx_msg void OnBnClickedRadioBlemish ()
afx_msg void OnBnClickedRadioSfr ()
afx_msg void OnBnClickedShowjson ()
afx_msg void OnBnClickedStart ()
afx_msg void OnBnClickedStop ()
afx_msg void OnDrawItem (int nIDCtl, LPDRAWITEMSTRUCT lpDrawItemStruct)
afx_msg void OnClose ()
afx_msg BOOL OnEraseBkgnd (CDC *pDC)
afx_msg void OnBnClickedSetupButton ()
void DrawImage (LPDRAWITEMSTRUCT info)
void DrawLogo (LPDRAWITEMSTRUCT info)
void GetLog (CString &dst)
void LogMessage (LPCTSTR msg, bool timestamp=true)
void ReInitDialog (void)
Allows the display to be resized after the user changes the image size.
void UpdateFPS (long long ms)
void UpdateImage (void *buf)
void UpdateStatus (bool passed, LPCTSTR reason)
void UpdateSummary (LPCTSTR summary)
void UpdateQuadrants (const bool *data)
afx_msg void OnClickedPassFail ()
Public Attributes
CButton c_startButton
CButton c_stopButton
CEdit c_summary
The summary display.
CStatic c_status
The status display.
CEdit c_reason
The reason display.
CEdit c_log
The log display.
CButton c_sfrPlus
The sfrPlus radial button.
CButton c_blemish
The Blemish radial button.
CStaticBmp c_image
owner-drawn control that displays an image from the acquisition source
CStatic c_logo
CStatic c_qsoUL
The static text for the upper left QSO.
CStatic c_qsoUR
The static text for the upper right QSO.
CStatic c_qsoLL
The static text for the lower left QSO.
CStatic c_qsoLR
The static text for the lower right QSO.
CStatic c_qsoCENTER
The static text for the center QSO.
CStatic c_fps
The frames-per-second display.
CButton c_showjson
The 'show JSON' button.
CButton c_setup
The setup button.
CButton c_pass_fail
Protected Member Functions
virtual void DoDataExchange (CDataExchange *pDX)
void ShowStartStop (bool start, bool stop)
BOOL OnInitDialog ()
void OnOK ()
void OnCancel ()
void Quit ()
afx_msg HBRUSH OnCtlColor (CDC *pDC, CWnd *pWnd, UINT nCtlColor)
afx_msg void OnSysCommand (UINT nID, LPARAM lParam)
afx_msg void OnPaint ()
afx_msg HCURSOR OnQueryDragIcon ()
void CenterWindow (CWnd *wnd, int centerX, int centerY)
move 'wnd' so its center is at the screen coordinate (centerX, centerY)
void CreateFont (CWnd *wnd, int points, CFont *newFont)
void MoveFPS ()
void PostParentMessage (UINT message, WPARAM wParam=0, LPARAM lParam=0)
void QsoMove ()
HBRUSH QsoSet (CDC *cdc, EQuadrant quadrant)
void QsoShow (bool show)
HBRUSH SetBGColor (CDC *dc, CBrush brush, COLORREF color)
void UpdateQuadrant (const bool *passed, EQuadrant quadrant, CWnd *control)
virtual void DoDataExchange (CDataExchange *pDX)
void ShowStartStop (bool start, bool stop)
BOOL OnInitDialog ()
void OnOK ()
void OnCancel ()
void Quit ()
afx_msg HBRUSH OnCtlColor (CDC *pDC, CWnd *pWnd, UINT nCtlColor)
afx_msg void OnSysCommand (UINT nID, LPARAM lParam)
afx_msg void OnPaint ()
afx_msg HCURSOR OnQueryDragIcon ()
void CenterWindow (CWnd *wnd, int centerX, int centerY)
move 'wnd' so its center is at the screen coordinate (centerX, centerY)
void CreateFont (CWnd *wnd, int points, CFont *newFont)
void MoveFPS ()
void PostParentMessage (UINT message, WPARAM wParam=0, LPARAM lParam=0)
void QsoMove ()
HBRUSH QsoSet (CDC *cdc, EQuadrant quadrant)
void QsoShow (bool show)
HBRUSH SetBGColor (CDC *dc, CBrush brush, COLORREF color)
void UpdateQuadrant (const bool *passed, EQuadrant quadrant, CWnd *control)
Protected Attributes
HICON m_hIcon
CBrush m_whiteBrush
CBrush m_passBrush
the brush (i.e. background color) to be used for Status item when the test has passed
CBrush m_failBrush
the brush (i.e. background color) to be used for Status item when the test has failed
HBRUSH m_statusBrush
handle to the brush to be used when drawing the Status item
COLORREF m_statusColor
unused if m_statusBrush == NULL
COLORREF m_qsoColor [eNumQuadrants]
color to use for each QSO item
CFont m_statusFont
font to use for Status item (used to change font size for the item)
CFont m_qsoFont
font to use for QSO (Quadrant Status Overlay) items
CImage m_logo
Imatest logo (goes at top of info display)
CSize m_delta
number of pixels to increase image item and dialog size
Timestamp m_timestamp
Detailed Description
The class underlying the main dialog.
Member Enumeration Documentation
anonymous enum
Enumerator
IDD
 { IDD = IDD_OPERATORCONSOLE_DIALOG };
anonymous enum
Enumerator
IDD
 { IDD = IDD_OPERATORCONSOLE_DIALOG };
Constructor & Destructor Documentation
COperatorConsoleDlg::COperatorConsoleDlg (CWnd * pParent = NULL)
References IDR_MAINFRAME.
    : CDialogEx(COperatorConsoleDlg::IDD, pParent)
 {
    m_hIcon = AfxGetApp()->LoadIcon(IDR_MAINFRAME);
    memset(m_qsoColor, 0, sizeof(m_qsoColor));
 }
COperatorConsoleDlg::COperatorConsoleDlg (CWnd * pParent = NULL)
Member Function Documentation
void COperatorConsoleDlg::CenterWindow (CWnd * wnd, int centerX, int centerY) protected
move 'wnd' so its center is at the screen coordinate (centerX, centerY)
Referenced by QsoMove().
 {
    if (wnd != NULL)
    {
       CRect rect;
       CPoint   pos;
       wnd->GetWindowRect(&rect);                   // current window location in screen coordinates
       pos = rect.CenterPoint();                    // center of rect in screen coordinates
       rect.OffsetRect(centerX - pos.x, centerY - pos.y); // move the rect so that its center is at (centerX, centerY) in screen coordinates
       ScreenToClient(&rect);                       // convert to client coordinates (relative to client rect of dialog)
       wnd->MoveWindow(&rect, TRUE);                // move the window
    }
 }
void COperatorConsoleDlg::CenterWindow (CWnd * wnd, int centerX, int centerY) protected
move 'wnd' so its center is at the screen coordinate (centerX, centerY)
void COperatorConsoleDlg::CreateFont (CWnd * wnd, int points, CFont * newFont) protected
void COperatorConsoleDlg::CreateFont (CWnd * wnd, int points, CFont * newFont) protected
 {
    CFont *font;
    LOGFONT  logFont;
    font = wnd->GetFont();
    font->GetLogFont(&logFont);
    logFont.lfHeight = points * 10;  // lfHeight will be interpreted as 10ths of a point
    newFont->CreatePointFontIndirect(&logFont);
 }
virtual void COperatorConsoleDlg::DoDataExchange (CDataExchange * pDX) protected virtual
void COperatorConsoleDlg::DoDataExchange (CDataExchange * pDX) protected virtual
References c_blemish, c_fps, c_image, c_log, c_logo, c_pass_fail, c_qsoCENTER, c_qsoLL, c_qsoLR, c_qsoUL, c_qsoUR, c_reason, c_setup, c_sfrPlus, c_showjson, c_startButton, c_status, c_stopButton, c_summary, IDC_FPS, IDC_IMAGE, IDC_LOG, IDC_LOGO, IDC_PASS_FAIL, IDC_QSO_CENTER, IDC_QSO_LL, IDC_QSO_LR, IDC_QSO_UL, IDC_QSO_UR, IDC_RADIO_BLEMISH, IDC_RADIO_SFR, IDC_REASON, IDC_SETUP_BUTTON, IDC_SHOWJSON, IDC_START, IDC_STATUS, IDC_STOP, and IDC_SUMMARY.
 {
    CDialogEx::DoDataExchange(pDX);
    DDX_Control(pDX, IDC_STOP,  c_stopButton);
    DDX_Control(pDX, IDC_START, c_startButton);
    DDX_Control(pDX, IDC_LOG,   c_log);
    DDX_Control(pDX, IDC_SUMMARY, c_summary);
    DDX_Control(pDX, IDC_STATUS, c_status);
    DDX_Control(pDX, IDC_REASON, c_reason);
    DDX_Control(pDX, IDC_RADIO_SFR, c_sfrPlus);
    DDX_Control(pDX, IDC_RADIO_BLEMISH, c_blemish);
    DDX_Control(pDX, IDC_IMAGE, c_image);
    DDX_Control(pDX, IDC_LOGO, c_logo);
    DDX_Control(pDX, IDC_QSO_UL, c_qsoUL);
    DDX_Control(pDX, IDC_QSO_UR, c_qsoUR);
    DDX_Control(pDX, IDC_QSO_LL, c_qsoLL);
    DDX_Control(pDX, IDC_QSO_LR, c_qsoLR);
    DDX_Control(pDX, IDC_QSO_CENTER, c_qsoCENTER);
    DDX_Control(pDX, IDC_FPS, c_fps);
    DDX_Control(pDX, IDC_SHOWJSON, c_showjson);
    DDX_Control(pDX, IDC_SETUP_BUTTON, c_setup);
    DDX_Control(pDX, IDC_PASS_FAIL, c_pass_fail);
 }
void COperatorConsoleDlg::DrawImage (LPDRAWITEMSTRUCT info)
References c_image, and CStaticBmp::Draw().
Referenced by OnDrawItem().
 {
 #if 0
    m_image.Draw(info->hDC, info->rcItem);
 #else
    c_image.Draw(this);
 #endif
 }
void COperatorConsoleDlg::DrawImage (LPDRAWITEMSTRUCT info)
void COperatorConsoleDlg::DrawLogo (LPDRAWITEMSTRUCT info)
References m_logo.
Referenced by OnDrawItem().
 {
    int   srcWidth, srcHeight;
    int dstWidth, dstHeight;
    srcWidth  = m_logo.GetWidth();
    srcHeight = m_logo.GetHeight();
    dstWidth  = info->rcItem.right  - info->rcItem.left;
    dstHeight = info->rcItem.bottom - info->rcItem.top;
    m_logo.SetHasAlphaChannel(false);
    m_logo.Draw(info->hDC, info->rcItem);
 }
void COperatorConsoleDlg::DrawLogo (LPDRAWITEMSTRUCT info)
void COperatorConsoleDlg::GetLog (CString & dst)
References c_log.
 {
    if (c_log)
       c_log.GetWindowTextA(dst);
 }
void COperatorConsoleDlg::GetLog (CString & dst)
void COperatorConsoleDlg::LogMessage (LPCTSTR msg, bool timestamp = true)
References c_log, Timestamp::Get(), and m_timestamp.
Referenced by COperatorConsoleApp::GetStdoutMsg(), and COperatorConsoleApp::UpdateResults().
 {
    if (msg && *msg)
    {
       int   end = c_log.GetWindowTextLength();
       if (timestamp)
       {
          c_log.SetSel(end, end);
          c_log.ReplaceSel(m_timestamp.Get());
          end = c_log.GetWindowTextLength();
       }
       c_log.SetSel(end, end);
       c_log.ReplaceSel(msg);
    }
 }
void COperatorConsoleDlg::LogMessage (LPCTSTR msg, bool timestamp = true)
void COperatorConsoleDlg::MoveFPS () protected
References c_fps, c_image, and MARGIN_Y.
Referenced by ReInitDialog().
 {
    CRect rect;
    CPoint   imageCenter, fpsCenter;
    int      dx, dy, bottom;
    // center the FPS item horizontally in the image, and inset it MARGIN_Y pixels from the bottom of the image
    //
    // Get the center point of the image in screen coordinates
    //
    c_image.GetWindowRect(&rect);
    imageCenter = rect.CenterPoint();
    bottom = rect.bottom - MARGIN_Y; // we want the bottom of the fps item to be inset MARGINY pixels from the bottom of the image
    //
    // Get the fps item's rectangle and center point in screen coordinates
    //
    c_fps.GetWindowRect(&rect);
    fpsCenter = rect.CenterPoint();
    dx = imageCenter.x - fpsCenter.x;   // number of pixels in X to move fps so that it is centered at imageCenter.x
    dy = bottom - rect.bottom;       // number of pixels in Y to move fps so that its bottom is MARGIN_Y pixels from bottom of image
    rect.OffsetRect(dx, dy);         // move the rect
    ScreenToClient(&rect);           // convert to client coordinates (relative to client rect of dialog)
    c_fps.MoveWindow(&rect, TRUE);      // move the window
 }
void COperatorConsoleDlg::MoveFPS () protected
void COperatorConsoleDlg::OnBnClickedRadioBlemish ()
References MSG_SET_BLEMISH, PostParentMessage(), and QsoShow().
 {
    QsoShow(false);   // hide the quadrant overlays (they're not used in Blemish)
    //
    // Tell the application to start running Blemish tests
    //
    PostParentMessage(MSG_SET_BLEMISH, 0, 0);
 }
afx_msg void COperatorConsoleDlg::OnBnClickedRadioBlemish ()
afx_msg void COperatorConsoleDlg::OnBnClickedRadioSfr ()
void COperatorConsoleDlg::OnBnClickedRadioSfr ()
References MSG_SET_SFRPLUS, PostParentMessage(), and QsoShow().
 {
    QsoShow(true); // hide the quadrant overlays (they're not used in Blemish)
    //
    // Tell the application to start running SFRplus tests
    //
    PostParentMessage(MSG_SET_SFRPLUS, 0, 0);
 }
void COperatorConsoleDlg::OnBnClickedSetupButton ()
References MSG_SETUP, and PostParentMessage().
 {
    //
    // Tell the application to launch the setup dialog
    //
    PostParentMessage(MSG_SETUP,0,0);
 }
afx_msg void COperatorConsoleDlg::OnBnClickedSetupButton ()
void COperatorConsoleDlg::OnBnClickedShowjson ()
References MSG_JSON, and PostParentMessage().
 {
    PostParentMessage(MSG_JSON, 0, 0);
 }
afx_msg void COperatorConsoleDlg::OnBnClickedShowjson ()
afx_msg void COperatorConsoleDlg::OnBnClickedStart ()
void COperatorConsoleDlg::OnBnClickedStart ()
References c_setup, eNumQuadrants, MSG_START, PostParentMessage(), ShowStartStop(), UpdateQuadrants(), and UpdateStatus().
 {
 #if 1
    ShowStartStop(false, true);   // hide the start button, show the stop button
    PostParentMessage(MSG_START, 0, 0);
    c_setup.ShowWindow(SW_HIDE); // hide the setup button while running
 #else
    //
    // This is test code that checks the color and font of
    // the Status item without running an actual test.
    //
    static bool pass = true;
    UpdateStatus(pass, "");
    pass = !pass;
    //
    // This is test code that toggles the values of the QSO display
    // without running an actual test
    //
    static bool quad[eNumQuadrants] = {true, true, true, true, true};
    UpdateQuadrants(quad);
    for (int i = 0; i < eNumQuadrants; i++)
       quad[i] = !quad[i];
 #endif
 }
afx_msg void COperatorConsoleDlg::OnBnClickedStop ()
void COperatorConsoleDlg::OnBnClickedStop ()
References c_setup, MSG_STOP, PostParentMessage(), and ShowStartStop().
 {
    ShowStartStop(true, false);   // hide the stop button, show the start button
    PostParentMessage(MSG_STOP, 0, 0);
    c_setup.ShowWindow(SW_SHOW); // show the setup button once the stop button is pressed
 }
void COperatorConsoleDlg::OnCancel () protected
References Quit().
 {
    Quit();
    CDialogEx::OnCancel();
 }
void COperatorConsoleDlg::OnCancel () protected
void COperatorConsoleDlg::OnClickedPassFail ()
References MSG_PASS_FAIL, and PostParentMessage().
 {
    //
    // Tell the application to launch the pass/fail dialog
    //
    PostParentMessage(MSG_PASS_FAIL,0,0);
 }
afx_msg void COperatorConsoleDlg::OnClickedPassFail ()
void COperatorConsoleDlg::OnClose ()
References Quit().
 {
    Quit();
    CDialogEx::OnClose();
 }
afx_msg void COperatorConsoleDlg::OnClose ()
afx_msg HBRUSH COperatorConsoleDlg::OnCtlColor (CDC * pDC, CWnd * pWnd, UINT nCtlColor) protected
HBRUSH COperatorConsoleDlg::OnCtlColor (CDC * pDC, CWnd * pWnd, UINT nCtlColor) protected
References eCenter, eLowerLeft, eLowerRight, eUpperLeft, eUpperRight, IDC_FPS, IDC_LOG, IDC_QSO_CENTER, IDC_QSO_LL, IDC_QSO_LR, IDC_QSO_UL, IDC_QSO_UR, IDC_STATUS, m_statusBrush, m_statusColor, m_whiteBrush, QsoSet(), and WHITE.
 {
    int      dialogItem;
    HBRUSH   hbr;
    //
    // Call the base class implementation first! Otherwise, it may
    // undo what we're trying to accomplish here.
    //
    hbr = CDialog::OnCtlColor(pDC, pWnd, nCtlColor);
    dialogItem = pWnd->GetDlgCtrlID();
    switch (dialogItem)
    {
    case IDC_STATUS:
       if (m_statusBrush != NULL)
       {
          pDC->SetBkColor(m_statusColor);
          hbr = m_statusBrush;
       }
       break;
    case IDC_LOG:
       pDC->SetBkColor(WHITE);
       hbr = m_whiteBrush;
       break;
    case IDC_QSO_UL:
       hbr = QsoSet(pDC, eUpperLeft);
       break;
    case IDC_QSO_UR:
       hbr = QsoSet(pDC, eUpperRight);
       break;
    case IDC_QSO_LL:
       hbr = QsoSet(pDC, eLowerLeft);
       break;
    case IDC_QSO_LR:
       hbr = QsoSet(pDC, eLowerRight);
       break;
    case IDC_QSO_CENTER:
       hbr = QsoSet(pDC, eCenter);
       break;
    case IDC_FPS:
       hbr = (HBRUSH)::GetStockObject(NULL_BRUSH);  // this necessary to get transparent background
       //       pDC->SetTextColor(WHITE);
       pDC->SetBkMode(TRANSPARENT);
    }
    return hbr;
 }
void COperatorConsoleDlg::OnDrawItem (int nIDCtl, LPDRAWITEMSTRUCT lpDrawItemStruct)
References DrawImage(), DrawLogo(), IDC_IMAGE, and IDC_LOGO.
 {
    // TODO: Add your message handler code here and/or call default
    switch (nIDCtl)
    {
    case IDC_IMAGE:
       DrawImage(lpDrawItemStruct);
       break;
    case IDC_LOGO:
       DrawLogo(lpDrawItemStruct);
       break;
    default:
       CDialogEx::OnDrawItem(nIDCtl, lpDrawItemStruct);
       break;
    }
 }
afx_msg void COperatorConsoleDlg::OnDrawItem (int nIDCtl, LPDRAWITEMSTRUCT lpDrawItemStruct)
BOOL COperatorConsoleDlg::OnEraseBkgnd (CDC * pDC)
References BLACK, c_qsoCENTER, c_qsoLL, c_qsoLR, c_qsoUL, and c_qsoUR.
 {
    BOOL  result;
 #if 0
    CRect rect;
    CWnd  *wnd = pDC->GetWindow();
    if ((wnd == &c_qsoUL)  || (wnd == &c_qsoUR) || (wnd == &c_qsoLL) || (wnd == &c_qsoLR) || (wnd == &c_qsoCENTER))
    {
       wnd->GetWindowRect(&rect);
       pDC->FillSolidRect(rect, BLACK);
       result = 1;
    }
    else
 #endif
    {
       result = CDialogEx::OnEraseBkgnd(pDC);
    }
    return result;
 }
afx_msg BOOL COperatorConsoleDlg::OnEraseBkgnd (CDC * pDC)
BOOL COperatorConsoleDlg::OnInitDialog () protected
BOOL COperatorConsoleDlg::OnInitDialog () protected
References FAIL_COLOR, IDM_ABOUTBOX, IDS_ABOUTBOX, IMAGE_NAME, LOGO_NAME, PASS_COLOR, QSO_SIZE, ResizeDlg::Resize(), STATUS_SIZE, theApp, and WHITE.
 {
    CDialogEx::OnInitDialog();
    // Add "About..." menu item to system menu.
    // IDM_ABOUTBOX must be in the system command range.
    ASSERT((IDM_ABOUTBOX & 0xFFF0) == IDM_ABOUTBOX);
    ASSERT(IDM_ABOUTBOX < 0xF000);
    CMenu* pSysMenu = GetSystemMenu(FALSE);
    if (pSysMenu != NULL)
    {
       BOOL bNameValid;
       CString strAboutMenu;
       bNameValid = strAboutMenu.LoadString(IDS_ABOUTBOX);
       ASSERT(bNameValid);
       if (!strAboutMenu.IsEmpty())
       {
          pSysMenu->AppendMenu(MF_SEPARATOR);
          pSysMenu->AppendMenu(MF_STRING, IDM_ABOUTBOX, strAboutMenu);
       }
    }
    // Set the icon for this dialog.  The framework does this automatically
    //  when the application's main window is not a dialog
    SetIcon(m_hIcon, TRUE);       // Set big icon
    SetIcon(m_hIcon, FALSE);      // Set small icon
    ShowWindow(SW_NORMAL);//SW_MAXIMIZE);
    // TODO: Add extra initialization here
    c_log.SetLimitText(0x7ffffffe);
    c_sfrPlus.SetCheck(BST_CHECKED); // select the SFRplus radio button
    OnBnClickedRadioSfr();           // tell the app that the button is selected (so that it knows which test to run)
    ShowStartStop(true, false);         // show the Start button and hide the Stop button
 #if 0
    m_image.Load(IMAGE_NAME);
 #endif
    m_logo.Load(LOGO_NAME);
 #if 1
    //m_logo.SetTransparentColor(WHITE);
    m_logo.SetHasAlphaChannel(false);
 #endif
    // Resize();                     // resize dialog to make it big enough for image item (also resizes c_image if needed)
    ResizeDlg resize;
    // HDK COMMENTED THESE FOR TEST
    resize.Resize(this, &c_image, theApp.GetImageWidth(), theApp.GetImageHeight());
    CWnd::CenterWindow();            // center the dialog on the screen
    QsoMove();
    MoveFPS();
    c_image.Init();                  // create bitmap and drawing context-- do this after the control has been resized [i.e. after calling Resize()]
    //
    // Create brushes to use to draw the background of the Status item.
    // We use different colors for passed and failed tests.
    //
    m_passBrush.CreateSolidBrush(PASS_COLOR);
    m_failBrush.CreateSolidBrush(FAIL_COLOR);
    //
    // Create a brush with a sold white background.  This can be used
    // by any item that wants a white background.
    //
    m_whiteBrush.CreateSolidBrush(WHITE);
    //
    // Set the brush handle to NULL to indicate that we don't want to change the background color
    // of the Status item (the color doesn't get changed until a test has been run).
    //
    m_statusBrush = NULL;
    m_statusColor = 0;
    //
    // Create fonts to use for the status and qso items.  The fonts are the
    // same as the current font except that the point size is changed.
    //
    CreateFont(&c_status, STATUS_SIZE, &m_statusFont);
    CreateFont(&c_qsoUL,  QSO_SIZE,    &m_qsoFont);
    c_status.SetFont(&m_statusFont);
    c_qsoUL.SetFont(&m_qsoFont);
    c_qsoUR.SetFont(&m_qsoFont);
    c_qsoLL.SetFont(&m_qsoFont);
    c_qsoLR.SetFont(&m_qsoFont);
    c_qsoCENTER.SetFont(&m_qsoFont);
    return TRUE;  // return TRUE  unless you set the focus to a control
 }
void COperatorConsoleDlg::OnOK () protected
void COperatorConsoleDlg::OnOK () protected
References Quit().
 {
    Quit();
    CDialogEx::OnOK();
 }
void COperatorConsoleDlg::OnPaint () protected
References m_hIcon, x, and y.
 {
    if (IsIconic())
    {
       CPaintDC dc(this); // device context for painting
       SendMessage(WM_ICONERASEBKGND, reinterpret_cast<WPARAM>(dc.GetSafeHdc()), 0);
       // Center icon in client rectangle
       int cxIcon = GetSystemMetrics(SM_CXICON);
       int cyIcon = GetSystemMetrics(SM_CYICON);
       CRect rect;
       GetClientRect(&rect);
       int x = (rect.Width() - cxIcon + 1) / 2;
       int y = (rect.Height() - cyIcon + 1) / 2;
       // Draw the icon
       dc.DrawIcon(x, y, m_hIcon);
    }
    else
    {
       CDialogEx::OnPaint();
    }
 }
afx_msg void COperatorConsoleDlg::OnPaint () protected
HCURSOR COperatorConsoleDlg::OnQueryDragIcon () protected
References m_hIcon.
 {
    return static_cast<HCURSOR>(m_hIcon);
 }
afx_msg HCURSOR COperatorConsoleDlg::OnQueryDragIcon () protected
void COperatorConsoleDlg::OnSysCommand (UINT nID, LPARAM lParam) protected
References IDM_ABOUTBOX.
 {
    if ((nID & 0xFFF0) == IDM_ABOUTBOX)
    {
       CAboutDlg dlgAbout;
       dlgAbout.DoModal();
    }
    else
    {
       CDialogEx::OnSysCommand(nID, lParam);
    }
 }
afx_msg void COperatorConsoleDlg::OnSysCommand (UINT nID, LPARAM lParam) protected
void COperatorConsoleDlg::PostParentMessage (UINT message, WPARAM wParam = 0, LPARAM lParam = 0) protected
References theApp.
Referenced by OnBnClickedRadioBlemish(), OnBnClickedRadioSfr(), OnBnClickedSetupButton(), OnBnClickedShowjson(), OnBnClickedStart(), OnBnClickedStop(), and OnClickedPassFail().
 {
    ::PostThreadMessage(theApp.m_nThreadID, message, 0, 0);
 }
void COperatorConsoleDlg::PostParentMessage (UINT message, WPARAM wParam = 0, LPARAM lParam = 0) protected
void COperatorConsoleDlg::QsoMove () protected
References c_image, c_qsoCENTER, c_qsoLL, c_qsoLR, c_qsoUL, c_qsoUR, CenterWindow(), ResizeDlg::GetWindowSize(), height, and width.
Referenced by ReInitDialog().
 {
    CRect rect;
    CPoint   center;
    int      width, height, dx, dy;
    //
    // Get the location, size, and center point of the image
    //
    ResizeDlg::GetWindowSize(&c_image, &width, &height, &rect);
    center = rect.CenterPoint();
    //
    // Calculate the distance in x and y from the center
    // of the image rect to the center of a quadrant
    //
    dx = (width  / 4);
    dy = (height / 4);
    //
    // Now move each window so that it's centered at the center of its quadrant
    //
    CenterWindow(&c_qsoUL,     center.x - dx, center.y - dy);   // upper left
    CenterWindow(&c_qsoUR,     center.x + dx, center.y - dy);   // upper right
    CenterWindow(&c_qsoLL,     center.x - dx, center.y + dy);   // lower left
    CenterWindow(&c_qsoLR,     center.x + dx, center.y + dy);   // lower right
    CenterWindow(&c_qsoCENTER, center.x,      center.y);     // center
 }
void COperatorConsoleDlg::QsoMove () protected
HBRUSH COperatorConsoleDlg::QsoSet (CDC * cdc, EQuadrant quadrant) protected
HBRUSH COperatorConsoleDlg::QsoSet (CDC * cdc, EQuadrant quadrant) protected
References m_qsoColor.
Referenced by OnCtlColor().
 {
    HBRUSH   hbr = (HBRUSH)::GetStockObject(NULL_BRUSH);  // this necessary to get transparent background
    cdc->SetTextColor(m_qsoColor[quadrant]);
    cdc->SetBkMode(TRANSPARENT);
    return hbr;
 }
void COperatorConsoleDlg::QsoShow (bool show) protected
void COperatorConsoleDlg::QsoShow (bool show) protected
References c_qsoCENTER, c_qsoLL, c_qsoLR, c_qsoUL, and c_qsoUR.
Referenced by OnBnClickedRadioBlemish(), and OnBnClickedRadioSfr().
 {
    int   value = show ? SW_SHOW : SW_HIDE;
    c_qsoUL.ShowWindow(value);
    c_qsoUR.ShowWindow(value);
    c_qsoLL.ShowWindow(value);
    c_qsoLR.ShowWindow(value);
    c_qsoCENTER.ShowWindow(value);
 }
void COperatorConsoleDlg::Quit () protected
References AppThread::Quit(), and theApp.
Referenced by OnCancel(), OnClose(), and OnOK().
 {
    //
    // We need to tell the application that we're ready to close the dialog window so that it
    // can do any cleanup (e.g. waiting for threads to finish) before the dialog closes.
    // This allows a message to be posted to the log window while the app finishes.
    //
    // Once the app is done, we can go ahead and close the dialog.
    //
    theApp.Quit();
 }
void COperatorConsoleDlg::Quit () protected
void COperatorConsoleDlg::ReInitDialog (void)
Allows the display to be resized after the user changes the image size.
References ResizeDlg::BidirectionalResize(), c_image, CStaticBmp::Init(), MoveFPS(), QsoMove(), theApp, and CStaticBmp::Update().
 {
    ShowWindow(SW_HIDE);
    c_image.Update(NULL);
    // Resize();                     // resize dialog to make it big enough for image item (also resizes c_image if needed)
    ResizeDlg resize;
    resize.BidirectionalResize(this, &c_image, theApp.GetImageWidth(), theApp.GetImageHeight());
    CWnd::CenterWindow();            // center the dialog on the screen
    QsoMove();
    MoveFPS();
    c_image.Init();                  // create bitmap and drawing context-- do this after the control has been resized [i.e. after calling Resize()]
    ShowWindow(SW_NORMAL);
 }
void COperatorConsoleDlg::ReInitDialog (void)
Allows the display to be resized after the user changes the image size.
HBRUSH COperatorConsoleDlg::SetBGColor (CDC * dc, CBrush brush, COLORREF color) protected
HBRUSH COperatorConsoleDlg::SetBGColor (CDC * dc, CBrush brush, COLORREF color) protected
 {
    dc->SetBkColor(color);
    return (HBRUSH)brush;
 }
void COperatorConsoleDlg::ShowStartStop (bool start, bool stop) protected
References c_startButton, and c_stopButton.
Referenced by OnBnClickedStart(), and OnBnClickedStop().
 {
    //
    // Show or hide the start and stop buttons
    //
    c_startButton.ShowWindow(start ? SW_SHOW : SW_HIDE);
    c_stopButton.ShowWindow(stop   ? SW_SHOW : SW_HIDE);
 }
void COperatorConsoleDlg::ShowStartStop (bool start, bool stop) protected
void COperatorConsoleDlg::UpdateFPS (long long ms)
References c_fps, and c_image.
Referenced by COperatorConsoleApp::UpdateResults().
 {
    double   fps = 1000./(double)ms;
    char  str[40];
    sprintf_s(str, sizeof(str)-1, "%.3lf FPS", fps);
    c_fps.SetWindowText(str);
    c_fps.Invalidate();
    c_image.Invalidate();   // if we don't do this the old QSO value doesn't get erased
 }
void COperatorConsoleDlg::UpdateFPS (long long ms)
void COperatorConsoleDlg::UpdateImage (void * buf)
void COperatorConsoleDlg::UpdateImage (void * buf)
References c_image, and CStaticBmp::Update().
Referenced by COperatorConsoleApp::UpdateResults().
 {
    c_image.Update(buf);
 }
void COperatorConsoleDlg::UpdateQuadrant (const bool * passed, EQuadrant quadrant, CWnd * control) protected
References FAIL_COLOR, m_qsoColor, PASS_COLOR, QSO_FAILED, and QSO_PASSED.
Referenced by UpdateQuadrants().
 {
    COLORREF color;
    const char  *str;
    if (passed[quadrant])
    {
       color = PASS_COLOR;
       str   = QSO_PASSED;
    }
    else
    {
       color = FAIL_COLOR;
       str   = QSO_FAILED;
    }
    m_qsoColor[quadrant] = color;
    control->SetWindowText(str);
    control->Invalidate();
 }
void COperatorConsoleDlg::UpdateQuadrant (const bool * passed, EQuadrant quadrant, CWnd * control) protected
void COperatorConsoleDlg::UpdateQuadrants (const bool * data)
void COperatorConsoleDlg::UpdateQuadrants (const bool * data)
References c_image, c_qsoCENTER, c_qsoLL, c_qsoLR, c_qsoUL, c_qsoUR, eCenter, eLowerLeft, eLowerRight, eUpperLeft, eUpperRight, and UpdateQuadrant().
Referenced by OnBnClickedStart(), and COperatorConsoleApp::UpdateResultsSFRplus().
 {
    UpdateQuadrant(data, eUpperLeft,  &c_qsoUL);
    UpdateQuadrant(data, eUpperRight, &c_qsoUR);
    UpdateQuadrant(data, eLowerLeft,  &c_qsoLL);
    UpdateQuadrant(data, eLowerRight, &c_qsoLR);
    UpdateQuadrant(data, eCenter,     &c_qsoCENTER);
    c_image.Invalidate();   // if we don't do this the old QSO value doesn't get erased
 }
void COperatorConsoleDlg::UpdateStatus (bool passed, LPCTSTR reason)
References c_reason, c_status, FAIL_COLOR, FAILED_TEXT, m_failBrush, m_passBrush, m_statusBrush, m_statusColor, PASS_COLOR, and PASSED_TEXT.
Referenced by OnBnClickedStart(), and COperatorConsoleApp::UpdateResults().
 {
    COLORREF color = passed ? PASS_COLOR : FAIL_COLOR;
    if (passed)
    {
       m_statusColor = PASS_COLOR;
       m_statusBrush = m_passBrush;
    }
    else
    {
       m_statusColor = FAIL_COLOR;
       m_statusBrush = m_failBrush;
    }
    // Set the text size (ignore for now)
    c_status.SetWindowText(passed ? PASSED_TEXT : FAILED_TEXT); // set PASS/FAIL text
    c_reason.SetSel(0, -1);                            // select all of the text
    c_reason.ReplaceSel(passed ? "" : (LPCTSTR)reason);         // if test failed, display reason
 }
void COperatorConsoleDlg::UpdateStatus (bool passed, LPCTSTR reason)
void COperatorConsoleDlg::UpdateSummary (LPCTSTR summary)
void COperatorConsoleDlg::UpdateSummary (LPCTSTR summary)
References c_summary.
Referenced by COperatorConsoleApp::UpdateResults().
 {
    c_summary.SetSel(0, -1);      // select all the text
    c_summary.ReplaceSel(summary);   // replace selection
 }
Member Data Documentation
CButton COperatorConsoleDlg::c_blemish
The Blemish radial button.
Referenced by DoDataExchange().
CStatic COperatorConsoleDlg::c_fps
The frames-per-second display.
Referenced by DoDataExchange(), MoveFPS(), and UpdateFPS().
CStaticBmp COperatorConsoleDlg::c_image
owner-drawn control that displays an image from the acquisition source
Referenced by DoDataExchange(), DrawImage(), MoveFPS(), QsoMove(), ReInitDialog(), UpdateFPS(), UpdateImage(), and UpdateQuadrants().
CEdit COperatorConsoleDlg::c_log
The log display.
Referenced by DoDataExchange(), GetLog(), and LogMessage().
CStatic COperatorConsoleDlg::c_logo
Referenced by DoDataExchange().
CButton COperatorConsoleDlg::c_pass_fail
Referenced by DoDataExchange().
CStatic COperatorConsoleDlg::c_qsoCENTER
The static text for the center QSO.
Referenced by DoDataExchange(), OnEraseBkgnd(), QsoMove(), QsoShow(), and UpdateQuadrants().
CStatic COperatorConsoleDlg::c_qsoLL
The static text for the lower left QSO.
Referenced by DoDataExchange(), OnEraseBkgnd(), QsoMove(), QsoShow(), and UpdateQuadrants().
CStatic COperatorConsoleDlg::c_qsoLR
The static text for the lower right QSO.
Referenced by DoDataExchange(), OnEraseBkgnd(), QsoMove(), QsoShow(), and UpdateQuadrants().
CStatic COperatorConsoleDlg::c_qsoUL
The static text for the upper left QSO.
Referenced by DoDataExchange(), OnEraseBkgnd(), QsoMove(), QsoShow(), and UpdateQuadrants().
CStatic COperatorConsoleDlg::c_qsoUR
The static text for the upper right QSO.
Referenced by DoDataExchange(), OnEraseBkgnd(), QsoMove(), QsoShow(), and UpdateQuadrants().
CEdit COperatorConsoleDlg::c_reason
The reason display.
Referenced by DoDataExchange(), and UpdateStatus().
CButton COperatorConsoleDlg::c_setup
The setup button.
Referenced by DoDataExchange(), OnBnClickedStart(), and OnBnClickedStop().
CButton COperatorConsoleDlg::c_sfrPlus
The sfrPlus radial button.
Referenced by DoDataExchange().
CButton COperatorConsoleDlg::c_showjson
The 'show JSON' button.
Referenced by DoDataExchange().
CButton COperatorConsoleDlg::c_startButton
Referenced by DoDataExchange(), and ShowStartStop().
CStatic COperatorConsoleDlg::c_status
The status display.
Referenced by DoDataExchange(), and UpdateStatus().
CButton COperatorConsoleDlg::c_stopButton
Referenced by DoDataExchange(), and ShowStartStop().
CEdit COperatorConsoleDlg::c_summary
The summary display.
Referenced by DoDataExchange(), and UpdateSummary().
CSize COperatorConsoleDlg::m_delta protected
number of pixels to increase image item and dialog size
CBrush COperatorConsoleDlg::m_failBrush protected
the brush (i.e. background color) to be used for Status item when the test has failed
Referenced by UpdateStatus().
HICON COperatorConsoleDlg::m_hIcon protected
Referenced by OnPaint(), and OnQueryDragIcon().
CImage COperatorConsoleDlg::m_logo protected
Imatest logo (goes at top of info display)
Referenced by DrawLogo().
CBrush COperatorConsoleDlg::m_passBrush protected
the brush (i.e. background color) to be used for Status item when the test has passed
Referenced by UpdateStatus().
COLORREF COperatorConsoleDlg::m_qsoColor protected
color to use for each QSO item
Referenced by QsoSet(), and UpdateQuadrant().
CFont COperatorConsoleDlg::m_qsoFont protected
font to use for QSO (Quadrant Status Overlay) items
HBRUSH COperatorConsoleDlg::m_statusBrush protected
handle to the brush to be used when drawing the Status item
Referenced by OnCtlColor(), and UpdateStatus().
COLORREF COperatorConsoleDlg::m_statusColor protected
unused if m_statusBrush == NULL
Referenced by OnCtlColor(), and UpdateStatus().
CFont COperatorConsoleDlg::m_statusFont protected
font to use for Status item (used to change font size for the item)
Timestamp COperatorConsoleDlg::m_timestamp protected
Referenced by LogMessage().
CBrush COperatorConsoleDlg::m_whiteBrush protected
Referenced by OnCtlColor().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/OperatorConsoleDlg.h
OperatorConsoleDlg.h
Documentation/Operator-Console/OperatorConsoleDlg.cpp
OperatorConsoleDlg.cpp