Operator Console: Documentation/Operator-Console/JSON/JSON_Base64.cpp File Reference
JSON_Base64.cpp File Reference
#include "JSON_Base64.h"
#include "JSONGlobals.h"
Functions
static const json_char * chars64 (JSON_TEXT("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"))
json_uchar toBinary (json_uchar c) json_pure
Function Documentation
static const json_char* chars64 (JSON_TEXT("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")) static
Referenced by JSONBase64::json_decode64(), and JSONBase64::json_encode64().
json_uchar toBinary (json_uchar c) inline
References JSON_ASSERT_SAFE, json_global, JSON_TEXT, and json_uchar.
Referenced by JSONBase64::json_decode64().
{
     JSON_ASSERT_SAFE(c >= 43, json_global(ERROR_LOWER_RANGE) + JSON_TEXT("base64"), return JSON_TEXT('0'););
     JSON_ASSERT_SAFE(c <= 122, json_global(ERROR_UPPER_RANGE) + JSON_TEXT("base64"), return JSON_TEXT('0'););
    static json_uchar binaryConvert[80] = {62,48,49,50,63,52,53,54,55,56,57,58,59,60,61,249,250,251,252,253,254,255,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51};
     return binaryConvert[c - 43];
 }