Operator Console: foo.cpp File Reference
foo.cpp File Reference
Functions
void Resize ()
BOOL CALLBACK OffsetChildPos (HWND hwnd, LPARAM lParam)
void GetImageWindowDelta ()
void GetWindowCenter (CWnd *wnd, CPoint *center)
void GetWindowSize (CWnd *wnd, int *width, int *height, CRect *bnds)
void OffsetWindowPos (CWnd *wnd, int dx, int dy)
void Resize (CWnd *dialog, CWnd *window, int width, int height)
void GetImageWindowDelta (int width, int height)
void OffsetWindowSize (CWnd *wnd, int dx, int dy)
void OffsetWindowPos (CWnd *parent, CWnd *wnd, int dx, int dy)
Variables
CSize m_delta
CWnd * m_dialog
CWnd * m_window
Function Documentation
void GetImageWindowDelta ()
Referenced by Resize().
void GetImageWindowDelta (int width, int height)
References GetWindowSize(), and m_delta.
 {
    int   itemWidth,  itemHeight;
    //
    // Get the current width and height of the image dialog item
    //
    GetWindowSize(&c_image, &itemWidth, &itemHeight);
    //
    // Get the difference in the width and height.
    // This is how much the sizes of the image item and dialog need to be increased.
    // This is also how much we need to move the other dialog items to accomodate the new image size.
    //
    m_delta.cx = width  - itemWidth;
    m_delta.cy = height - itemHeight;
 }
void GetWindowCenter (CWnd * wnd, CPoint * center)
 {
    if (wnd != NULL && center != NULL)
    {
       CRect rect;
       wnd->GetWindowRect(rect);
       *center = rect.CenterPoint();
    }
 }
void GetWindowSize (CWnd * wnd, int * width, int * height, CRect * bnds)
Referenced by GetImageWindowDelta(), and OffsetWindowSize().
 {
    if (wnd != NULL)
    {
       CRect rect;
       CRect *r = (bnds == NULL) ? &rect : bnds;
       wnd->GetWindowRect(r);
       if (width != NULL)
       {
          *width  = r->Width();
       }
       if (height != NULL)
       {
          *height = r->Height();
       }
    }
 }
BOOL CALLBACK OffsetChildPos (HWND hwnd, LPARAM lParam)
References MoveData::delta, MoveData::dialog, height, MoveData::skip, and width.
Referenced by Resize().
 {
    MoveData *data = (MoveData *)lParam;
    RECT  rect;
    int      width, height;
    POINT ul;
    if (hwnd != data->skip)
    {
       ::GetWindowRect(hwnd, &rect); // rect is in screen coords
       ul.x = rect.left;
       ul.y = rect.top;
       ::ScreenToClient(data->dialog, &ul);   // make ul coords relative to dialog
       width  = rect.right  - rect.left;
       height = rect.bottom - rect.top;
       ::MoveWindow(hwnd, ul.x + data->delta->cx, ul.y + data->delta->cy, width, height, TRUE);
    }
    return TRUE;
 }
void OffsetWindowPos (CWnd * wnd, int dx, int dy)
void OffsetWindowPos (CWnd * parent, CWnd * wnd, int dx, int dy)
 {
    if (wnd != NULL)
    {
       CRect rect;
       wnd->GetWindowRect(&rect);       // current window location in screen coordinates
       parent->ScreenToClient(&rect);      // current location in client coords (relative to client rect of parent)
       rect.OffsetRect(dx, dy);         // offset the rect by (dx, dy)
       wnd->MoveWindow(&rect, TRUE);    // move the window
    }
 }
void OffsetWindowSize (CWnd * wnd, int dx, int dy)
References GetWindowSize(), height, and width.
Referenced by Resize().
 {
    int width, height;
    GetWindowSize(wnd, &width, &height);
    wnd->SetWindowPos(NULL, 0, 0, width + dx, height + dy, SWP_NOMOVE | SWP_NOZORDER);
 }
void Resize ()
void Resize (CWnd * dialog, CWnd * window, int width, int height)
References MoveData::delta, MoveData::dialog, GetImageWindowDelta(), m_delta, OffsetChildPos(), OffsetWindowSize(), and MoveData::skip.
 {
    MoveData data;
    int         dy;
    //
    // Get the difference in size between the window an the desired width and height
    //
    GetImageWindowDelta();
    //
    // Resize the window
    //
    OffsetWindowSize(window, m_delta.cx, m_delta.cy);
    if (m_delta.cx != 0 || m_delta.cy != 0)
    {
       //
       // Resize the dialog.  It can grow or shrink in x, but
       // its height may not be less than its original height.
       //
       dy = m_delta.cy > 0 ? m_delta.cy : 0;
       OffsetWindowSize(dialog, m_delta.cx, dy);    // resize the dialog
       //
       // Move the rest of the items dx pixels to the left or right.  We're not
       // going to change the y coordinates, so we set m_delta.cy to 0.
       //
       m_delta.cy = 0;
       //
       // Move all of the dialog items to compensate for the new size of 'window'.  EnumChildWindows()
       // will call OffsetChildPos() for each of the Dialog's child windows (i.e. all dialog items).
       // We want to move every item except for the image item.
       //
       data.delta  = &m_delta;
       data.skip   = window->m_hWnd; // we don't want to move 'window'
       data.dialog = dialog->m_hWnd; // handle to the dialog window (we need this for converting coordinates)
       ::EnumChildWindows(dialog->m_hWnd, OffsetChildPos, (LPARAM)&data);
    }
 }
Variable Documentation
CSize m_delta
Referenced by GetImageWindowDelta(), and Resize().
CWnd* m_dialog
Referenced by ModelessDialogThread::ModelessDialogThread().
CWnd* m_window