Operator Console: ImageTest Class Reference
ImageTest Class Reference abstract
An abstract class that defines an image test to be performed.
#include <ImageTest.h>
Public Member Functions
ImageTest (void)
virtual ~ImageTest (void)
virtual void ParseResults (string &results)=0
This must be implemented by subclass.
virtual void Run ()
Runs the test pointed to by m_imatestFunc.
virtual void Run (void *raw_pixels, int width, int height, const Config *config)
void GetLog (CString &dst)
void GetFailInfo (CString &dst)
void GetJSON (CString &dst)
void GetName (CString &name)
void GetSummary (CString &dst)
void Init (void *raw_pixels, int width, int height, const Config *config)
bool Passed ()
void SetBuffer (void *buf)
ImageTest (void)
virtual ~ImageTest (void)
virtual void ParseResults (string &results)=0
This must be implemented by subclass.
virtual void Run ()
virtual void Run (void *raw_pixels, int width, int height, const Config *config)
void GetLog (CString &dst)
void GetFailInfo (CString &dst)
void GetJSON (CString &dst)
void GetName (CString &name)
void GetSummary (CString &dst)
void Init (void *raw_pixels, int width, int height, const Config *config)
bool Passed ()
void SetBuffer (void *buf)
Static Public Member Functions
static UINT __cdecl ThreadProc (void *param)
param must be a pointer to a ThreadControl object; param->m_data must point to an ImageTest object
static UINT __cdecl ThreadProc (void *param)
param must be a pointer to a ThreadControl object; param->m_data must point to an ImageTest object
Public Attributes
int m_width
int m_height
int m_ncolors
const char * m_extension
const char * m_fileroot
const char * m_serialNumber
const char * m_partNumber
const char * m_iniFilePathName
const char * m_programPath
const char * m_name
long long m_elapsed
CString m_elapsedStr
Timestamp m_timestamp
Protected Member Functions
bool AllocateRGB ()
void AppendLog (CString &log)
void ClearLog ()
void ClearJSON ()
void ClearFailInfo ()
void ClearSummary ()
void DeleteRGB ()
bool GetDataNode (string &results, JSONNode &data, bool logErrors=true)
bool GetPassFailNode (JSONNode &data, JSONNode &passFail, bool logErrors=true)
void PlanesFromRGB ()
converts from m_rawPixels to m_rgb
void GetString (JSONNode &node, const char *name, json_string &string, bool logErrors=true)
void InitResults ()
void ParseFailures (const JSONNode *data)
void RGBFromPlanes (UINT *rgb)
converts from m_rgb to rgb
void SaveImage (RGBQUAD *buf, const char *filename)
void SetJSON (string &src)
void SetSummary (CString &src)
bool AllocateRGB ()
void AppendLog (CString &log)
void ClearLog ()
void ClearJSON ()
void ClearFailInfo ()
void ClearSummary ()
void DeleteRGB ()
bool GetDataNode (string &results, JSONNode &data, bool logErrors=true)
bool GetPassFailNode (JSONNode &data, JSONNode &passFail, bool logErrors=true)
void PlanesFromRGB ()
void GetString (JSONNode &node, const char *name, json_string &string, bool logErrors=true)
void InitResults ()
void ParseFailures (const JSONNode *data)
void RGBFromPlanes (UINT *rgb)
void SaveImage (RGBQUAD *buf, const char *filename)
void SetJSON (string &src)
void SetSummary (CString &src)
Protected Attributes
const void * m_rawPixels
unsigned char * m_rgb
bool m_passed
const TestID * m_tests
int m_numTests
Timer m_time
ImatestShellFunc m_imatestFunc
CriticalCString m_jsonResults
the full results of the test in JSON format
CriticalCString m_summary
the summary results of the test (these get displayed in the dialog)
CriticalCString m_failInfo
reasons that image failed the test
CriticalCString m_log
log message(s)
Detailed Description
An abstract class that defines an image test to be performed.
ImageTest is an abstract class that defines an image test to be performed (e.g. blemish, SFRplus). To use this class, create a subclass and implement the ParseResults() method.
Some member variables are used by more than 1 thread. To prevent these variables from being accessed simultaneously from multiple threads, they are protected by critical sections, which limit access to one thread at a time.
In theory there shouldn't be a case where both threads are trying to access the variable simultaneously, but theory is often different than the real world. The sequence of events in the threads is as follows:
The main thread signals the ImageTest thread to run its test once.
The test runs once It sets the values of the shared member variables It sends a "done" message to the main thread It waits for a signal to run again Repeat
The main thread receives the "done" message It makes copies of the shared member variables It signals the ImageTest thread to run once Repeat
In this scenario, the main thread only accesses the shared data when it has received the "done" message (i.e. after the ImageTest thread is finished using the shared data), and the ImageTest thread only accesses the shared data while the main thread is doing other things.
Constructor & Destructor Documentation
ImageTest::ImageTest (void)
References m_extension, m_fileroot, m_height, m_imatestFunc, m_iniFilePathName, m_name, m_partNumber, m_programPath, m_rawPixels, m_rgb, m_serialNumber, and m_width.
 {
    m_width           = 0;
    m_height          = 0;
    m_extension       = NULL;
    m_fileroot        = NULL;
    m_serialNumber    = NULL;
    m_partNumber      = NULL;
    m_iniFilePathName = NULL;
    m_programPath     = NULL;
    m_rawPixels      = NULL;
    m_name            = NULL;
    m_imatestFunc     = NULL;
    m_rgb             = NULL;
 }
ImageTest::~ImageTest (void) virtual
References DeleteRGB().
 {
    DeleteRGB();
 }
ImageTest::ImageTest (void)
virtual ImageTest::~ImageTest (void) virtual
Member Function Documentation
bool ImageTest::AllocateRGB () protected
References DeleteRGB(), m_height, m_ncolors, m_rgb, and m_width.
Referenced by Init().
 {
    //
    // If the source data is 3-channel (i.e. rgb) in rgba format, then
    // we will need to convert it into a planar format for MATLAB.
    //
    if (m_ncolors == 3)
    {
       DeleteRGB();
       m_rgb = new unsigned char[m_width * m_height * 3];
    }
    return m_rgb != NULL;
 }
bool ImageTest::AllocateRGB () protected
void ImageTest::AppendLog (CString & log) inline protected
 {m_log.Append(log);}
void ImageTest::AppendLog (CString & log) inline protected
Referenced by Run().
 {m_log.Append(log);}
void ImageTest::ClearFailInfo () inline protected
 {m_failInfo.Clear();}
void ImageTest::ClearFailInfo () inline protected
 {m_failInfo.Clear();}
void ImageTest::ClearJSON () inline protected
 {m_jsonResults.Clear();}
void ImageTest::ClearJSON () inline protected
 {m_jsonResults.Clear();}
void ImageTest::ClearLog () inline protected
 {m_log.Clear();}
void ImageTest::ClearLog () inline protected
 {m_log.Clear();}
void ImageTest::ClearSummary () inline protected
 {m_summary.Clear();}
void ImageTest::ClearSummary () inline protected
 {m_summary.Clear();}
void ImageTest::DeleteRGB () protected
References m_rgb.
Referenced by AllocateRGB(), and ~ImageTest().
 {
    if (m_rgb != NULL)
    {
       delete [] m_rgb;
       m_rgb = NULL;
    }
 }
void ImageTest::DeleteRGB () protected
bool ImageTest::GetDataNode (string & results, JSONNode & data, bool logErrors = true) protected
References CriticalCString::Append(), Timestamp::Get(), m_log, m_timestamp, and libjson::parse().
 {
    bool     success = false;
    JSONNode node;
    CString     log;
    try
    {
       node = libjson::parse(results.c_str());
       data = node.at(0);
       success = true;
    }
    catch(...)
    {
       if (logErrors)
       {
          log.AppendFormat("%s Results have invalid format\n", (LPCTSTR)m_timestamp.Get());
       }
       success = false;
    }
    m_log.Append(log);
    return success;
 }
bool ImageTest::GetDataNode (string & results, JSONNode & data, bool logErrors = true) protected
void ImageTest::GetFailInfo (CString & dst) inline
 {m_failInfo.Get(dst);}
void ImageTest::GetFailInfo (CString & dst) inline
Referenced by COperatorConsoleApp::GetResults().
 {m_failInfo.Get(dst);}
void ImageTest::GetJSON (CString & dst) inline
 {m_jsonResults.Get(dst);}
void ImageTest::GetJSON (CString & dst) inline
Referenced by COperatorConsoleApp::GetResults().
 {m_jsonResults.Get(dst);}
void ImageTest::GetLog (CString & dst) inline
 {m_log.Get(dst);}
void ImageTest::GetLog (CString & dst) inline
Referenced by COperatorConsoleApp::GetResults().
 {m_log.Get(dst);}
void ImageTest::GetName (CString & name) inline
 {name = m_name;}
void ImageTest::GetName (CString & name) inline
Referenced by COperatorConsoleApp::GetResults().
 {name = m_name;}
bool ImageTest::GetPassFailNode (JSONNode & data, JSONNode & passFail, bool logErrors = true) protected
References CriticalCString::Append(), Timestamp::Get(), m_log, and m_timestamp.
 {
    bool  validNode;
    CString  log;
    try
    {
       passFail = data.at("passfail");
       validNode = true;
    }
    catch(...)
    {
       validNode = false;
       if (logErrors)
       {
          log.AppendFormat("%s Couldn't find pass/fail section in results\n", (LPCTSTR)m_timestamp.Get());
       }
    }
    m_log.Append(log);
    return validNode;
 }
bool ImageTest::GetPassFailNode (JSONNode & data, JSONNode & passFail, bool logErrors = true) protected
void ImageTest::GetString (JSONNode & node, const char * name, json_string & string, bool logErrors = true) protected
References CriticalCString::Append(), JSONNode::as_array(), JSONNode::as_string(), Timestamp::Get(), m_log, and m_timestamp.
 {
    try
    {
       string = node.at(name).as_array()[0].as_string();
    }
    catch(...)
    {
       CString  log;
       log.AppendFormat("%s Couldn't find %s value\n", (LPCTSTR)m_timestamp.Get(), name);
       m_log.Append(log);
    }
 }
void ImageTest::GetString (JSONNode & node, const char * name, json_string & string, bool logErrors = true) protected
void ImageTest::GetSummary (CString & dst) inline
Referenced by COperatorConsoleApp::GetResults().
 {m_summary.Get(dst);}
void ImageTest::GetSummary (CString & dst) inline
 {m_summary.Get(dst);}
void ImageTest::Init (void * raw_pixels, int width, int height, const Config * config)
References AllocateRGB(), height, Config::m_extension, m_extension, Config::m_fileRoot, m_fileroot, m_height, Config::m_iniFilePathName, m_iniFilePathName, Config::m_ncolors, m_ncolors, Config::m_partNumber, m_partNumber, Config::m_programPath, m_programPath, m_rawPixels, Config::m_serialNumber, m_serialNumber, m_width, and width.
Referenced by COperatorConsoleApp::InitBlemishThread(), COperatorConsoleApp::InitSFRplusThread(), and Run().
 {
    m_rawPixels       = raw_pixels;
    m_width           = width;
    m_height          = height;
    m_fileroot        = config->m_fileRoot;
    m_serialNumber    = config->m_serialNumber;
    m_partNumber      = config->m_partNumber;
    m_extension       = config->m_extension;
    m_iniFilePathName = config->m_iniFilePathName;
    m_programPath     = config->m_programPath;
    m_ncolors         = config->m_ncolors;
    AllocateRGB();
 }
void ImageTest::Init (void * raw_pixels, int width, int height, const Config * config)
void ImageTest::InitResults () protected
References CriticalCString::Clear(), m_failInfo, m_jsonResults, m_log, m_passed, and m_summary.
Referenced by Run().
 {
    m_jsonResults.Clear();
    m_summary.Clear();
    m_failInfo.Clear();
    m_log.Clear();
    m_passed = false;
 }
void ImageTest::InitResults () protected
void ImageTest::ParseFailures (const JSONNode * data) protected
References CriticalCString::Append(), JSONNode::as_array(), JSONNode::as_bool(), FAIL_DELIMITER, m_failInfo, m_log, m_numTests, m_tests, and CriticalCString::Set().
 {
    CString  fail;
    CString  log;
    int      i;
    bool  first  = true;
    bool  passed = false;
    for (i = 0; i < m_numTests; i++)
    {
       try
       {
          passed = passfail->at(m_tests[i].key).as_array()[0].as_bool();
          if (!passed)
          {
             if (!first)
             {
                fail.Append(FAIL_DELIMITER);  // add a separator before adding the next test name
             }
             fail.Append(m_tests[i].name); // add the name of the test that failed to the m_failInfo string
             first = false;
          }
       }
       catch(...)
       {
          log.AppendFormat("Couldn't find %s in results\n", m_tests[i].key);
       }
    }
    m_failInfo.Set(fail);
    m_log.Append(log);
 }
void ImageTest::ParseFailures (const JSONNode * data) protected
virtual void ImageTest::ParseResults (string & results) pure virtual
This must be implemented by subclass.
Implemented in SFRplusTest, SFRplusTest, BlemishTest, and BlemishTest.
Referenced by Run().
virtual void ImageTest::ParseResults (string & results) pure virtual
This must be implemented by subclass.
Implemented in SFRplusTest, SFRplusTest, BlemishTest, and BlemishTest.
bool ImageTest::Passed () inline
Referenced by COperatorConsoleApp::UpdateResults().
 {return m_passed;}
bool ImageTest::Passed () inline
 {return m_passed;}
void ImageTest::PlanesFromRGB () protected
converts from m_rawPixels to m_rgb
References m_height, m_rawPixels, m_rgb, and m_width.
Referenced by Run().
 {
    int            i, numPixels;
    unsigned char  *r, *g, *b;    // pointers into m_rgb
    unsigned char  *R, *G, *B;    // pointers into m_rawPixels
    //
    // m_rawPixels is an array of RGBQUAD structs (32-bit ints), where each byte represents one color component (r, g, b), plus
    // one unused byte.  MATLAB stores an RGB image sequentially, with all of the red values followed by all of the green values,
    // followed by all of the blue values.  This function converts an arry of RGBQUAD values into MATLAB's color plane format.
    //
    numPixels = m_width * m_height;
    r = m_rgb;
    g = r + numPixels;
    b = g + numPixels;
    R = (unsigned char *)m_rawPixels;
    G = R+1;
    B = G+1;
    // TODO, vectorize this loop?
    for (i = 0; i < numPixels; i++)
    {
       *r = *R;
       *g = *G;
       *b = *B;
       r++;
       g++;
       b++;
       R += 4;
       G += 4;
       B += 4;
    }
 }
void ImageTest::PlanesFromRGB () protected
void ImageTest::RGBFromPlanes (UINT * rgb) protected
void ImageTest::RGBFromPlanes (UINT * rgb) protected
converts from m_rgb to rgb
References m_height, m_rgb, and m_width.
Referenced by Run().
 {
    int            i, numPixels;
    unsigned char  *r, *g, *b;    // pointers into m_rgb
    unsigned char  *R, *G, *B;    // pointers into m_rawPixels
    //
    // rgb is an array of 32-bit ints, arranged in rgba order.
    // MATLAB stores an RGB image sequentally, with all of the red values followed
    // by all of the green values, followed by all of the blue values.
    //
    // This function converts from MATLAB's color plane format into rgb format
    //
    numPixels = m_width * m_height;
    r = m_rgb;
    g = r + numPixels;
    b = g + numPixels;
    R = (unsigned char *)rgb;
    G = R+1;
    B = G+1;
    for (i = 0; i < numPixels; i++)
    {
       *R = *r;
       *G = *g;
       *B = *b;
       r++;
       g++;
       b++;
       R += 4;
       G += 4;
       B += 4;
    }
 }
void ImageTest::Run () virtual
Runs the test pointed to by m_imatestFunc.
References AppendLog(), Timestamp::Get(), INI_RAW_JSON_MODE, InitResults(), m_extension, m_fileroot, m_height, m_imatestFunc, m_iniFilePathName, m_name, m_ncolors, m_partNumber, m_passed, m_programPath, m_rgb, m_serialNumber, m_timestamp, m_width, ParseResults(), PlanesFromRGB(), prepareTestSettings(), RGBFromPlanes(), SaveImage(), and SetJSON().
Referenced by Run(), and ThreadProc().
 {
    json_string    test_settings;
    int            crop_borders[4] = {0,0,0,0};
    InitResults(); // clear out strings, set m_passed to false
 //#ifdef IMATEST_CAMERA
 // RGBFromPlanes((UINT *)m_rawPixels);
 //#else
    PlanesFromRGB();              // convert m_rawPixels from rgba format to planar format for MATLAB
 //#endif
    // RGBFromPlanes((UINT *)m_rawPixels); // convert it back, just for fun
 #if 0
    //
    // Save the data as a png file
    //
    UINT *tmp = new UINT[m_width*m_height];
    RGBFromPlanes(tmp);
    SaveImage((RGBQUAD *)tmp, "image.png");
    delete [] tmp;
 #endif
    prepareTestSettings(m_width, m_height, m_ncolors, m_extension, m_fileroot, m_serialNumber, m_partNumber, crop_borders, test_settings);
    const char  *operation_flag[] = {INI_RAW_JSON_MODE};
    const char  *file_name[]      = {""};
    const char  *iniFile[]        = {m_iniFilePathName};
    const char  *program_path[]   = {m_programPath};
    const char  *input_keys[]     = {"JSON"};
    const char  *json_options[]   = {test_settings.c_str()}; // make sure to call prepareTestSettings() first
    //
    // To create mwArrays using the constructor prototype:
    // mwArray(mwSize num_strings, const char** str)
    //
    try
    {
       mwArray fileParam(1, file_name);                            // Argument 1 - File name (Not applicable for raw files)
       mwArray pathParam(1, program_path);                            // Argument 2 -   Program Path
       mwArray keysParam(1, input_keys);                              // Argument 3 - Mode of Control
       mwArray modeParam(1, operation_flag);                          // Argument 4 - Operation Flag
       mwArray iniFileParam(1, iniFile);                              // Argument 5 INI file
 //    mwArray rawFileParam(m_width * m_height, 1, mxUINT16_CLASS, mxREAL); // Argument 6 - Raw Data
       mwArray rawFileParam(m_width * m_height * 3, 1, mxUINT8_CLASS, mxREAL); // Argument 6 - RGB Data
       mwArray  json_options_param(1,json_options);                      // JSON options describing the RAW file;
       mwArray  vararginParam(1,3,mxCELL_CLASS);                      // The remaining arguments go in this param
       mwArray  out;                                            // this will hold returned data
 #ifdef IMATEST_CAMERA
       rawFileParam.SetData(m_rgb, m_width * m_height * 3);
       //rawFileParam.SetData((unsigned short *)m_rawPixels, m_width * m_height);
 #else
       rawFileParam.SetData(m_rgb, m_width * m_height * 3);
 #endif
       // Our remaining arguments go into the Varargin parameter
       vararginParam.Get(1,1).Set(iniFileParam);       // Path to INI file
       vararginParam.Get(1,2).Set(rawFileParam);       // data description
       vararginParam.Get(1,3).Set(json_options_param);    // options file
       //
       // Call the Imatest IT library function
       //
       if (m_imatestFunc == NULL)
       {
       }
       else
       {
          m_imatestFunc(1, out, fileParam, pathParam, keysParam, modeParam, vararginParam);
       }
       //
       // Copy the output of the module to a System::String object
       //
       stringstream ss (stringstream::in | stringstream::out);
       ss << out;
       string jsonResults = ss.str();
       ParseResults(jsonResults);
       SetJSON(jsonResults);   // copy results into m_jsonResults (m_jsonResults is shared between threads, so we don't want to access it directly)
    }
    catch (const mwException &e)
    {
       CString log;
       log.AppendFormat("%s Error running %s test\n%s\n", (LPCTSTR)m_timestamp.Get(), m_name, e.what());
       log.Replace("\n", "\r\n"); // the exception may have '\n' characters that we need to replace with "\r\n"
       AppendLog(log);
       m_passed = false;
    }
 }
virtual void ImageTest::Run () virtual
virtual void ImageTest::Run (void * raw_pixels, int width, int height, const Config * config) virtual
void ImageTest::Run (void * raw_pixels, int width, int height, const Config * config) virtual
References Init(), and Run().
 {
    Init(raw_pixels, width, height, config);
    Run();
 }
void ImageTest::SaveImage (RGBQUAD * buf, const char * filename) protected
References m_height, and m_width.
Referenced by Run().
 {
    CImage      image;
    HDC         hdc;
    HBITMAP     hbitmap;
    BITMAPINFO  info;
    memset(&info, 0, sizeof(info));
    info.bmiHeader.biSize          = sizeof(info.bmiHeader);
    info.bmiHeader.biWidth         = m_width;
    info.bmiHeader.biHeight        = -m_height;  // a negative value means top-down instead of bottom-up
    info.bmiHeader.biPlanes        = 1;
    info.bmiHeader.biBitCount      = 32;
    info.bmiHeader.biCompression   = BI_RGB;
    info.bmiHeader.biSizeImage     = 0;
    info.bmiHeader.biXPelsPerMeter = 1;
    info.bmiHeader.biYPelsPerMeter = 1;
    info.bmiHeader.biClrUsed       = 0;
    info.bmiHeader.biClrImportant  = 0;
    image.Create(m_width, m_height, 32);
    hdc = image.GetDC();
    hbitmap = (HBITMAP)image;
    SetDIBits(hdc, hbitmap, 0, m_height, buf, &info, DIB_RGB_COLORS);
    image.ReleaseDC();
    image.Save(filename, Gdiplus::ImageFormatPNG);
 }
void ImageTest::SaveImage (RGBQUAD * buf, const char * filename) protected
void ImageTest::SetBuffer (void * buf) inline
 {m_rawPixels = buf;}
void ImageTest::SetBuffer (void * buf) inline
 {m_rawPixels = buf;}
void ImageTest::SetJSON (string & src) inline protected
Referenced by Run().
 {m_jsonResults.Set(src);}
void ImageTest::SetJSON (string & src) inline protected
 {m_jsonResults.Set(src);}
void ImageTest::SetSummary (CString & src) inline protected
 {m_summary.Set(src);}
void ImageTest::SetSummary (CString & src) inline protected
 {m_summary.Set(src);}
static UINT __cdecl ImageTest::ThreadProc (void * param) static
param must be a pointer to a ThreadControl object; param->m_data must point to an ImageTest object
UINT __cdecl ImageTest::ThreadProc (void * param) static
param must be a pointer to a ThreadControl object; param->m_data must point to an ImageTest object
References DONE_INDEX, Timer::Get(), ThreadControl::m_data, m_elapsed, m_elapsedStr, ThreadControl::m_events, ThreadControl::m_parentID, ThreadControl::m_threadMsg, m_time, NUM_THREAD_EVENTS, Run(), RUN_INDEX, Timer::Start(), and Timer::Stop().
Referenced by COperatorConsoleApp::InitBlemishThread(), and COperatorConsoleApp::InitSFRplusThread().
 {
    ThreadControl  *info = (ThreadControl *)param;
    ImageTest      *test = (ImageTest *)info->m_data;
    bool        done  = false;
    DWORD       eventIndex;
    while (!done)
    {
       //
       // Wait for an event to be signaled.  info->m_events is an array of 2 CEvent structs.
       // 'eventIndex' tells us which event was signaled.  Once we know which event was signaled
       // we can take the appropriate action.
       //
       // While we're waiting for an event, our thread blocks, allowing other threads (like the
       // GUI handler) to run.
       //
       eventIndex = ::WaitForMultipleObjects(NUM_THREAD_EVENTS, info->m_events, FALSE, INFINITE);   // wait for an event to be signaled
       if (eventIndex == DONE_INDEX)
       {
          //
          // We get a DONE event when the program is terminating.  We just exit the loop and return.
          //
          done = TRUE;
       }
       else if (eventIndex == RUN_INDEX)
       {
          //
          // We get a RUN event when it's time to run the test.  We send a
          // message to the main application thread when the test is done.
          //
          test->m_time.Start();
          test->Run();
          test->m_time.Stop();
          test->m_time.Get(&test->m_elapsedStr);
          test->m_time.Get(&test->m_elapsed);
          ::PostThreadMessage(info->m_parentID, info->m_threadMsg, (WPARAM)0, (LPARAM)0);
       }
    }
    return 0;   // this terminates the thread
 }
Member Data Documentation
long long ImageTest::m_elapsed
Referenced by ThreadProc(), and COperatorConsoleApp::UpdateResults().
CString ImageTest::m_elapsedStr
Referenced by ThreadProc(), and COperatorConsoleApp::UpdateResults().
const char * ImageTest::m_extension
Referenced by ImageTest(), Init(), and Run().
CriticalCString ImageTest::m_failInfo protected
reasons that image failed the test
Referenced by InitResults(), and ParseFailures().
const char * ImageTest::m_fileroot
Referenced by ImageTest(), Init(), and Run().
int ImageTest::m_height
Referenced by AllocateRGB(), ImageTest(), Init(), PlanesFromRGB(), RGBFromPlanes(), Run(), and SaveImage().
ImatestShellFunc ImageTest::m_imatestFunc protected
Referenced by ImageTest(), and Run().
const char * ImageTest::m_iniFilePathName
Referenced by ImageTest(), Init(), COperatorConsoleApp::OnSetup(), and Run().
CriticalCString ImageTest::m_jsonResults protected
the full results of the test in JSON format
Referenced by InitResults().
CriticalCString ImageTest::m_log protected
log message(s)
Referenced by GetDataNode(), GetPassFailNode(), GetString(), InitResults(), and ParseFailures().
const char * ImageTest::m_name
Referenced by ImageTest(), Run(), and COperatorConsoleApp::UpdateResults().
int ImageTest::m_ncolors
Referenced by AllocateRGB(), Init(), and Run().
int ImageTest::m_numTests protected
Referenced by ParseFailures().
const char * ImageTest::m_partNumber
Referenced by ImageTest(), Init(), COperatorConsoleApp::OnSetup(), and Run().
bool ImageTest::m_passed protected
Referenced by InitResults(), and Run().
const char * ImageTest::m_programPath
Referenced by ImageTest(), Init(), COperatorConsoleApp::OnSetup(), and Run().
const void * ImageTest::m_rawPixels protected
Referenced by ImageTest(), Init(), and PlanesFromRGB().
unsigned char * ImageTest::m_rgb protected
Referenced by AllocateRGB(), DeleteRGB(), ImageTest(), PlanesFromRGB(), RGBFromPlanes(), and Run().
const char * ImageTest::m_serialNumber
Referenced by ImageTest(), Init(), COperatorConsoleApp::OnSetup(), and Run().
CriticalCString ImageTest::m_summary protected
the summary results of the test (these get displayed in the dialog)
Referenced by InitResults().
const TestID * ImageTest::m_tests protected
Referenced by ParseFailures().
Timer ImageTest::m_time protected
Referenced by ThreadProc().
Timestamp ImageTest::m_timestamp
Referenced by GetDataNode(), GetPassFailNode(), GetString(), and Run().
int ImageTest::m_width
Referenced by AllocateRGB(), ImageTest(), Init(), PlanesFromRGB(), RGBFromPlanes(), Run(), and SaveImage().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/ImageTest.h
ImageTest.h
Documentation/Operator-Console/ImageTest.cpp
ImageTest.cpp