Operator Console: JSONSingleton< T > Class Template Reference
JSONSingleton< T > Class Template Reference
#include <JSONSingleton.h>
Static Public Member Functions
static T get (void)
static void set (T p)
static T get (void)
static void set (T p)
Private Member Functions
JSONSingleton ()
JSONSingleton (const JSONSingleton< T > &)
JSONSingleton< T > operator= (const JSONSingleton< T > &)
JSONSingleton ()
JSONSingleton (const JSONSingleton< T > &)
JSONSingleton< T > operator= (const JSONSingleton< T > &)
Static Private Member Functions
static JSONSingleton< T > * get_singleton (void)
static JSONSingleton< T > * get_singleton (void)
Private Attributes
T ptr
Constructor & Destructor Documentation
template<typename T> JSONSingleton< T >::JSONSingleton () inline private
 : ptr(NULL) { }
template<typename T> JSONSingleton< T >::JSONSingleton (const JSONSingleton< T > &) private
template<typename T> JSONSingleton< T >::JSONSingleton () inline private
 : ptr(NULL) { }
template<typename T> JSONSingleton< T >::JSONSingleton (const JSONSingleton< T > &) private
Member Function Documentation
template<typename T> static T JSONSingleton< T >::get (void) inline static
References JSONSingleton< T >::get_singleton(), and JSONSingleton< T >::ptr.
{
       return get_singleton() -> ptr;
    }
template<typename T> static T JSONSingleton< T >::get (void) inline static
References JSONSingleton< T >::get_singleton(), and JSONSingleton< T >::ptr.
{
       return get_singleton() -> ptr;
    }
template<typename T> static JSONSingleton<T>* JSONSingleton< T >::get_singleton (void) inline static private
{
       static JSONSingleton<T> instance;
       return &instance;
    }
template<typename T> static JSONSingleton<T>* JSONSingleton< T >::get_singleton (void) inline static private
Referenced by JSONSingleton< T >::get(), and JSONSingleton< T >::set().
{
       static JSONSingleton<T> instance;
       return &instance;
    }
template<typename T> JSONSingleton<T> JSONSingleton< T >::operator= (const JSONSingleton< T > &) private
template<typename T> JSONSingleton<T> JSONSingleton< T >::operator= (const JSONSingleton< T > &) private
template<typename T> static void JSONSingleton< T >::set (T p) inline static
References JSONSingleton< T >::get_singleton(), and JSONSingleton< T >::ptr.
{
       get_singleton() -> ptr = p;
    }
template<typename T> static void JSONSingleton< T >::set (T p) inline static
References JSONSingleton< T >::get_singleton(), and JSONSingleton< T >::ptr.
{
       get_singleton() -> ptr = p;
    }
Member Data Documentation
template<typename T> T JSONSingleton< T >::ptr private
Referenced by JSONSingleton< T >::get(), and JSONSingleton< T >::set().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/JSON/JSONSingleton.h
JSON/JSONSingleton.h