Operator Console: Timer Class Reference
Timer Class Reference
a timer class for getting the elapsed time between events
#include <Timer.h>
Public Member Functions
Timer (void)
virtual ~Timer (void)
void Start ()
void Stop ()
void Get (long long *ms)
gets the elapsed time in milliseconds
void Get (double *sec)
gets the elapsed time in seconds
void Get (CString *str)
gets the elapsed time in a formatted string
Timer (void)
virtual ~Timer (void)
void Start ()
void Stop ()
void Get (long long *ms)
void Get (double *sec)
void Get (CString *str)
Protected Member Functions
void Elapsed ()
calculates elapsed time in milliseconds
void Elapsed ()
Protected Attributes
struct _timeb m_start
struct _timeb m_stop
long long m_elapsed
elapsed time in ms
Detailed Description
a timer class for getting the elapsed time between events
Constructor & Destructor Documentation
Timer::Timer (void)
References m_elapsed, m_start, and m_stop.
 {
    memset(&m_start, 0, sizeof(m_start));
    memset(&m_stop, 0, sizeof(m_stop));
    m_elapsed = 0;
 }
Timer::~Timer (void) virtual
 {
 }
Timer::Timer (void)
virtual Timer::~Timer (void) virtual
Member Function Documentation
void Timer::Elapsed () protected
calculates elapsed time in milliseconds
References m_elapsed, m_start, and m_stop.
Referenced by Stop().
 {
    long long   start = (m_start.time * 1000)  + m_start.millitm;
    long long   stop  = (m_stop.time * 1000)   + m_stop.millitm;
    m_elapsed = stop - start;
 }
void Timer::Elapsed () protected
void Timer::Get (long long * ms)
void Timer::Get (long long * ms)
gets the elapsed time in milliseconds
References m_elapsed.
Referenced by ImageTest::ThreadProc().
 {
    if (ms != NULL)
    {
       *ms = m_elapsed;
    }
 }
void Timer::Get (double * sec)
gets the elapsed time in seconds
References m_elapsed.
 {
    if (sec != NULL)
    {
       *sec = (double)m_elapsed / 1000.;
    }
 }
void Timer::Get (double * sec)
void Timer::Get (CString * str)
void Timer::Get (CString * str)
gets the elapsed time in a formatted string
References m_elapsed.
 {
    if (str != NULL)
    {
       str->Format("%lu.%03u", (unsigned long)(m_elapsed / 1000), (unsigned)(m_elapsed % 1000));
    }
 }
void Timer::Start ()
void Timer::Start ()
References m_start.
Referenced by ImageTest::ThreadProc().
 {
    _ftime_s(&m_start);
 }
void Timer::Stop ()
void Timer::Stop ()
References Elapsed(), and m_stop.
Referenced by ImageTest::ThreadProc().
 {
    _ftime_s(&m_stop);
    Elapsed();
 }
Member Data Documentation
long long Timer::m_elapsed protected
elapsed time in ms
Referenced by Elapsed(), Get(), and Timer().
struct _timeb Timer::m_start protected
Referenced by Elapsed(), Start(), and Timer().
struct _timeb Timer::m_stop protected
Referenced by Elapsed(), Stop(), and Timer().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/Timer.h
Timer.h
Documentation/Operator-Console/Timer.cpp
Timer.cpp