Operator Console: ModelessDialogThread Class Reference
ModelessDialogThread Class Reference
a thread class for creating modeless dialogs which can operate without halting the main dialog
#include <ModelessDialogThread.h>
Public Member Functions
ModelessDialogThread ()
virtual ~ModelessDialogThread ()
void SetText (LPCTSTR text)
void SetTitle (LPCTSTR title)
void Show (bool show)
BOOL InitInstance ()
int ExitInstance ()
ModelessDialogThread ()
virtual ~ModelessDialogThread ()
void SetText (LPCTSTR text)
void SetTitle (LPCTSTR title)
void Show (bool show)
BOOL InitInstance ()
int ExitInstance ()
Protected Member Functions
void OnModelessQuit (WPARAM wParam, LPARAM lParam)
void OnModelessQuit (WPARAM wParam, LPARAM lParam)
Protected Attributes
TextDlg * m_dialog
Detailed Description
a thread class for creating modeless dialogs which can operate without halting the main dialog
Constructor & Destructor Documentation
ModelessDialogThread::ModelessDialogThread ()
References m_dialog.
 {
    m_dialog = NULL;
 }
ModelessDialogThread::~ModelessDialogThread () virtual
 {
 }
ModelessDialogThread::ModelessDialogThread ()
virtual ModelessDialogThread::~ModelessDialogThread () virtual
Member Function Documentation
int ModelessDialogThread::ExitInstance ()
References m_dialog.
 {
    if (m_dialog != NULL)
    {
       delete m_dialog;
    }
    return CWinThread::ExitInstance();
 }
int ModelessDialogThread::ExitInstance ()
BOOL ModelessDialogThread::InitInstance ()
BOOL ModelessDialogThread::InitInstance ()
References m_dialog.
 {
    CWinThread::InitInstance();
    m_dialog   = new TextDlg;
    m_pMainWnd = m_dialog;
    return TRUE;
 }
void ModelessDialogThread::OnModelessQuit (WPARAM wParam, LPARAM lParam) protected
void ModelessDialogThread::OnModelessQuit (WPARAM wParam, LPARAM lParam) protected
 {
    PostQuitMessage(0);
 }
void ModelessDialogThread::SetText (LPCTSTR text)
void ModelessDialogThread::SetText (LPCTSTR text)
References m_dialog, and TextDlg::SetText().
Referenced by COperatorConsoleApp::OnShowJSON().
 {
    if (m_dialog != NULL)
    {
       m_dialog->SetText(text);
    }
 }
void ModelessDialogThread::SetTitle (LPCTSTR title)
void ModelessDialogThread::SetTitle (LPCTSTR title)
References m_dialog, and TextDlg::SetTitle().
Referenced by COperatorConsoleApp::OnShowJSON().
 {
    if (m_dialog != NULL)
    {
       m_dialog->SetTitle(title);
    }
 }
void ModelessDialogThread::Show (bool show)
References m_dialog, and TextDlg::Show().
Referenced by COperatorConsoleApp::OnShowJSON().
 {
    if (m_dialog != NULL)
    {
       m_dialog->Show(show);
    }
 }
void ModelessDialogThread::Show (bool show)
Member Data Documentation
TextDlg * ModelessDialogThread::m_dialog protected
Referenced by ExitInstance(), InitInstance(), SetText(), SetTitle(), and Show().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/ModelessDialogThread.h
Documentation/Operator-Console/ModelessDialogThread.cpp