Operator Console: libjson Namespace Reference
libjson Namespace Reference
Functions
static json_string encode64 (const unsigned char *binary, size_t bytes) json_nothrow
static std::string decode64 (const json_string &encoded) json_nothrow
static json_string strip_white_space (const json_string &json) json_nothrow
static std::string to_std_string (const json_string &str)
static std::wstring to_std_wstring (const json_string &str)
static json_string to_json_string (const std::string &str)
static json_string to_json_string (const std::wstring &str)
static JSONNode parse (const json_string &json) json_throws(std
static JSONNode parse_unformatted (const json_string &json) json_throws(std
static bool is_valid (const json_string &json) json_nothrow
static bool is_valid_unformatted (const json_string &json) json_nothrow
static JSONNode json_deprecated (validate(const json_string &json),"libjson::validate is deprecated, use libjson::is_valid and libjson::parse instead")
static json_string encode64 (const unsigned char *binary, size_t bytes) json_nothrow
static std::string decode64 (const json_string &encoded) json_nothrow
static json_string strip_white_space (const json_string &json) json_nothrow
static std::string to_std_string (const json_string &str)
static std::wstring to_std_wstring (const json_string &str)
static json_string to_json_string (const std::string &str)
static json_string to_json_string (const std::wstring &str)
static JSONNode parse (const json_string &json) json_throws(std
static JSONNode parse_unformatted (const json_string &json) json_throws(std
static bool is_valid (const json_string &json) json_nothrow
static bool is_valid_unformatted (const json_string &json) json_nothrow
static JSONNode json_deprecated (validate(const json_string &json),"libjson::validate is deprecated, use libjson::is_valid and libjson::parse instead")
Function Documentation
static std::string libjson::decode64 (const json_string & encoded) inline static
References JSONBase64::json_decode64().
{
           return JSONBase64::json_decode64(encoded);
         }
static std::string libjson::decode64 (const json_string & encoded) inline static
References JSONBase64::json_decode64().
{
           return JSONBase64::json_decode64(encoded);
         }
static json_string libjson::encode64 (const unsigned char * binary, size_t bytes) inline static
References JSONBase64::json_encode64().
{
           return JSONBase64::json_encode64(binary, bytes);
         }
static json_string libjson::encode64 (const unsigned char * binary, size_t bytes) inline static
References JSONBase64::json_encode64().
{
           return JSONBase64::json_encode64(binary, bytes);
         }
static bool libjson::is_valid (const json_string & json) inline static
References JSONValidator::isValidRoot(), JSON_FAIL, JSON_SECURITY_MAX_STRING_LENGTH, JSON_TEXT, json_unlikely, and JSONWorker::RemoveWhiteSpaceAndComments().
{
             #ifdef JSON_SECURITY_MAX_STRING_LENGTH
                 if (json_unlikely(json.length() > JSON_SECURITY_MAX_STRING_LENGTH)){
                   JSON_FAIL(JSON_TEXT("Exceeding JSON_SECURITY_MAX_STRING_LENGTH"));
                   return false;
                 }
             #endif
             return JSONValidator::isValidRoot(JSONWorker::RemoveWhiteSpaceAndComments(json, false).c_str());
           }
static bool libjson::is_valid (const json_string & json) inline static
References JSONValidator::isValidRoot(), JSON_FAIL, JSON_SECURITY_MAX_STRING_LENGTH, JSON_TEXT, json_unlikely, and JSONWorker::RemoveWhiteSpaceAndComments().
{
             #ifdef JSON_SECURITY_MAX_STRING_LENGTH
                 if (json_unlikely(json.length() > JSON_SECURITY_MAX_STRING_LENGTH)){
                   JSON_FAIL(JSON_TEXT("Exceeding JSON_SECURITY_MAX_STRING_LENGTH"));
                   return false;
                 }
             #endif
             return JSONValidator::isValidRoot(JSONWorker::RemoveWhiteSpaceAndComments(json, false).c_str());
           }
static bool libjson::is_valid_unformatted (const json_string & json) inline static
References JSONValidator::isValidRoot(), JSON_FAIL, JSON_SECURITY_MAX_STRING_LENGTH, JSON_TEXT, and json_unlikely.
{
             #ifdef JSON_SECURITY_MAX_STRING_LENGTH
                 if (json_unlikely(json.length() > JSON_SECURITY_MAX_STRING_LENGTH)){
                   JSON_FAIL(JSON_TEXT("Exceeding JSON_SECURITY_MAX_STRING_LENGTH"));
                   return false;
                 }
             #endif
             return JSONValidator::isValidRoot(json.c_str());
           }
static bool libjson::is_valid_unformatted (const json_string & json) inline static
References JSONValidator::isValidRoot(), JSON_FAIL, JSON_SECURITY_MAX_STRING_LENGTH, JSON_TEXT, and json_unlikely.
{
             #ifdef JSON_SECURITY_MAX_STRING_LENGTH
                 if (json_unlikely(json.length() > JSON_SECURITY_MAX_STRING_LENGTH)){
                   JSON_FAIL(JSON_TEXT("Exceeding JSON_SECURITY_MAX_STRING_LENGTH"));
                   return false;
                 }
             #endif
             return JSONValidator::isValidRoot(json.c_str());
           }
static JSONNode libjson::json_deprecated (validate(const json_string &json) , "libjson::validate is deprecated, use libjson::is_valid and libjson::parse instead") inline static
static JSONNode libjson::json_deprecated (validate(const json_string &json) , "libjson::validate is deprecated, use libjson::is_valid and libjson::parse instead") inline static
static JSONNode libjson::parse (const json_string & json) inline static
References json_char, json_auto< T >::ptr, and JSONWorker::RemoveWhiteSpace.
Referenced by ImageTest::GetDataNode(), JSONStream::operator<<(), JSONStream::parse(), and parse().
{
           #ifdef JSON_PREPARSE
             #if defined JSON_DEBUG || defined JSON_SAFE
                json_char temp;
                json_auto<json_char> buffer(JSONWorker::RemoveWhiteSpace(json, temp, false));
             #else
                json_auto<json_char> buffer(JSONWorker::RemoveWhiteSpace(json, false));
             #endif
             return JSONPreparse::isValidRoot(buffer.ptr);
           #else
             return JSONWorker::parse(json);
           #endif
         }
static JSONNode libjson::parse (const json_string & json) inline static
References json_char, parse(), json_auto< T >::ptr, and JSONWorker::RemoveWhiteSpace.
{
           #ifdef JSON_PREPARSE
             #if defined JSON_DEBUG || defined JSON_SAFE
                json_char temp;
                json_auto<json_char> buffer(JSONWorker::RemoveWhiteSpace(json, temp, false));
             #else
                json_auto<json_char> buffer(JSONWorker::RemoveWhiteSpace(json, false));
             #endif
             return JSONPreparse::isValidRoot(buffer.ptr);
           #else
             return JSONWorker::parse(json);
           #endif
         }
static JSONNode libjson::parse_unformatted (const json_string & json) inline static
Referenced by parse_unformatted().
{
           #ifdef JSON_PREPARSE
             return JSONPreparse::isValidRoot(json);
           #else
             return JSONWorker::parse_unformatted(json);
           #endif
         }
static JSONNode libjson::parse_unformatted (const json_string & json) inline static
References parse_unformatted().
{
           #ifdef JSON_PREPARSE
             return JSONPreparse::isValidRoot(json);
           #else
             return JSONWorker::parse_unformatted(json);
           #endif
         }
static json_string libjson::strip_white_space (const json_string & json) inline static
References JSONWorker::RemoveWhiteSpaceAndComments().
{
         return JSONWorker::RemoveWhiteSpaceAndComments(json, false);
       }
static json_string libjson::strip_white_space (const json_string & json) inline static
References JSONWorker::RemoveWhiteSpaceAndComments().
{
         return JSONWorker::RemoveWhiteSpaceAndComments(json, false);
       }
static json_string libjson::to_json_string (const std::string & str) inline static
{
             #if defined(JSON_UNICODE) ||defined(JSON_MEMORY_CALLBACKS) || defined(JSON_MEMORY_POOL)
                return json_string(str.begin(), str.end());
             #else
                return str;
             #endif
          }
static json_string libjson::to_json_string (const std::string & str) inline static
{
             #if defined(JSON_UNICODE) ||defined(JSON_MEMORY_CALLBACKS) || defined(JSON_MEMORY_POOL)
                return json_string(str.begin(), str.end());
             #else
                return str;
             #endif
          }
static json_string libjson::to_json_string (const std::wstring & str) inline static
{
             #if (!defined(JSON_UNICODE)) || defined(JSON_MEMORY_CALLBACKS) || defined(JSON_MEMORY_POOL)
                return json_string(str.begin(), str.end());
             #else
                return str;
             #endif
          }
static json_string libjson::to_json_string (const std::wstring & str) inline static
{
             #if (!defined(JSON_UNICODE)) || defined(JSON_MEMORY_CALLBACKS) || defined(JSON_MEMORY_POOL)
                return json_string(str.begin(), str.end());
             #else
                return str;
             #endif
          }
static std::string libjson::to_std_string (const json_string & str) inline static
{
             #if defined(JSON_UNICODE) ||defined(JSON_MEMORY_CALLBACKS) || defined(JSON_MEMORY_POOL)
                return std::string(str.begin(), str.end());
             #else
                return str;
             #endif
          }
static std::string libjson::to_std_string (const json_string & str) inline static
{
             #if defined(JSON_UNICODE) ||defined(JSON_MEMORY_CALLBACKS) || defined(JSON_MEMORY_POOL)
                return std::string(str.begin(), str.end());
             #else
                return str;
             #endif
          }
static std::wstring libjson::to_std_wstring (const json_string & str) inline static
{
             #if (!defined(JSON_UNICODE)) || defined(JSON_MEMORY_CALLBACKS) || defined(JSON_MEMORY_POOL)
                return std::wstring(str.begin(), str.end());
             #else
                return str;
             #endif
          }
static std::wstring libjson::to_std_wstring (const json_string & str) inline static
{
             #if (!defined(JSON_UNICODE)) || defined(JSON_MEMORY_CALLBACKS) || defined(JSON_MEMORY_POOL)
                return std::wstring(str.begin(), str.end());
             #else
                return str;
             #endif
          }