Operator Console: ResizeDlg Class Reference
ResizeDlg Class Reference
A class that resizes and centers dialog objects within a parent window.
#include <ResizeDlg.h>
Public Member Functions
ResizeDlg (void)
virtual ~ResizeDlg (void)
void GetImageWindowDelta (int width, int height)
Calculates the differences in window height and width between the current and new sizes.
void OffsetWindowSize (CWnd *wnd, int dx, int dy)
Changes the window size.
void OffsetWindowPos (CWnd *parent, CWnd *wnd, int dx, int dy)
Changes the window position.
void Resize (CWnd *dialog, CWnd *window, int width, int height)
Resizes an object within a parent window but does not allow the object to shrink vertically.
void BidirectionalResize (CWnd *dialog, CWnd *window, int width, int height)
Resizes an object within a parent window that allows the object to shrink vertically, but not below a minimum size.
ResizeDlg (void)
virtual ~ResizeDlg (void)
void GetImageWindowDelta (int width, int height)
void OffsetWindowSize (CWnd *wnd, int dx, int dy)
void OffsetWindowPos (CWnd *parent, CWnd *wnd, int dx, int dy)
void Resize (CWnd *dialog, CWnd *window, int width, int height)
void BidirectionalResize (CWnd *dialog, CWnd *window, int width, int height)
Static Public Member Functions
static void CenterWindow (CWnd *parent, CWnd *wnd, bool horizontal=true, bool vertical=true)
A function that centers an object with respect to the parent with the option to select only vertical or horizontal centering.
static void GetWindowCenter (CWnd *wnd, CRect *bnds, CPoint *center)
static void GetWindowSize (CWnd *wnd, int *width, int *height, CRect *bnds=NULL, bool client=false)
A function that acquires either the window or client size.
static BOOL CALLBACK OffsetChildPos (HWND hwnd, LPARAM lParam)
static void CenterWindow (CWnd *parent, CWnd *wnd, bool horizontal=true, bool vertical=true)
static void GetWindowCenter (CWnd *wnd, CRect *bnds, CPoint *center)
static void GetWindowSize (CWnd *wnd, int *width, int *height, CRect *bnds=NULL, bool client=false)
static BOOL CALLBACK OffsetChildPos (HWND hwnd, LPARAM lParam)
Protected Attributes
CSize m_delta
CWnd * m_dialog
CWnd * m_window
Detailed Description
A class that resizes and centers dialog objects within a parent window.
Constructor & Destructor Documentation
ResizeDlg::ResizeDlg (void)
 {
 }
ResizeDlg::~ResizeDlg (void) virtual
 {
 }
ResizeDlg::ResizeDlg (void)
virtual ResizeDlg::~ResizeDlg (void) virtual
Member Function Documentation
void ResizeDlg::BidirectionalResize (CWnd * dialog, CWnd * window, int width, int height)
Resizes an object within a parent window that allows the object to shrink vertically, but not below a minimum size.
Parameters
*dialog pointer to the parent window
*window pointer to the object to be resized
width the new width in pixels
height the new height in pixels
References CenterWindow(), MoveData::delta, MoveData::dialog, GetImageWindowDelta(), GetWindowSize(), m_delta, m_dialog, m_window, OffsetChildPos(), OffsetWindowSize(), and MoveData::skip.
Referenced by COperatorConsoleDlg::ReInitDialog().
 {
    MoveData data;
    int         dy;
    int   clientWidth,  clientHeight;
    int screenWidth, screenHeight;
    m_dialog = dialog;
    m_window = window;
    GetWindowSize(dialog, &clientWidth, &clientHeight,NULL,true);
    GetWindowSize(dialog, &screenWidth, &screenHeight);
    //
    // Get the difference in size between the window an the desired width and height
    //
    GetImageWindowDelta(width, height);
    if (m_delta.cx != 0 || m_delta.cy != 0)
    {
       //
       // Resize the window
       //
       OffsetWindowSize(window, m_delta.cx, m_delta.cy);
       if (m_delta.cx < -16)
          m_delta.cx += 16;
       //
       // Resize the dialog.  It can grow or shrink in x uncontrolled, but
       // its height may not be less than a minimum value. Also, if we need to
       // resize, it shouldn't make the window needlessly large.
       //
       int border = 16;
       int min_window_size = 660;
       if ( m_delta.cy >= 0) // only change size if needed
       {
          if (clientHeight < height)
          {
             dy = height - clientHeight+border;
          }
          else
          {
             dy = 0;
          }
       }
       else if ( clientHeight + m_delta.cy> min_window_size) // allow window to shrink if it won't go below minimum size
       {
          dy = m_delta.cy;
       }
       else
       {
          dy = min_window_size - screenHeight+(screenHeight - clientHeight);   // shrink size to minimum size + width of the
       }                                                     // screen border (screenHeight - clientHeight)
       OffsetWindowSize(dialog, m_delta.cx, dy);
       //
       // Center the window vertically in the dialog
       //
       CenterWindow(dialog, window, false, true);
       //
       // Move the rest of the items dx pixels to the left or right.  We're not
       // going to change the y coordinates, so we set m_delta.cy to 0.
       //
       m_delta.cy = 0;
       //
       // Move all of the dialog items to compensate for the new size of 'window'.  EnumChildWindows()
       // will call OffsetChildPos() for each of the Dialog's child windows (i.e. all dialog items).
       // We want to move every item except for the image item.
       //
       data.delta  = &m_delta;
       data.skip   = window->m_hWnd; // we don't want to move 'window'
       data.dialog = dialog->m_hWnd; // handle to the dialog window (we need this for converting coordinates)
       ::EnumChildWindows(dialog->m_hWnd, OffsetChildPos, (LPARAM)&data);
    }
 }
void ResizeDlg::BidirectionalResize (CWnd * dialog, CWnd * window, int width, int height)
void ResizeDlg::CenterWindow (CWnd * parent, CWnd * wnd, bool horizontal = true, bool vertical = true) static
A function that centers an object with respect to the parent with the option to select only vertical or horizontal centering.
Parameters
*parent pointer to the parent window
*wnd pointer to the object to be centered
horizontal set to TRUE if horizontal centering is desired
vertical set to TRUE if vertical centering is desired
Referenced by BidirectionalResize(), and Resize().
 {
    if (wnd != NULL)
    {
       CRect r, rect, client;
       CPoint   ul;
       int      width, height, w, h;
       //
       // Get the width, height, and screen coordinates of the windows
       //
       GetWindowSize(parent, &w,     &h,      &r, true);  // r = client rect of parent
       GetWindowSize(wnd,    &width, &height, &rect,false);     // rect is in screen coordinates
       //
       // Convert the upper left coordinate of wnd to local coordinates (relative to parent)
       //
       ul.x = rect.left;
       ul.y = rect.top;
       parent->ScreenToClient(&ul);
       if (horizontal)
       {
          ul.x = (w - width)  / 2;   // local coordinate
       }
       if (vertical)
       {
          ul.y = (h - height) / 2;   // local coordinate
       }
       //
       // For some reason the x and y coordinates are off by a factor of 2, so I'm adjusting here.
       // I don't know why that is, but I did a screen capture and measured the window positions
       // in a paint program, and they were twice as much as they should have been.
       //
       if (horizontal)
       {
          ul.x /= 2;
       }
       if (vertical)
       {
          ul.y /= 2;
       }
       wnd->MoveWindow(ul.x, ul.y, width, height,true);
       //wnd->SetWindowPos(NULL, ul.x, ul.y, width, height, SWP_NOSIZE|SWP_NOZORDER);
    }
 }
static void ResizeDlg::CenterWindow (CWnd * parent, CWnd * wnd, bool horizontal = true, bool vertical = true) static
void ResizeDlg::GetImageWindowDelta (int width, int height)
Calculates the differences in window height and width between the current and new sizes.
References GetWindowSize(), m_delta, and m_window.
Referenced by BidirectionalResize(), and Resize().
 {
    int   itemWidth,  itemHeight;
    //
    // Get the current width and height of the image dialog item
    //
    GetWindowSize(m_window, &itemWidth, &itemHeight);
    //
    // Get the difference in the width and height.
    // This is how much the sizes of the image item and dialog need to be increased.
    // This is also how much we need to move the other dialog items to accommodate the new image size.
    //
    m_delta.cx = width  - itemWidth;
    m_delta.cy = height - itemHeight;
 }
void ResizeDlg::GetImageWindowDelta (int width, int height)
void ResizeDlg::GetWindowCenter (CWnd * wnd, CRect * bnds, CPoint * center) static
 {
    if (wnd != NULL && center != NULL)
    {
       CRect rect;
       CRect *r = (bnds != NULL) ? bnds : &rect;
       wnd->GetWindowRect(r);
       *center = r->CenterPoint();
    }
 }
static void ResizeDlg::GetWindowCenter (CWnd * wnd, CRect * bnds, CPoint * center) static
void ResizeDlg::GetWindowSize (CWnd * wnd, int * width, int * height, CRect * bnds = NULL, bool client = false) static
A function that acquires either the window or client size.
Note that the client size does not include the window border, whereas the window size does.
Parameters
*wnd the window
*width pointer to an int into which the width is stored
*height pointer to an int into which the height is stored
*bnds [OPTIONAL] a CRect to store the window dimensions; supply NULL if not desired
client Supply TRUE if the client size is desired, FALSE if the window size is desired
Referenced by BidirectionalResize(), GetImageWindowDelta(), OffsetWindowSize(), and COperatorConsoleDlg::QsoMove().
 {
    if (wnd != NULL)
    {
       CRect rect;
       CRect *r = (bnds == NULL) ? &rect : bnds;
       if (client)
       {
          wnd->GetClientRect(r);
       }
       else
       {
          wnd->GetWindowRect(r);
       }
       if (width != NULL)
       {
          *width  = r->Width();
       }
       if (height != NULL)
       {
          *height = r->Height();
       }
    }
 }
static void ResizeDlg::GetWindowSize (CWnd * wnd, int * width, int * height, CRect * bnds = NULL, bool client = false) static
static BOOL CALLBACK ResizeDlg::OffsetChildPos (HWND hwnd, LPARAM lParam) static
BOOL CALLBACK ResizeDlg::OffsetChildPos (HWND hwnd, LPARAM lParam) static
References MoveData::delta, MoveData::dialog, height, MoveData::skip, and width.
Referenced by BidirectionalResize(), and Resize().
 {
    MoveData *data = (MoveData *)lParam;
    RECT  rect;
    int      width, height;
    POINT ul;
    if (hwnd != data->skip)
    {
       ::GetWindowRect(hwnd, &rect); // rect is in screen coordinates
       ul.x = rect.left;
       ul.y = rect.top;
       ::ScreenToClient(data->dialog, &ul);   // make ul coordinates relative to dialog
       width  = rect.right  - rect.left;
       height = rect.bottom - rect.top;
       ::MoveWindow(hwnd, ul.x + data->delta->cx, ul.y + data->delta->cy, width, height, TRUE);
    }
    return TRUE;
 }
void ResizeDlg::OffsetWindowPos (CWnd * parent, CWnd * wnd, int dx, int dy)
void ResizeDlg::OffsetWindowPos (CWnd * parent, CWnd * wnd, int dx, int dy)
Changes the window position.
 {
    if (wnd != NULL)
    {
       CRect rect;
       wnd->GetWindowRect(&rect);       // current window location in screen coordinates
       parent->ScreenToClient(&rect);      // current location in client coordinates (relative to client rect of parent)
       rect.OffsetRect(dx, dy);         // offset the rect by (dx, dy)
       wnd->MoveWindow(&rect, TRUE);    // move the window
    }
 }
void ResizeDlg::OffsetWindowSize (CWnd * wnd, int dx, int dy)
Changes the window size.
References GetWindowSize(), height, and width.
Referenced by BidirectionalResize(), and Resize().
 {
    int width, height;
    GetWindowSize(wnd, &width, &height);
    wnd->SetWindowPos(NULL, 0, 0, width + dx, height + dy, SWP_NOMOVE | SWP_NOZORDER);
 }
void ResizeDlg::OffsetWindowSize (CWnd * wnd, int dx, int dy)
void ResizeDlg::Resize (CWnd * dialog, CWnd * window, int width, int height)
void ResizeDlg::Resize (CWnd * dialog, CWnd * window, int width, int height)
Resizes an object within a parent window but does not allow the object to shrink vertically.
Parameters
dialog pointer to the parent window
window pointer to the object to be resized
width the new width in pixels
height the new height in pixels
References CenterWindow(), MoveData::delta, MoveData::dialog, GetImageWindowDelta(), m_delta, m_dialog, m_window, OffsetChildPos(), OffsetWindowSize(), and MoveData::skip.
Referenced by COperatorConsoleDlg::OnInitDialog().
 {
    MoveData data;
    int         dy;
    m_dialog = dialog;
    m_window = window;
    //
    // Get the difference in size between the window and the desired width and height
    //
    GetImageWindowDelta(width, height);
    if (m_delta.cx != 0 || m_delta.cy != 0)
    {
       //
       // Resize the window
       //
       OffsetWindowSize(window, m_delta.cx, m_delta.cy);
       if (m_delta.cx < -16)
          m_delta.cx += 16;
       //
       // Resize the dialog.  It can grow or shrink in x, but
       // its height may not be less than its original height.
       //
       dy = m_delta.cy > 0 ? m_delta.cy : 0;
       OffsetWindowSize(dialog, m_delta.cx, dy);    // resize the dialog
       //
       // Center the window vertically in the dialog
       //
       CenterWindow(dialog, window, false, true);
       //
       // Move the rest of the items dx pixels to the left or right.  We're not
       // going to change the y coordinates, so we set m_delta.cy to 0.
       //
       m_delta.cy = 0;
       //
       // Move all of the dialog items to compensate for the new size of 'window'.  EnumChildWindows()
       // will call OffsetChildPos() for each of the Dialog's child windows (i.e. all dialog items).
       // We want to move every item except for the image item.
       //
       data.delta  = &m_delta;
       data.skip   = window->m_hWnd; // we don't want to move 'window'
       data.dialog = dialog->m_hWnd; // handle to the dialog window (we need this for converting coordinates)
       ::EnumChildWindows(dialog->m_hWnd, OffsetChildPos, (LPARAM)&data);
    }
 }
Member Data Documentation
CSize ResizeDlg::m_delta protected
Referenced by BidirectionalResize(), GetImageWindowDelta(), and Resize().
CWnd * ResizeDlg::m_dialog protected
Referenced by BidirectionalResize(), and Resize().
CWnd * ResizeDlg::m_window protected
Referenced by BidirectionalResize(), GetImageWindowDelta(), and Resize().
The documentation for this class was generated from the following files:
Documentation/Operator-Console/ResizeDlg.h
ResizeDlg.h
Documentation/Operator-Console/ResizeDlg.cpp
ResizeDlg.cpp